Repository pingcap/dm, pull requests merged in 2019-12, with the labels that each got.

#388 pkg: support to sync alter database DDL
  pkg/utils/util.go
  syncer/filter_test.go
  tests/all_mode/data/db1.increment.sql
Labels: should-cherry-pick-1.0, should-update-release-note, status/LGT2, type/enhancement

#390 *: use `IsRetryableError` in tidb-tools
  go.mod
  go.sum
  loader/db.go
  pkg/retry/errors.go
  pkg/retry/strategy_test.go
  syncer/db.go
  syncer/error_test.go
Labels: priority/normal, should-cherry-pick-1.0, should-update-release-note, status/LGT2, type/bug-fix

#392 log: skip 1 caller in ErrorFilterContextCanceled()
  pkg/log/log.go
Labels: priority/unimportant, should-cherry-pick-1.0, status/LGT2, type/bug-fix

#401 syncer: fix ignore canceled error
  syncer/syncer.go
Labels: priority/normal, should-cherry-pick-1.0, should-update-release-note, status/LGT2, type/bug-fix

#407 Fix the missing var dm_worker_instances for rolling_update_monitor
  dm/dm-ansible/rolling_update_monitor.yml
Labels: priority/normal, should-cherry-pick-1.0, should-update-release-note, status/LGT2, type/bug-fix

#377 *: fix context usage for SQL operation
  checker/checker.go
  checker/cmd.go
  dm/unit/unit.go
  dm/worker/relay.go
  dm/worker/relay_test.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  loader/checkpoint.go
  loader/checkpoint_test.go
  loader/loader.go
  loader/status.go
  mydumper/mydumper.go
  pkg/conn/baseconn.go
  pkg/context/context.go
  pkg/retry/strategy.go
  pkg/streamer/reader_test.go
  pkg/utils/db_test.go
  relay/relay.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/db.go
  syncer/ddl.go
  syncer/ddl_test.go
  syncer/ghost.go
  syncer/job.go
  syncer/online_ddl.go
  syncer/pt_osc.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/others_integration.txt
  tests/retry_cancel/conf/diff_config.toml
  tests/retry_cancel/conf/dm-master.toml
  tests/retry_cancel/conf/dm-task.yaml
  tests/retry_cancel/conf/dm-worker1.toml
  tests/retry_cancel/conf/dm-worker2.toml
  tests/retry_cancel/data/db1.increment.sql
  tests/retry_cancel/data/db1.prepare.sql
  tests/retry_cancel/data/db2.increment.sql
  tests/retry_cancel/data/db2.prepare.sql
  tests/retry_cancel/run.sh
Labels: already-cherry-pick-1.0, priority/normal, should-update-release-note, status/DNM, status/LGT2, type/bug-fix

#412 .*: add dm-portal
  Makefile
  cmd/dm-portal/main.go
  dm/portal/api.go
  dm/portal/api_test.go
  dm/portal/config.go
  dm/portal/config_test.go
  dm/portal/dm-fe/.gitignore
  dm/portal/dm-fe/README.md
  dm/portal/dm-fe/config-overrides.js
  dm/portal/dm-fe/package.json
  dm/portal/dm-fe/public/favicon.ico
  dm/portal/dm-fe/public/index.html
  dm/portal/dm-fe/public/manifest.json
  dm/portal/dm-fe/src/App.test.tsx
  dm/portal/dm-fe/src/App.tsx
  dm/portal/dm-fe/src/components/BinlogFilterModal.tsx
  dm/portal/dm-fe/src/components/InstancesStep.tsx
  dm/portal/dm-fe/src/components/Layout.tsx
  dm/portal/dm-fe/src/components/MigrateStep.tsx
  dm/portal/dm-fe/src/components/NamingStep.tsx
  dm/portal/dm-fe/src/components/StartStep.tsx
  dm/portal/dm-fe/src/components/UploadStep.tsx
  dm/portal/dm-fe/src/index.css
  dm/portal/dm-fe/src/index.tsx
  dm/portal/dm-fe/src/logo.svg
  dm/portal/dm-fe/src/react-app-env.d.ts
  dm/portal/dm-fe/src/serviceWorker.ts
  dm/portal/dm-fe/src/services/api.ts
  dm/portal/dm-fe/src/types.ts
  dm/portal/dm-fe/src/utils/config-util.ts
  dm/portal/dm-fe/src/utils/request.ts
  dm/portal/dm-fe/tsconfig.json
  dm/portal/dm-fe/yarn.lock
  dm/portal/statik/statik.go
  go.mod
  go.sum
Labels: priority/normal, should-cherry-pick-1.0, status/LGT2

#400 *: fix context usage for SQL operation (#377)
  checker/checker.go
  checker/cmd.go
  dm/unit/unit.go
  dm/worker/relay.go
  dm/worker/relay_test.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  loader/checkpoint.go
  loader/checkpoint_test.go
  loader/loader.go
  loader/status.go
  mydumper/mydumper.go
  pkg/conn/baseconn.go
  pkg/context/context.go
  pkg/retry/strategy.go
  pkg/streamer/reader_test.go
  pkg/utils/db_test.go
  relay/relay.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/db.go
  syncer/ddl.go
  syncer/ddl_test.go
  syncer/ghost.go
  syncer/job.go
  syncer/online_ddl.go
  syncer/pt_osc.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/others_integration.txt
  tests/retry_cancel/conf/diff_config.toml
  tests/retry_cancel/conf/dm-master.toml
  tests/retry_cancel/conf/dm-task.yaml
  tests/retry_cancel/conf/dm-worker1.toml
  tests/retry_cancel/conf/dm-worker2.toml
  tests/retry_cancel/data/db1.increment.sql
  tests/retry_cancel/data/db1.prepare.sql
  tests/retry_cancel/data/db2.increment.sql
  tests/retry_cancel/data/db2.prepare.sql
  tests/retry_cancel/run.sh
Labels: status/DNM, status/LGT1

#416 *: split unit test according to upstream MySQL
  Makefile
  dm/worker/worker_test.go
Labels: priority/normal, should-cherry-pick-1.0, status/LGT2, type/test

#418 *: cherry pick #378 and #416
  Makefile
  dm/worker/worker_test.go
  pkg/streamer/file_test.go
  pkg/streamer/hub_test.go
  pkg/streamer/reader_test.go
  pkg/utils/storage.go
  pkg/utils/storage_unix.go
  pkg/utils/storage_windows.go
  relay/writer/file_test.go
  relay/writer/file_util_test.go
Labels: priority/normal, status/LGT2, type/cherry-pick, type/test

#420 .*: add dm-portal (#412)
  Makefile
  cmd/dm-portal/main.go
  dm/portal/api.go
  dm/portal/api_test.go
  dm/portal/config.go
  dm/portal/config_test.go
  dm/portal/dm-fe/.gitignore
  dm/portal/dm-fe/README.md
  dm/portal/dm-fe/config-overrides.js
  dm/portal/dm-fe/package.json
  dm/portal/dm-fe/public/favicon.ico
  dm/portal/dm-fe/public/index.html
  dm/portal/dm-fe/public/manifest.json
  dm/portal/dm-fe/src/App.test.tsx
  dm/portal/dm-fe/src/App.tsx
  dm/portal/dm-fe/src/components/BinlogFilterModal.tsx
  dm/portal/dm-fe/src/components/InstancesStep.tsx
  dm/portal/dm-fe/src/components/Layout.tsx
  dm/portal/dm-fe/src/components/MigrateStep.tsx
  dm/portal/dm-fe/src/components/NamingStep.tsx
  dm/portal/dm-fe/src/components/StartStep.tsx
  dm/portal/dm-fe/src/components/UploadStep.tsx
  dm/portal/dm-fe/src/index.css
  dm/portal/dm-fe/src/index.tsx
  dm/portal/dm-fe/src/logo.svg
  dm/portal/dm-fe/src/react-app-env.d.ts
  dm/portal/dm-fe/src/serviceWorker.ts
  dm/portal/dm-fe/src/services/api.ts
  dm/portal/dm-fe/src/types.ts
  dm/portal/dm-fe/src/utils/config-util.ts
  dm/portal/dm-fe/src/utils/request.ts
  dm/portal/dm-fe/tsconfig.json
  dm/portal/dm-fe/yarn.lock
  dm/portal/statik/statik.go
  go.mod
  go.sum
Labels: priority/normal, status/LGT2, type/cherry-pick, type/feature

#419 dm-portal: don't generate table list for mydumper if DoTables is empty
  dm/portal/api.go
  dm/portal/api_test.go
Labels: bug, priority/normal, should-cherry-pick-1.0, status/LGT2

#425 Changelog: bump to v1.0.3
  CHANGELOG.md
Labels: priority/normal, should-cherry-pick-1.0, should-update-docs, status/LGT2, type/CHANGELOG

#429 ansible: release v1.0.3
  dm/dm-ansible/inventory.ini
Labels: priority/important, status/LGT1, type/dm-ansible

#423 pbmock: generate pb mock with reflect mode
  dm/pbmock/dmmaster.go
  dm/pbmock/dmworker.go
  tests/generate-mock.sh
Labels: priority/normal, should-cherry-pick-1.0, status/LGT2, type/test

#431 *: Register DM-worker instance into DM-master
  cmd/dm-worker/main.go
  dm/master/config.go
  dm/master/coordinator/coordinator.go
  dm/master/coordinator/worker.go
  dm/master/server.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmmaster.pb.gw.go
  dm/pb/dmworker.pb.go
  dm/pb/tracer.pb.go
  dm/pb/tracer_base.pb.go
  dm/pb/tracer_syncer.pb.go
  dm/proto/dmmaster.proto
  dm/worker/config.go
  dm/worker/join.go
  dm/worker/server.go
Labels: status/WIP

#403 *: fix DB connection close and all_mode integration test
  pkg/conn/baseconn.go
  tests/all_mode/run.sh
Labels: priority/unimportant, should-cherry-pick-1.0, status/LGT2, type/bug-fix, type/test

#436 *: fix DB connection close and all_mode integration test (#403)
  pkg/conn/baseconn.go
  tests/_utils/check_http_alive
  tests/all_mode/run.sh
Labels: priority/normal, should-update-release-note, status/LGT2, type/bug-fix, type/cherry-pick

#433 compile syncer independently
  Makefile
  cmd/dm-syncer/config.go
  cmd/dm-syncer/main.go
  cmd/dm-syncer/main_test.go
  dm/config/subtask.go
  dm/config/task.go
  tests/_utils/run_dm_syncer
  tests/dm_syncer/conf/diff_config.toml
  tests/dm_syncer/conf/dm-master.toml
  tests/dm_syncer/conf/dm-syncer-1.toml
  tests/dm_syncer/conf/dm-syncer-2.toml
  tests/dm_syncer/conf/dm-task.yaml
  tests/dm_syncer/conf/dm-worker1.toml
  tests/dm_syncer/conf/dm-worker2.toml
  tests/dm_syncer/conf/old_meta_file
  tests/dm_syncer/data/db1.increment.sql
  tests/dm_syncer/data/db1.prepare.sql
  tests/dm_syncer/data/db1.prepare.user.sql
  tests/dm_syncer/data/db2.increment.sql
  tests/dm_syncer/data/db2.prepare.sql
  tests/dm_syncer/data/db2.prepare.user.sql
  tests/dm_syncer/run.sh
  tests/others_integration.txt
  tests/run.sh
Labels: priority/important, status/LGT1, type/feature
