Repository pingcap/dm, pull requests merged in 2019-01, with the labels that each got.

#24 ansible: remove log-rotate option
  dm/dm-ansible/roles/dm-master/defaults/main.yml
  dm/dm-ansible/roles/dm-master/templates/run_dm-master.sh.j2
  dm/dm-ansible/roles/dm-worker/defaults/main.yml
  dm/dm-ansible/roles/dm-worker/templates/run_dm-worker.sh.j2
Labels: priority/normal, status/LGTM1, type/bug-fix

#25 *: add check-task cmd; refine output format
  checker/cmd.go
  dm/ctl/common/util.go
  dm/ctl/ctl.go
  dm/ctl/master/check_task.go
  dm/ctl/master/start_task.go
  dm/ctl/master/update_task.go
  dm/master/server.go
Labels: priority/normal, status/LGTM2, type/feature

#32 hide coveralls token
  Makefile
Labels: priority/normal, status/LGTM1, type/enhancement
