Repository pingcap/dm, pull requests merged in 2019-10, with the labels that each got.

#299 .*: remove column mapping in example config file and help output
  README.md
  checker/checker.go
  dm/ctl/master/update_task.go
  dm/dm-ansible/conf/task.yaml.example
  dm/master/task.yaml
Labels: priority/normal, should-cherry-pick-1.0, should-update-docs, status/LGT2

#306 *: update go.mod
  go.mod
  go.sum
Labels: priority/normal, should-cherry-pick-1.0, status/LGT2, type/enhancement

#308 .*: remove column mapping in example config file and help output (#299)
  README.md
  checker/checker.go
  dm/ctl/master/update_task.go
  dm/dm-ansible/conf/task.yaml.example
  dm/master/task.yaml
Labels: priority/normal, status/LGT2, type/cherry-pick

#305 worker: fix potential panic when restoring subtask from meta
  dm/worker/worker.go
  dm/worker/worker_test.go
Labels: priority/normal, should-cherry-pick-1.0, should-update-release-note, status/LGT2, type/bug-fix

#312 *: add two black DML cases for auto recovery; fix panic when commit DML txn failed
  dm/worker/task_checker.go
  dm/worker/task_checker_test.go
  pkg/baseconn/conn.go
Labels: priority/important, release-blocker, should-cherry-pick-1.0, should-update-release-note, status/LGT2, type/bug-fix

#309 task config: add thread config for mydumper, loader and syncer
  dm/config/task.go
  dm/config/task_test.go
  dm/dm-ansible/conf/task_advanced.yaml.example
  dm/dm-ansible/conf/task_basic.yaml.example
  dm/master/task_advanced.yaml
  dm/master/task_basic.yaml
Labels: priority/normal, release-blocker, should-cherry-pick-1.0, should-update-docs, should-update-release-note, status/LGT2

#304 relay: begin with the latest binlog file if relay position is not set
  pkg/utils/db.go
  relay/meta.go
  relay/meta_test.go
  relay/relay.go
  relay/relay_test.go
  syncer/db.go
  tests/initial_unit/run.sh
Labels: priority/normal, release-blocker, should-cherry-pick-1.0, should-update-docs, status/LGT2, type/enhancement

#316 master: only fetch necessary DM-worker's config
  dm/master/server.go
  dm/master/server_test.go
  tests/start_task/conf/dm-master.toml
  tests/start_task/run.sh
Labels: priority/normal, release-blocker, should-cherry-pick-1.0, should-update-release-note, status/LGT2, type/bug-fix

#297 DM-worker: add error abstraction in pb.ProcessError
  checker/checker.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/unit/unit.go
  dm/worker/relay.go
  dm/worker/relay_test.go
  dm/worker/status.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  dm/worker/task_checker.go
  dm/worker/task_checker_test.go
  loader/loader.go
  mydumper/mydumper.go
  relay/relay.go
  syncer/mode.go
  syncer/syncer.go
Labels: priority/normal, release-blocker, should-cherry-pick-1.0, should-update-release-note, status/LGT2, type/enhancement

#320 DM-worker: add error abstraction in pb.ProcessError (#297)
  checker/checker.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/unit/unit.go
  dm/worker/relay.go
  dm/worker/relay_test.go
  dm/worker/status.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  dm/worker/task_checker.go
  dm/worker/task_checker_test.go
  loader/loader.go
  mydumper/mydumper.go
  relay/relay.go
  syncer/mode.go
  syncer/syncer.go
Labels: priority/normal, status/LGT2, type/cherry-pick

#321 syncer: fast fail on some error in ddl execution (#317)
  dm/worker/task_checker.go
  pkg/retry/errors.go
  syncer/db.go
Labels: priority/normal, status/LGT2, type/cherry-pick

#266 dm-worker: refine conn
  .gitignore
  dm/config/subtask.go
  loader/checkpoint.go
  loader/checkpoint_test.go
  loader/db.go
  loader/loader.go
  pkg/conn/baseconn.go
  pkg/conn/baseconn_test.go
  pkg/conn/basedb.go
  pkg/conn/basedb_test.go
  pkg/retry/errors.go
  pkg/retry/strategy_test.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/db.go
  syncer/db_test.go
  syncer/ghost.go
  syncer/online_ddl.go
  syncer/pt_osc.go
  syncer/sharding_group.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: priority/normal, release-blocker, should-cherry-pick-1.0, status/LGT2, type/enhancement

#310 mydumper: generate tables needed to dump for mydumper automatically
  dm/config/task.go
  dm/worker/worker_test.go
  mydumper/mydumper.go
  mydumper/mydumper_test.go
  mydumper/util.go
  pkg/utils/common.go
  tests/all_mode/conf/dm-task.yaml
  tests/compatibility/conf/dm-task.yaml
  tests/dmctl_basic/conf/dm-task.yaml
  tests/http_apis/conf/dm-task.yaml
  tests/incremental_mode/conf/dm-task.yaml
  tests/initial_unit/conf/dm-task.yaml
  tests/load_interrupt/conf/dm-task.yaml
  tests/online_ddl/conf/dm-task.yaml
  tests/print_status/conf/dm-task.yaml
  tests/relay_interrupt/conf/dm-task.yaml
  tests/safe_mode/conf/dm-task.yaml
  tests/sequence_safe_mode/conf/dm-task.yaml
  tests/sequence_sharding/conf/dm-task.yaml
  tests/sharding/conf/dm-task.yaml
  tests/start_task/conf/dm-task.yaml
Labels: priority/normal, release-blocker, should-cherry-pick-1.0, should-update-docs, should-update-release-note, status/LGT2

#325 dm-worker: refine conn (#266)
  .gitignore
  dm/config/subtask.go
  loader/checkpoint.go
  loader/checkpoint_test.go
  loader/db.go
  loader/loader.go
  pkg/conn/baseconn.go
  pkg/conn/baseconn_test.go
  pkg/conn/basedb.go
  pkg/conn/basedb_test.go
  pkg/retry/errors.go
  pkg/retry/strategy_test.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/db.go
  syncer/db_test.go
  syncer/ghost.go
  syncer/online_ddl.go
  syncer/pt_osc.go
  syncer/sharding_group.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: priority/normal, release-blocker, status/LGT2, type/cherry-pick, type/enhancement

#315 checker: increase total timeout to 30m; set readTimeout for DB check operation to 30s
  checker/checker.go
Labels: priority/normal, release-blocker, should-cherry-pick-1.0, status/LGT2, type/bug-fix

#323 worker: generate index flavor automatically by querying version info from DB
  dm/worker/config.go
  dm/worker/config_test.go
  pkg/utils/db.go
  tests/all_mode/conf/dm-worker1.toml
  tests/all_mode/conf/dm-worker2.toml
  tests/compatibility/conf/dm-worker1.toml
  tests/compatibility/conf/dm-worker2.toml
  tests/dmctl_basic/conf/dm-worker1.toml
  tests/dmctl_basic/conf/dm-worker2.toml
  tests/http_apis/conf/dm-worker1.toml
  tests/incremental_mode/conf/dm-worker1.toml
  tests/incremental_mode/conf/dm-worker2.toml
  tests/initial_unit/conf/dm-worker1.toml
  tests/load_interrupt/conf/dm-worker1.toml
  tests/load_interrupt/conf/dm-worker2.toml
  tests/online_ddl/conf/dm-worker1.toml
  tests/online_ddl/conf/dm-worker2.toml
  tests/print_status/conf/dm-worker1.toml
  tests/relay_interrupt/conf/dm-worker1.toml
  tests/safe_mode/conf/dm-worker1.toml
  tests/safe_mode/conf/dm-worker2.toml
  tests/sequence_safe_mode/conf/dm-worker1.toml
  tests/sequence_safe_mode/conf/dm-worker2.toml
  tests/sequence_sharding/conf/dm-worker1.toml
  tests/sequence_sharding/conf/dm-worker2.toml
  tests/sharding/conf/dm-worker1.toml
  tests/sharding/conf/dm-worker2.toml
  tests/start_task/conf/dm-worker1.toml
Labels: priority/normal, release-blocker, should-cherry-pick-1.0, should-update-docs, should-update-release-note, status/LGT2

#293 rfc: add data flow control
  docs/RFCS/20190906_flow_control.md
  docs/media/rfc-load-benchmark.png
Labels: priority/normal, status/LGT2, type/feature

#328 worker: generate index flavor automatically by querying version info from DB (#323)
  dm/worker/config.go
  dm/worker/config_test.go
  pkg/utils/db.go
  tests/all_mode/conf/dm-worker1.toml
  tests/all_mode/conf/dm-worker2.toml
  tests/compatibility/conf/dm-worker1.toml
  tests/compatibility/conf/dm-worker2.toml
  tests/dmctl_basic/conf/dm-worker1.toml
  tests/dmctl_basic/conf/dm-worker2.toml
  tests/http_apis/conf/dm-worker1.toml
  tests/incremental_mode/conf/dm-worker1.toml
  tests/incremental_mode/conf/dm-worker2.toml
  tests/initial_unit/conf/dm-worker1.toml
  tests/load_interrupt/conf/dm-worker1.toml
  tests/load_interrupt/conf/dm-worker2.toml
  tests/online_ddl/conf/dm-worker1.toml
  tests/online_ddl/conf/dm-worker2.toml
  tests/print_status/conf/dm-worker1.toml
  tests/relay_interrupt/conf/dm-worker1.toml
  tests/safe_mode/conf/dm-worker1.toml
  tests/safe_mode/conf/dm-worker2.toml
  tests/sequence_safe_mode/conf/dm-worker1.toml
  tests/sequence_safe_mode/conf/dm-worker2.toml
  tests/sequence_sharding/conf/dm-worker1.toml
  tests/sequence_sharding/conf/dm-worker2.toml
  tests/sharding/conf/dm-worker1.toml
  tests/sharding/conf/dm-worker2.toml
  tests/start_task/conf/dm-worker1.toml
Labels: priority/normal, release-blocker, should-update-docs, should-update-release-note, status/LGT2, type/cherry-pick

#330 *: only retry for special message with 1105
  pkg/retry/errors.go
  syncer/db.go
  syncer/error_test.go
  tests/load_interrupt/run.sh
Labels: priority/normal, should-cherry-pick-1.0, should-update-release-note, status/LGT2, type/bug-fix

#331 DM-worker: fix toml decode time.duration in config
  dm/worker/config.go
  dm/worker/config_test.go
  dm/worker/dm-worker.toml
  dm/worker/relay.go
  dm/worker/task_checker.go
  dm/worker/task_checker_test.go
  dm/worker/worker_test.go
  tests/all_mode/conf/dm-worker1.toml
  tests/all_mode/conf/dm-worker2.toml
Labels: priority/normal, should-cherry-pick-1.0, status/LGT2, type/bug-fix

#329 worker: use random value as server-id if server-id is not set
  cmd/dm-worker/main.go
  dm/config/subtask.go
  dm/worker/config.go
  dm/worker/config_test.go
  pkg/utils/db.go
  pkg/utils/db_test.go
  relay/config.go
  syncer/db_test.go
  syncer/heartbeat.go
  syncer/online_ddl.go
  syncer/syncer.go
  tests/all_mode/conf/dm-worker1.toml
  tests/all_mode/conf/dm-worker2.toml
  tests/compatibility/conf/dm-worker1.toml
  tests/compatibility/conf/dm-worker2.toml
  tests/dmctl_basic/conf/dm-worker1.toml
  tests/dmctl_basic/conf/dm-worker2.toml
  tests/http_apis/conf/dm-worker1.toml
  tests/incremental_mode/conf/dm-worker1.toml
  tests/incremental_mode/conf/dm-worker2.toml
  tests/initial_unit/conf/dm-worker1.toml
  tests/load_interrupt/conf/dm-worker1.toml
  tests/load_interrupt/conf/dm-worker2.toml
  tests/online_ddl/conf/dm-worker1.toml
  tests/online_ddl/conf/dm-worker2.toml
  tests/print_status/conf/dm-worker1.toml
  tests/relay_interrupt/conf/dm-worker1.toml
  tests/safe_mode/conf/dm-worker1.toml
  tests/safe_mode/conf/dm-worker2.toml
  tests/sequence_safe_mode/conf/dm-worker1.toml
  tests/sequence_safe_mode/conf/dm-worker2.toml
  tests/sequence_sharding/conf/dm-worker1.toml
  tests/sequence_sharding/conf/dm-worker2.toml
  tests/sharding/conf/dm-worker1.toml
  tests/sharding/conf/dm-worker2.toml
  tests/start_task/conf/dm-worker1.toml
Labels: priority/normal, should-cherry-pick-1.0, should-update-docs, should-update-release-note, status/LGT2

#337 worker: use random value as server-id if server-id is not set (#329)
  cmd/dm-worker/main.go
  dm/config/subtask.go
  dm/worker/config.go
  dm/worker/config_test.go
  pkg/utils/db.go
  pkg/utils/db_test.go
  relay/config.go
  syncer/db_test.go
  syncer/heartbeat.go
  syncer/online_ddl.go
  syncer/syncer.go
  tests/all_mode/conf/dm-worker1.toml
  tests/all_mode/conf/dm-worker2.toml
  tests/compatibility/conf/dm-worker1.toml
  tests/compatibility/conf/dm-worker2.toml
  tests/dmctl_basic/conf/dm-worker1.toml
  tests/dmctl_basic/conf/dm-worker2.toml
  tests/http_apis/conf/dm-worker1.toml
  tests/incremental_mode/conf/dm-worker1.toml
  tests/incremental_mode/conf/dm-worker2.toml
  tests/initial_unit/conf/dm-worker1.toml
  tests/load_interrupt/conf/dm-worker1.toml
  tests/load_interrupt/conf/dm-worker2.toml
  tests/online_ddl/conf/dm-worker1.toml
  tests/online_ddl/conf/dm-worker2.toml
  tests/print_status/conf/dm-worker1.toml
  tests/relay_interrupt/conf/dm-worker1.toml
  tests/safe_mode/conf/dm-worker1.toml
  tests/safe_mode/conf/dm-worker2.toml
  tests/sequence_safe_mode/conf/dm-worker1.toml
  tests/sequence_safe_mode/conf/dm-worker2.toml
  tests/sequence_sharding/conf/dm-worker1.toml
  tests/sequence_sharding/conf/dm-worker2.toml
  tests/sharding/conf/dm-worker1.toml
  tests/sharding/conf/dm-worker2.toml
  tests/start_task/conf/dm-worker1.toml
Labels: priority/normal, should-update-release-note, status/LGT2, type/cherry-pick

#336 *: fix executing shard DDL with mismatched request
  dm/master/server.go
  dm/master/server_test.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmworker.pb.go
  dm/pb/tracer.pb.go
  dm/pb/tracer_base.pb.go
  dm/pb/tracer_syncer.pb.go
  dm/proto/dmworker.proto
  syncer/error.go
  syncer/error_test.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: priority/important, release-blocker, should-cherry-pick-1.0, should-update-release-note, status/LGT1, type/bug-fix

#335 relay: fix GTID recover after relay log recovered
  _utils/terror_gen/errors_release.txt
  pkg/binlog/event/event.go
  pkg/gtid/gtid.go
  pkg/gtid/gtid_test.go
  pkg/terror/error_list.go
  relay/relay.go
  relay/relay_test.go
Labels: priority/normal, release-blocker, should-cherry-pick-1.0, should-update-release-note, status/LGT2, type/bug-fix

#334 dmctl: simplify default query-status output
  cmd/dm-ctl/main.go
  dm/ctl/common/util.go
  dm/ctl/master/query_status.go
  dm/ctl/master/query_status_test.go
  tests/dmctl_basic/check_list/query_status.sh
  tests/relay_interrupt/run.sh
  tests/start_task/run.sh
Labels: priority/normal, should-cherry-pick-1.0, should-update-docs, should-update-release-note, status/LGT2

#341 CHANGELOG: add release notes for v1.0.2
  CHANGELOG.md
Labels: priority/important, should-cherry-pick-1.0, should-update-dm-ansible, should-update-docs, status/LGT2, type/CHANGELOG

#343 ansible: release v1.0.2
  dm/dm-ansible/inventory.ini
Labels: priority/important, status/LGT2, type/dm-ansible
