Repository pingcap/dm, pull requests merged in 2019-11, with the labels that each got.

#346 dm-ansible: don't add config in config file if not setted in inventory.ini
  dm/dm-ansible/roles/dm-worker/templates/dm-worker.toml.j2
Labels: should-cherry-pick-1.0, status/LGT2, type/bug-fix, type/dm-ansible

#344 dm-master: embed etcd in DM-master
  _utils/terror_gen/errors_release.txt
  cmd/dm-master/main.go
  dm/master/config.go
  dm/master/config_test.go
  dm/master/dm-master.toml
  dm/master/etcd.go
  dm/master/http_handler.go
  dm/master/server.go
  dm/master/server_test.go
  dm/master/status.go
  dm/master/status_test.go
  go.mod
  pkg/terror/error_list.go
  tests/dmctl_basic/conf/dm-master.toml
Labels: feature-request, priority/important, should-update-dm-ansible, should-update-docs, should-update-release-note, status/LGT2, type/feature

#345 error-msg: improve error message output
  _utils/terror_gen/errors_release.txt
  dm/config/task.go
  dm/master/server.go
  dm/worker/subtask.go
  pkg/streamer/reader.go
  pkg/streamer/reader_test.go
  pkg/terror/error_list.go
  pkg/utils/util.go
  relay/common/util.go
  syncer/filter.go
  syncer/syncer.go
Labels: priority/normal, should-cherry-pick-1.0, should-update-dm-ansible, should-update-release-note, status/LGT2

#349 fix data race in import unit(loader)
  dm/worker/subtask.go
  loader/loader.go
  tests/import_goroutine_leak/conf/dm-master.toml
  tests/import_goroutine_leak/conf/dm-task.yaml
  tests/import_goroutine_leak/conf/dm-worker1.toml
  tests/import_goroutine_leak/conf/dm-worker2.toml
  tests/import_goroutine_leak/run.sh
Labels: priority/normal, should-cherry-pick-1.0, should-update-release-note, status/LGT2, type/bug-fix

#350 dm-master: join a new member into an existing cluster
  _utils/terror_gen/errors_release.txt
  dm/master/config.go
  dm/master/config_test.go
  dm/master/dm-master.toml
  dm/master/etcd.go
  dm/master/etcd_test.go
  dm/master/server.go
  dm/master/server_test.go
  go.mod
  go.sum
  pkg/etcdutil/etcdutil.go
  pkg/etcdutil/etcdutil_test.go
  pkg/terror/error_list.go
Labels: priority/important, should-update-dm-ansible, should-update-docs, should-update-release-note, status/LGT2, type/feature

#356 dmctl: optimize query-status info
  dm/ctl/master/query_status.go
  dm/ctl/master/query_status_test.go
  tests/relay_interrupt/run.sh
Labels: priority/normal, should-cherry-pick-1.0, should-update-docs, status/LGT2

#359 mydumper/: change Equal to HasPrefix in func needToGenerateDoTables
  _utils/terror_gen/errors_release.txt
  mydumper/mydumper_test.go
  mydumper/util.go
  pkg/terror/error_list.go
Labels: priority/normal, should-cherry-pick-1.0, status/LGT2

#287 dmctl: add command mode
  cmd/dm-ctl/main.go
  dm/ctl/common/config.go
  dm/ctl/ctl.go
  dm/ctl/master/break_ddl_lock.go
  dm/ctl/master/check_task.go
  dm/ctl/master/migrate_relay.go
  dm/ctl/master/pause_relay.go
  dm/ctl/master/pause_task.go
  dm/ctl/master/purge_relay.go
  dm/ctl/master/query_error.go
  dm/ctl/master/query_status.go
  dm/ctl/master/refresh_worker_tasks.go
  dm/ctl/master/resume_relay.go
  dm/ctl/master/resume_task.go
  dm/ctl/master/show_ddl_locks.go
  dm/ctl/master/sql_inject.go
  dm/ctl/master/sql_replace.go
  dm/ctl/master/sql_skip.go
  dm/ctl/master/start_task.go
  dm/ctl/master/stop_task.go
  dm/ctl/master/switch_relay_master.go
  dm/ctl/master/unlock_ddl_lock.go
  dm/ctl/master/update_masterconfig.go
  dm/ctl/master/update_relay.go
  dm/ctl/master/update_task.go
  tests/dmctl_command/conf/diff_config.toml
  tests/dmctl_command/conf/dm-master.toml
  tests/dmctl_command/conf/dm-task.yaml
  tests/dmctl_command/conf/dm-worker1.toml
  tests/dmctl_command/conf/dm-worker2.toml
  tests/dmctl_command/data/db1.increment.sql
  tests/dmctl_command/data/db1.prepare.sql
  tests/dmctl_command/data/db2.increment.sql
  tests/dmctl_command/data/db2.prepare.sql
  tests/dmctl_command/run.sh
Labels: priority/important, should-cherry-pick-1.0, should-update-docs, should-update-release-note, status/LGT2, type/feature

#362 release-1.0: upgrade golang and module
  CONTRIBUTING.md
  _utils/terror_gen/errors_release.txt
  checker/checker.go
  go.mod
  go.sum
  loader/loader.go
  mydumper/util.go
  pkg/log/log.go
  pkg/terror/error_list.go
  syncer/db_test.go
  syncer/ddl_test.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: priority/normal, status/LGT2, type/enhancement

#360 *: combine etcd log into dm-master
  CONTRIBUTING.md
  _utils/terror_gen/errors_release.txt
  checker/checker.go
  dm/master/config.go
  dm/master/config_test.go
  dm/master/etcd.go
  dm/master/etcd_test.go
  dm/master/server.go
  dm/master/server_test.go
  go.mod
  go.sum
  loader/loader.go
  mydumper/util.go
  pkg/encrypt/encrypt.go
  pkg/etcdutil/etcdutil_test.go
  pkg/log/log.go
  pkg/terror/error_list.go
  syncer/ddl_test.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/_utils/check_http_alive
  tests/http_apis/run.sh
Labels: priority/normal, should-update-release-note, status/LGT2, type/feature

#235 debug-tools: Binlog event blackhole
  Makefile
  debug-tools/binlog-event-blackhole/README.md
  debug-tools/binlog-event-blackhole/config.go
  debug-tools/binlog-event-blackhole/fetcher.go
  debug-tools/binlog-event-blackhole/main.go
  debug-tools/binlog-event-blackhole/packet.go
Labels: priority/normal, qa, status/LGT1

#365 dmctl/:Clear workers cache before we run a command
  dm/ctl/ctl.go
Labels: priority/normal, should-cherry-pick-1.0, status/LGT2, type/bug-fix

#372 checker/:ignore unnecessary privilege for different task modes
  checker/cmd.go
  cmd/dm-master/main.go
  cmd/dm-tracer/main.go
  cmd/dm-worker/main.go
  tests/_utils/check_count
  tests/full_mode/conf/diff_config.toml
  tests/full_mode/conf/dm-master.toml
  tests/full_mode/conf/dm-task.yaml
  tests/full_mode/conf/dm-worker1.toml
  tests/full_mode/conf/dm-worker2.toml
  tests/full_mode/data/db1.prepare.sql
  tests/full_mode/data/db1.prepare.user.sql
  tests/full_mode/data/db2.prepare.sql
  tests/full_mode/data/db2.prepare.user.sql
  tests/full_mode/run.sh
  tests/incremental_mode/data/db1.prepare.user.sql
  tests/incremental_mode/data/db2.prepare.user.sql
  tests/incremental_mode/run.sh
  tests/others_integration.txt
Labels: priority/normal, should-cherry-pick-1.0, should-update-docs, should-update-release-note, status/LGT2

#367 dm-master: leader election
  _utils/terror_gen/errors_release.txt
  dm/master/election.go
  dm/master/etcd.go
  dm/master/server.go
  dm/master/server_test.go
  pkg/election/election.go
  pkg/election/election_test.go
  pkg/etcdutil/etcdutil.go
  pkg/etcdutil/etcdutil_test.go
  pkg/terror/error_list.go
  tests/others_integration.txt
Labels: priority/important, should-update-release-note, status/LGT2, type/feature

#375 *: fix `cannot convert type: decimal.Decimal`
  go.mod
  go.sum
  tests/all_mode/data/db1.increment.sql
Labels: priority/important, should-cherry-pick-1.0, status/LGT2, type/bug-fix

#355 loader/syncer: filter context cancel error while executing sqls
  loader/db.go
  loader/loader.go
  pkg/conn/baseconn.go
  pkg/log/log.go
  pkg/utils/util.go
  syncer/db.go
  syncer/syncer.go
  syncer/warning.go
Labels: priority/normal, should-cherry-pick-1.0, status/LGT1

#378 *: support running unit test on Windows
  Makefile
  pkg/streamer/file_test.go
  pkg/streamer/hub_test.go
  pkg/streamer/reader_test.go
  pkg/utils/storage.go
  pkg/utils/storage_unix.go
  pkg/utils/storage_windows.go
  relay/writer/file_test.go
  relay/writer/file_util_test.go
Labels: priority/unimportant, status/LGT2, type/enhancement

#381 loader/syncer: fix bug in #355
  pkg/log/log.go
  pkg/log/log_test.go
Labels: priority/normal, status/LGT2

#380 config/task: add check for duplicate config items
  _utils/terror_gen/errors_release.txt
  dm/config/task.go
  dm/config/task_test.go
  pkg/terror/error_list.go
Labels: priority/normal, should-cherry-pick-1.0, should-update-release-note, status/LGT2

#382 loader/syncer: filter context cancel error while executing sqls (#355)
  loader/db.go
  loader/loader.go
  pkg/conn/baseconn.go
  pkg/log/log.go
  pkg/log/log_test.go
  pkg/utils/util.go
  syncer/db.go
  syncer/syncer.go
  syncer/warning.go
Labels: priority/normal, status/DNM, status/LGT2, type/cherry-pick

#384 pkg: support alter database in parser util pkg
  pkg/parser/common.go
  pkg/parser/common_test.go
Labels: priority/normal, should-cherry-pick-1.0, should-update-release-note, status/LGT2, type/bug-fix

#383 go.mod:update go.mod and go.sum to new tidb-tools
  go.mod
  go.sum
Labels: priority/normal, should-cherry-pick-1.0, status/LGT2
