Repository pingcap/dm, pull requests merged in 2019-07, with the labels that each got.

#172 log refactor: tracer
  dm/tracer/config.go
  dm/tracer/http_handler.go
  dm/tracer/http_status.go
  dm/tracer/server.go
  dm/tracer/store.go
  pkg/tracing/tracer_test.go
Labels: priority/normal, status/LGTM2

#192 *: add release notes for 1.0 RC.1
  CHANGELOG.md
Labels: priority/normal, status/LGTM2, type/doc

#196 Add dm-worker parameters
  dm/dm-ansible/roles/dm-worker/templates/dm-worker.toml.j2
Labels: status/LGTM2

#202 dm-worker: Should use fmt.Printf instead of the uninitialized logger
  cmd/dm-worker/main.go
Labels: priority/normal, status/LGTM2, type/bug-fix

#203 Add syncer sharding test
  go.mod
  go.sum
  syncer/syncer_test.go
  tests/safe_mode/conf/dm-task.yaml
  tests/sequence_safe_mode/conf/dm-task.yaml
Labels: priority/unimportant, qa, status/LGTM2, type/test

#198 syncer: refine syncer test to trigger casuality
  syncer/syncer_test.go
Labels: priority/normal, status/LGTM1, type/test

#199 *: Use insert for non safe-mode instead of replace
  dm/tracer/http_handler.go
  dm/tracer/http_handler_test.go
  dm/tracer/http_status.go
  dm/tracer/store.go
  syncer/dml.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/_dmctl_tools/check_safe_mode.go
  tests/safe_mode/run.sh
  tests/sequence_safe_mode/run.sh
Labels: priority/normal, status/LGTM2, type/enhancement

#204 loader: return error if parse mydumper meta data failed
  loader/loader.go
Labels: priority/unimportant, status/LGTM2, type/enhancement

#208 tests: fix safe mode test
  tests/README.md
  tests/_utils/truncate_trace_events
  tests/safe_mode/run.sh
  tests/sequence_safe_mode/run.sh
Labels: priority/normal, qa, status/LGTM2, type/test

#207 worker: close kv db when worker exits
  dm/worker/worker.go
Labels: priority/unimportant, status/LGTM2, type/enhancement

#210 dm-ansible: Make sure stdout is outputted
  dm/dm-ansible/roles/dm-master/defaults/main.yml
  dm/dm-ansible/roles/dm-master/templates/run_dm-master.sh.j2
  dm/dm-ansible/roles/dm-worker/defaults/main.yml
  dm/dm-ansible/roles/dm-worker/templates/run_dm-worker.sh.j2
Labels: priority/normal, status/LGTM2, type/enhancement

#212 master/worker/task add strictly config verification
  dm/config/task.go
  dm/config/task_test.go
  dm/dm-ansible/roles/dm-worker/templates/dm-worker.toml.j2
  dm/master/config.go
  dm/master/config_test.go
  dm/master/server_test.go
  dm/worker/config.go
  dm/worker/config_test.go
  tests/all_mode/conf/dm-task.yaml
  tests/all_mode/conf/dm-worker1.toml
  tests/all_mode/conf/dm-worker2.toml
  tests/dmctl_basic/conf/dm-task.yaml
  tests/dmctl_basic/conf/dm-worker1.toml
  tests/dmctl_basic/conf/dm-worker2.toml
  tests/incremental_mode/conf/dm-task.yaml
  tests/incremental_mode/conf/dm-worker1.toml
  tests/incremental_mode/conf/dm-worker2.toml
  tests/load_interrupt/conf/dm-task.yaml
  tests/load_interrupt/conf/dm-worker1.toml
  tests/load_interrupt/conf/dm-worker2.toml
  tests/online_ddl/conf/dm-task.yaml
  tests/online_ddl/conf/dm-worker1.toml
  tests/online_ddl/conf/dm-worker2.toml
  tests/print_status/conf/dm-task.yaml
  tests/print_status/conf/dm-worker1.toml
  tests/safe_mode/conf/dm-task.yaml
  tests/safe_mode/conf/dm-worker1.toml
  tests/safe_mode/conf/dm-worker2.toml
  tests/sequence_safe_mode/conf/dm-task.yaml
  tests/sequence_safe_mode/conf/dm-worker1.toml
  tests/sequence_safe_mode/conf/dm-worker2.toml
  tests/sequence_sharding/conf/dm-task.yaml
  tests/sequence_sharding/conf/dm-worker1.toml
  tests/sequence_sharding/conf/dm-worker2.toml
  tests/sharding/conf/dm-task.yaml
  tests/sharding/conf/dm-worker1.toml
  tests/sharding/conf/dm-worker2.toml
Labels: feature-request, priority/normal, status/LGTM2, type/feature

#215 Combine syncer localReader into one interface
  pkg/streamer/reader.go
  pkg/streamer/reader_test.go
  syncer/syncer.go
Labels: feature-request, priority/normal, status/LGTM2, type/feature

#211 rfc: add error handling
  docs/RFCS/20190722_error_handling.md
Labels: priority/normal, status/LGTM2, type/doc

#219 dm-ansible: support dm-portal
  dm/dm-ansible/deploy.yml
  dm/dm-ansible/group_vars/dm_portal_servers.yml
  dm/dm-ansible/inventory.ini
  dm/dm-ansible/roles/dm-portal/defaults/main.yml
  dm/dm-ansible/roles/dm-portal/meta/main.yml
  dm/dm-ansible/roles/dm-portal/tasks/binary_deployment.yml
  dm/dm-ansible/roles/dm-portal/tasks/main.yml
  dm/dm-ansible/roles/dm-portal/tasks/systemd_deployment.yml
  dm/dm-ansible/roles/dm-portal/templates/run_dm-portal.sh.j2
  dm/dm-ansible/roles/download/templates/packages.yml.j2
  dm/dm-ansible/rolling_update.yml
  dm/dm-ansible/start.yml
  dm/dm-ansible/stop.yml
  dm/dm-ansible/unsafe_cleanup.yml
Labels: priority/normal, status/LGTM2, type/feature
