Repository pingcap/dm, pull requests merged in 2019-06, with the labels that each got.

#161 tests: refine integration test
  tests/_utils/run_dm_worker
  tests/print_status/run.sh
Labels: priority/normal, qa, status/LGTM1, type/test

#164 *: add source-id checker
  dm/config/checking_item.go
  dm/config/subtask.go
  dm/config/subtask_test.go
  dm/dm-ansible/roles/check_config_static/tasks/main.yml
  dm/worker/config.go
  dm/worker/config_test.go
Labels: priority/normal, status/LGTM1, type/enhancement

#166 tests: change covermode to reduce dmctl test execution time
  Makefile
  syncer/syncer.go
  tests/_utils/run_dm_ctl
  tests/dmctl_basic/conf/dm-task.yaml
  tests/dmctl_basic/run.sh
Labels: priority/normal, qa, status/LGTM1, type/enhancement

#140 streamer: refactor and add test cases
  dm/worker/config.go
  dm/worker/config_test.go
  dm/worker/server_test.go
  pkg/binlog/filename.go
  pkg/binlog/filename_test.go
  pkg/binlog/position.go
  pkg/binlog/position_test.go
  pkg/streamer/file.go
  pkg/streamer/file_test.go
  pkg/streamer/hub.go
  pkg/streamer/hub_test.go
  pkg/streamer/reader.go
  pkg/streamer/reader_test.go
  pkg/streamer/streamer_test.go
  pkg/streamer/util.go
  pkg/streamer/util_test.go
  pkg/streamer/utils.go
  pkg/streamer/utils_test.go
  relay/meta.go
  relay/relay.go
  relay/writer/file.go
  relay/writer/file_test.go
  syncer/relay.go
  syncer/status.go
  syncer/syncer.go
Labels: priority/normal, qa, status/LGTM2, type/enhancement

#174 *: update go mod
  go.mod
  go.sum
  pkg/parser/common_test.go
Labels: priority/normal, status/LGTM2, type/enhancement

#162 log refactor: dm-master
  cmd/dm-master/main.go
  dm/config/subtask.go
  dm/config/task.go
  dm/master/config.go
  dm/master/server.go
  dm/master/sql-operator/operator.go
  dm/master/status.go
  pkg/parser/common.go
  pkg/tracing/tracer.go
Labels: priority/normal, status/LGTM2, type/enhancement

#160 syncer: add pipeline struct
  syncer/pipe.go
  syncer/syncer_test.go
Labels: status/LGTM2

#179 loader: refine some error messages
  loader/loader.go
Labels: priority/unimportant, status/LGTM2, type/enhancement

#157 rpc: add rate limit and rpc client manage in dm-master
  dm/ctl/common/config.go
  dm/ctl/common/util.go
  dm/ctl/ctl.go
  dm/ctl/dmctl.toml
  dm/ctl/master/query_status.go
  dm/master/agent_pool.go
  dm/master/agent_pool_test.go
  dm/master/config.go
  dm/master/dm-master.toml
  dm/master/server.go
  dm/master/server_test.go
  dm/master/status_test.go
  dm/master/workerrpc/interface.go
  dm/master/workerrpc/rawgrpc.go
  go.mod
  go.sum
Labels: priority/normal, status/LGTM2, type/enhancement

#186 loader: generate db-schema-create.sql file if not exists
  loader/loader.go
  loader/util.go
  loader/util_test.go
Labels: priority/normal, status/LGTM2, type/enhancement

#185 loader: fix break in forloop and some minor refine
  loader/db.go
  loader/loader.go
Labels: priority/normal, status/LGTM2, type/enhancement

#188 syncer: support case insensitive binlog event in filter
  go.mod
  go.sum
  syncer/syncer_test.go
Labels: priority/normal, status/LGTM2, type/enhancement

#183 *: refine task.yaml sample file
  dm/dm-ansible/conf/task.yaml.example
  dm/master/task.yaml
Labels: priority/normal, status/LGTM2, type/doc

#171 relay: use new `Reader`, `Transformer` and `Writer`
  dm/worker/relay_test.go
  dm/worker/server_test.go
  pkg/binlog/reader/tcp_test.go
  pkg/streamer/reader.go
  pkg/utils/util.go
  pkg/utils/util_test.go
  relay/meta_test.go
  relay/reader/error.go
  relay/reader/error_test.go
  relay/reader/reader.go
  relay/reader/reader_test.go
  relay/relay.go
  relay/relay_test.go
  relay/transformer/transformer.go
  relay/transformer/transformer_test.go
  relay/util.go
  relay/util_test.go
  relay/writer/file.go
  relay/writer/file_test.go
  relay/writer/writer.go
Labels: priority/important, status/LGTM2, type/enhancement

#189 *: some static check fix
  dm/config/subtask_test.go
  dm/master/server.go
  dm/tracer/server.go
  dm/worker/config_test.go
  dm/worker/log_test.go
  dm/worker/meta_test.go
  loader/loader.go
  pkg/binlog/reader/file_test.go
  pkg/binlog/reader/tcp_test.go
  pkg/encrypt/encrypt.go
  pkg/streamer/file_test.go
  pkg/streamer/streamer_test.go
  pkg/tracing/tracer_test.go
  relay/metrics.go
  relay/writer/file_test.go
  relay/writer/file_util.go
  syncer/ddl_exec_info.go
  syncer/ddl_exec_info_test.go
  syncer/dml.go
  syncer/util.go
Labels: priority/unimportant, status/PTAL, type/enhancement

#187 *: add an upgrade mechanism and fix task meta encoding
  dm/worker/log.go
  dm/worker/log_test.go
  dm/worker/meta_test.go
  dm/worker/upgrade.go
  dm/worker/upgrade_test.go
  dm/worker/worker.go
  go.mod
  go.sum
Labels: priority/important, status/LGTM2, type/bug-fix, type/feature
