Repository pingcap/dm, pull requests merged in 2019-04, with the labels that each got.

#98 config: verify subtask config when generating from task
  dm/config/task.go
  dm/master/server.go
Labels: priority/normal, qa, status/LGTM2, type/bug-fix

#96 syncer: add metrics for sharding merge
  dm/dm-ansible/scripts/dm.json
  syncer/metrics.go
  syncer/syncer.go
Labels: priority/normal, status/LGTM2, type/feature

#99 *: change `max_allowed_packet` to 64MB
  dm/config/subtask.go
  dm/config/subtask_test.go
  dm/worker/config.go
  loader/checkpoint_test.go
  loader/db.go
  syncer/db.go
  syncer/syncer_test.go
Labels: priority/normal, status/LGTM2, type/enhancement

#100 *: add a `.name` suffix to avoid data overwrite between tasks
  dm/config/subtask.go
  dm/master/task.yaml
  loader/loader.go
Labels: priority/normal, status/LGTM2, type/enhancement

#106 tests: update test entry in Makefile
  Makefile
  README.md
Labels: priority/unimportant, qa, status/LGTM2, type/test

#102 *: slice capacity prealloc tuning
  dm/worker/subtask.go
  syncer/ddl.go
  syncer/dml.go
Labels: priority/normal, status/LGTM2, type/enhancement

#104 *: remove some unnecessary type conversion
  dm/ctl/master/migrate_relay.go
  dm/worker/config.go
  dm/worker/server.go
  pkg/binlog/event/dml.go
  pkg/binlog/event/util.go
  pkg/encrypt/encrypt.go
  pkg/streamer/reader.go
  pkg/streamer/utils_test.go
Labels: priority/unimportant, status/LGTM2, type/enhancement

#107 syncer/dml.go: Refine error msg
  syncer/dml.go
Labels: status/LGTM2, type/enhancement

#103 tests: add retry in metric check, make it more robust
  tests/README.md
  tests/_utils/check_metric
  tests/all_mode/run.sh
Labels: priority/unimportant, qa, status/LGTM2, type/test

#111 mydumper: fix data race in stdout pipe
  mydumper/mydumper.go
Labels: priority/normal, status/LGTM2, type/bug-fix

#101 *: refine dashboard
  dm/dm-ansible/scripts/dm.json
  dm/dm-ansible/scripts/dm_instances.json
  dm/dm-ansible/scripts/import_grafana_dashboards.py
Labels: priority/normal, should update docs, status/LGTM2, type/enhancement

#115 *: fix adjusting sub task config when starting task from the meta
  dm/config/subtask.go
  dm/config/task.go
  dm/worker/meta.go
  dm/worker/meta_test.go
Labels: priority/normal, status/LGTM2, type/bug-fix

#113 syncer: remove useless code in checkpoint
  syncer/checkpoint.go
  syncer/meta.go
Labels: priority/normal, status/LGTM2, type/enhancement

#120 dashboard: change dashboard name
  dm/dm-ansible/scripts/dm.json
  dm/dm-ansible/scripts/dm_instances.json
Labels: priority/normal, status/LGTM2, type/compatibility

#112 tests: add incremental mode test
  tests/all_mode/run.sh
  tests/dmctl_tools/dmctl_operate_task.go
  tests/dmctl_tools/dmctl_start_task.go
  tests/incremental_mode/conf/diff_config.toml
  tests/incremental_mode/conf/dm-master.toml
  tests/incremental_mode/conf/dm-task.yaml
  tests/incremental_mode/conf/dm-worker1.toml
  tests/incremental_mode/conf/dm-worker2.toml
  tests/incremental_mode/data/db1.increment.sql
  tests/incremental_mode/data/db1.prepare.sql
  tests/incremental_mode/data/db2.increment.sql
  tests/incremental_mode/data/db2.prepare.sql
  tests/incremental_mode/run.sh
  tests/online_ddl/dmctl.go
  tests/online_ddl/run.sh
  tests/run.sh
  tests/safe_mode/run.sh
  tests/sharding/dmctl.go
  tests/sharding/run.sh
  tests/utils/dmctl.go
Labels: priority/normal, qa, status/LGTM2, type/test

#114 tests: fix random fail in decrypt unit test
  pkg/encrypt/encrypt_test.go
Labels: priority/normal, qa, status/LGTM2, type/test

#118 tests: add load unit interruption test
  loader/loader.go
  syncer/mode.go
  syncer/syncer.go
  tests/_utils/run_dm_master
  tests/_utils/run_dm_tracer
  tests/_utils/run_dm_worker
  tests/load_interrupt/conf/diff_config.toml
  tests/load_interrupt/conf/dm-master.toml
  tests/load_interrupt/conf/dm-task.yaml
  tests/load_interrupt/conf/dm-worker1.toml
  tests/load_interrupt/conf/dm-worker2.toml
  tests/load_interrupt/run.sh
Labels: priority/normal, qa, status/LGTM2, type/test

#119 tracer: fix data race, start tracer before task restore
  dm/worker/worker.go
  pkg/tracing/tracer.go
  tests/README.md
  tests/_utils/test_prepare
  tests/all_mode/conf/dm-task.yaml
  tests/online_ddl/conf/dm-task.yaml
  tests/safe_mode/run.sh
  tests/sharding/conf/dm-task.yaml
Labels: priority/normal, qa, status/LGTM2, type/enhancement

#108 *: add `Reader`, `Transformer` for relay log
  pkg/binlog/event/event.go
  pkg/binlog/event/event_test.go
  pkg/binlog/reader/file.go
  pkg/binlog/reader/file_test.go
  pkg/binlog/reader/mock.go
  pkg/binlog/reader/mock_test.go
  pkg/binlog/reader/reader.go
  pkg/binlog/reader/tcp.go
  pkg/binlog/reader/tcp_test.go
  relay/reader/error.go
  relay/reader/error_test.go
  relay/reader/reader.go
  relay/reader/reader_test.go
  relay/reader/stage.go
  relay/transformer/transformer.go
  relay/transformer/transformer_test.go
  relay/transformer/util.go
  relay/transformer/util_test.go
Labels: priority/important, status/LGTM2, type/enhancement

#122 *: upgrade failpoint dep
  Makefile
  go.mod
  go.sum
Labels: priority/normal, status/LGTM2, type/enhancement

#124 syncer: fix checkpoint update when multi sharding group exists
  syncer/sharding_group.go
  syncer/sharding_group_test.go
Labels: priority/important, qa, status/LGTM2, type/bug-fix

#123 syncer: refine drop schema in sharding
  syncer/ddl.go
  tests/sharding/conf/diff_config.toml
  tests/sharding/conf/dm-task.yaml
  tests/sharding/data/db1.increment.sql
  tests/sharding/data/db1.increment2.sql
  tests/sharding/data/db1.increment3.sql
  tests/sharding/data/db1.prepare.sql
  tests/sharding/data/db2.increment.sql
  tests/sharding/data/db2.increment2.sql
  tests/sharding/data/db2.increment3.sql
  tests/sharding/data/db2.prepare.sql
  tests/sharding/run.sh
Labels: priority/normal, status/LGTM2, type/enhancement

#128 Add unsafe_cleanup.yml for dm ansible
  dm/dm-ansible/unsafe_cleanup.yml
Labels: priority/normal, status/LGTM2, type/feature

#126 tests: re-enable checkpoint unit test
  go.mod
  go.sum
  pkg/log/log.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/README.md
Labels: priority/normal, qa, status/LGTM2, type/test

#127 tests: add process unit periodic status test
  loader/loader.go
  loader/status.go
  syncer/syncer.go
  tests/README.md
  tests/_utils/check_rpc_alive
  tests/_utils/test_prepare
  tests/dmctl_tools/check_master_online.go
  tests/dmctl_tools/check_worker_online.go
  tests/incremental_mode/run.sh
  tests/load_interrupt/run.sh
  tests/online_ddl/run.sh
  tests/print_status/conf/diff_config.toml
  tests/print_status/conf/dm-master.toml
  tests/print_status/conf/dm-task.yaml
  tests/print_status/conf/dm-worker1.toml
  tests/print_status/data/db.increment.sql
  tests/print_status/data/db.prepare.sql
  tests/print_status/run.sh
  tests/run.sh
  tests/safe_mode/run.sh
  tests/sharding/run.sh
Labels: priority/normal, qa, status/LGTM2
