Repository pingcap/dm, pull requests merged in 2019-03, with the labels that each got.

#63 *: fileSizeUpdated return value minor fix
  pkg/streamer/utils.go
Labels: priority/normal, status/LGTM2, type/enhancement

#60 syncer: fix generated column in where condition
  syncer/dml.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/_utils/run_dm_worker
  tests/all_mode/data/db1.increment.sql
Labels: priority/normal, status/LGTM2, type/bug-fix

#66 poor: resume task if sync unit exits with `invalid connection` error
  dm/worker/subtask.go
Labels: status/LGTM2, type/enhancement

#65 checker: allow to ignore some checking items
  checker/check_test.go
  checker/checker.go
  checker/cmd.go
  dm/config/checking_item.go
  dm/config/checking_item_test.go
  dm/config/subtask.go
  dm/config/task.go
  go.mod
  go.sum
Labels: priority/normal, status/LGTM2, type/enhancement

#68 *: update links to docs
  .github/ISSUE_TEMPLATE/question.md
  README.md
Labels: priority/normal, status/LGTM2, type/doc

#54 use restore feature to refine codes releated ddl
  dm/ctl/common/util.go
  go.mod
  go.sum
  loader/convert_data.go
  pkg/parser/commen_test.go
  pkg/parser/common.go
  relay/util.go
  syncer/ast.go
  syncer/ast_test.go
  syncer/ddl.go
  syncer/ddl_test.go
  syncer/filter.go
  syncer/inject_sql.go
  syncer/online_ddl.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: status/LGTM2, type/enhancement

#71 *: upgrade build go version, add more build direction
  Makefile
  README.md
  go.sum
  tests/README.md
  tests/wait_for_mysql.sh
Labels: priority/normal, status/LGTM2, type/enhancement

#75 *: replace golang.org/x/net/context with standard context
  checker/checker.go
  checker/cmd.go
  dm/ctl/master/break_ddl_lock.go
  dm/ctl/master/check_task.go
  dm/ctl/master/migrate_relay.go
  dm/ctl/master/operate_relay.go
  dm/ctl/master/operate_task.go
  dm/ctl/master/purge_relay.go
  dm/ctl/master/query_error.go
  dm/ctl/master/query_status.go
  dm/ctl/master/refresh_worker_tasks.go
  dm/ctl/master/show_ddl_locks.go
  dm/ctl/master/sql_replace.go
  dm/ctl/master/sql_skip.go
  dm/ctl/master/start_task.go
  dm/ctl/master/unlock_ddl_lock.go
  dm/ctl/master/update_masterconfig.go
  dm/ctl/master/update_relay.go
  dm/ctl/master/update_task.go
  dm/ctl/worker/break_ddl_lock.go
  dm/ctl/worker/operate_relay.go
  dm/ctl/worker/operate_sub_task.go
  dm/ctl/worker/query_error.go
  dm/ctl/worker/query_status.go
  dm/ctl/worker/start_sub_task.go
  dm/ctl/worker/switch_relay_master.go
  dm/ctl/worker/update_sub_task.go
  dm/master/server.go
  dm/unit/unit.go
  dm/worker/server.go
  dm/worker/subtask.go
  dm/worker/worker.go
  go.mod
  loader/loader.go
  loader/status.go
  mydumper/mydumper.go
  pkg/streamer/reader.go
  relay/relay.go
  syncer/ddl_exec_info.go
  syncer/heartbeat.go
  syncer/inject_sql.go
  syncer/metrics.go
  syncer/mode.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: priority/unimportant, status/LGTM2, type/enhancement

#74 loader: add db retry in checkpoint operation
  loader/checkpoint.go
  loader/db.go
  loader/loader.go
Labels: priority/normal, status/LGTM2, type/enhancement

#76 *: fix go vet test in CI
  Makefile
Labels: priority/unimportant, status/LGTM2, type/bug-fix

#78 *: fix go vet test
  Makefile
Labels: priority/unimportant, status/LGTM2, type/bug-fix

#81 test: fix vet test in CI
  Makefile
  go.mod
  go.sum
Labels: priority/unimportant, status/LGTM2, type/bug-fix

#79 test: add parameter to run single integration_test
  Makefile
  tests/README.md
  tests/run.sh
Labels: priority/unimportant, status/LGTM2, status/PTAL, type/enhancement

#80 *: request the MariaDB master to send Annotate_rows_log_event back
  relay/relay.go
Labels: priority/normal, qa, status/LGTM2, type/bug-fix

#82 loader:/ avoid indent, and confusing causeErr
  loader/db.go
  loader/loader.go
Labels: priority/unimportant, status/LGTM2, type/enhancement

#37 *: support generate MySQL/MariaDB binlog events for testing
  dm/master/config.go
  dm/worker/config.go
  pkg/binlog/event/common.go
  pkg/binlog/event/common_test.go
  pkg/binlog/event/ddl.go
  pkg/binlog/event/ddl_test.go
  pkg/binlog/event/default_arg.go
  pkg/binlog/event/dml.go
  pkg/binlog/event/dml_test.go
  pkg/binlog/event/event.go
  pkg/binlog/event/event_test.go
  pkg/binlog/event/generator.go
  pkg/binlog/event/generator_test.go
  pkg/binlog/event/sid_mysql.go
  pkg/binlog/event/sid_mysql_test.go
  pkg/binlog/event/util.go
  syncer/syncer_test.go
  tests/README.md
Labels: priority/normal, qa, status/LGTM2, type/feature

#84 test: add online ddl test in integration test
  syncer/ghost.go
  syncer/online_ddl.go
  syncer/pt_osc.go
  tests/README.md
  tests/_utils/run_sql_file
  tests/_utils/run_sql_file_online_ddl
  tests/_utils/test_prepare
  tests/all_mode/run.sh
  tests/online_ddl/conf/diff_config.toml
  tests/online_ddl/conf/dm-master.toml
  tests/online_ddl/conf/dm-task.yaml
  tests/online_ddl/conf/dm-worker1.toml
  tests/online_ddl/conf/dm-worker2.toml
  tests/online_ddl/data/db1.increment.sql
  tests/online_ddl/data/db1.prepare.sql
  tests/online_ddl/data/db2.increment.sql
  tests/online_ddl/data/db2.prepare.sql
  tests/online_ddl/dmctl.go
  tests/online_ddl/run.sh
  tests/sharding/run.sh
Labels: priority/normal, qa, status/LGTM2, type/test

#58 *: add basic tracing framework
  Makefile
  cmd/dm-tracer/main.go
  dm/master/server.go
  dm/master/status.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmworker.pb.go
  dm/pb/tracer.pb.go
  dm/pb/tracer_base.pb.go
  dm/pb/tracer_syncer.pb.go
  dm/proto/dmworker.proto
  dm/proto/tracer.proto
  dm/proto/tracer_base.proto
  dm/proto/tracer_syncer.proto
  dm/tracer/README.md
  dm/tracer/config.go
  dm/tracer/http_handler.go
  dm/tracer/http_handler_test.go
  dm/tracer/http_status.go
  dm/tracer/server.go
  dm/tracer/store.go
  dm/worker/config.go
  dm/worker/metrics.go
  dm/worker/worker.go
  pkg/tracing/config.go
  pkg/tracing/event.go
  pkg/tracing/hub.go
  pkg/tracing/tracer.go
  pkg/tracing/tracer_syncer.go
  pkg/tracing/tracer_test.go
  pkg/tracing/utils.go
  pkg/tracing/utils_test.go
  syncer/job.go
  syncer/syncer.go
Labels: priority/important, qa, status/LGTM2, type/feature

#73 *: release resources acquired when Init fail in the half-way
  checker/checker.go
  dm/unit/unit.go
  loader/loader.go
  pkg/func-rollback/rollback.go
  pkg/func-rollback/rollback_test.go
  relay/relay.go
  syncer/syncer.go
Labels: priority/normal, qa, status/LGTM2, type/bug-fix

#59 fix typo
  loader/loader.go
  loader/status.go
Labels: status/LGTM2

#89 loader: fix load progress
  loader/loader.go
Labels: priority/normal, qa, status/LGTM2, type/bug-fix

#90 tracer: remove remaining imports of golang.org/x/net/context
  dm/tracer/server.go
  pkg/tracing/tracer.go
  pkg/tracing/tracer_test.go
Labels: priority/unimportant, status/LGTM2, type/enhancement

#93 mydumper: pipe mydumper log into dm-worker.log
  mydumper/mydumper.go
Labels: priority/normal, status/LGTM2, type/feature

#92 relay: use Reader interface read binlog events
  pkg/binlog/reader/reader.go
  pkg/binlog/reader/tcp.go
  pkg/binlog/reader/tcp_test.go
  relay/relay.go
Labels: priority/normal, status/LGTM2, type/enhancement

#95 syncer: fix the error message about executing multiple DDLs
  syncer/sharding_group.go
Labels: priority/normal, status/LGTM2, type/bug-fix
