Repository pingcap/dm, pull requests merged in 2019-02, with the labels that each got.

#40 README: fix dead links
  README.md
Labels: priority/unimportant, status/LGTM2, type/doc

#38 test: fix Incorrect datetime value error in unit test
  syncer/syncer_test.go
Labels: priority/normal, qa, status/LGTM2, type/bug-fix

#42 *: support generated column in loader and binlog replication
  loader/convert_data.go
  loader/convert_data_test.go
  loader/dumpfile/test1.t3-schema.sql
  syncer/ast.go
  syncer/db.go
  syncer/ddl_test.go
  syncer/dml.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/all_mode/data/db1.increment.sql
  tests/all_mode/data/db1.prepare.sql
  tests/sharding/data/db1.increment.sql
  tests/sharding/data/db1.prepare.sql
  tests/sharding/data/db2.increment.sql
  tests/sharding/data/db2.prepare.sql
Labels: priority/normal, qa, status/LGTM2, type/bug-fix

#53 *: fix some race condition
  dm/master/server.go
  dm/worker/server.go
  relay/purger/purger.go
  syncer/syncer.go
Labels: priority/normal, status/LGTM2, type/bug-fix

#55 *: fix build status badge
  README.md
Labels: priority/unimportant, status/LGTM1

#50 *: DM server graceful exit in integration test
  cmd/dm-master/main_test.go
  cmd/dm-worker/main_test.go
  tests/README.md
  tests/_utils/wait_process_exit
  tests/all_mode/run.sh
  tests/sharding/run.sh
Labels: priority/normal, status/LGTM2, type/enhancement

#57 syncer: do not skip all queries begin with '#'
  syncer/ddl_test.go
  syncer/filter.go
  syncer/filter_test.go
Labels: priority/normal, status/LGTM2, type/bug-fix

#61 syncer: take the first 2 fields of show binary logs
  syncer/db.go
Labels: status/LGTM2, type/bug-fix
