Repository pingcap/dm, pull requests merged in 2019-09, with the labels that each got.

#264 dm-worker: fix lock acquire starvation
  dm/worker/worker.go
Labels: priority/normal, release-blocker, status/LGTM2, type/bug-fix

#262 test: add compatibility test
  Makefile
  tests/README.md
  tests/_utils/run_dm_master
  tests/_utils/run_dm_worker
  tests/compatibility/conf/diff_config.toml
  tests/compatibility/conf/dm-master.toml
  tests/compatibility/conf/dm-task.yaml
  tests/compatibility/conf/dm-worker1.toml
  tests/compatibility/conf/dm-worker2.toml
  tests/compatibility/data/db1.increment.1.sql
  tests/compatibility/data/db1.increment.2.sql
  tests/compatibility/data/db1.increment.3.sql
  tests/compatibility/data/db1.prepare.sql
  tests/compatibility/data/db2.increment.1.sql
  tests/compatibility/data/db2.increment.2.sql
  tests/compatibility/data/db2.increment.3.sql
  tests/compatibility/data/db2.prepare.sql
  tests/compatibility/start.sh
  tests/compatibility_run.sh
  tests/run.sh
Labels: priority/normal, qa, release-blocker, status/LGTM2

#265 relay: retry for upstream bad connection
  dm/worker/relay.go
  dm/worker/server_test.go
  go.mod
  go.sum
  pkg/parser/common_test.go
  relay/config.go
  relay/relay.go
  relay/relay_test.go
  relay/retry/reader.go
  relay/retry/reader_test.go
  relay/transformer/transformer.go
Labels: priority/important, release-blocker, status/LGTM2, type/bug-fix

#263 *: upgrade grpc to v1.23.0
  dm/master/server.go
  dm/tracer/server.go
  dm/worker/server.go
  go.mod
  go.sum
  pkg/tracing/tracer_test.go
Labels: priority/normal, release-blocker, status/LGTM1, type/enhancement

#267 DM-worker: update blacklist of auto resumable error
  dm/worker/task_checker.go
  dm/worker/task_checker_test.go
Labels: priority/normal, status/LGTM2, type/enhancement

#268 test: add integration test for task auto recover
  dm/worker/task_checker.go
  tests/_utils/check_log_contains
  tests/_utils/run_tidb_server
  tests/all_mode/run.sh
  tests/run.sh
Labels: priority/unimportant, qa, status/LGTM2, type/test

#269 loader: fix data values lost in error message
  loader/convert_data.go
  loader/convert_data_test.go
Labels: priority/unimportant, status/LGTM2, type/bug-fix

#270 *: fix some misspell
  dm/worker/log.go
  dm/worker/meta_test.go
  loader/convert_data.go
  pkg/streamer/reader.go
  relay/metrics.go
  syncer/sharding-meta/shardmeta.go
  syncer/sharding_group.go
  syncer/syncer.go
Labels: priority/unimportant, status/LGTM2, type/enhancement

#271 Changelog: Add DM 1.0 GA
  CHANGELOG.md
Labels: priority/normal, status/LGTM2, type/CHANGELOG

#272 ansible: release v1.0.0
  dm/dm-ansible/inventory.ini
Labels: priority/normal, status/LGTM2, type/dm-ansible

#273 Add 1.0 GA action required in CHANGELOG
  CHANGELOG.md
Labels: needs-cherry-pick-1.0, priority/normal, status/LGTM2, type/CHANGELOG

#274 dm-worker: fix panic in query status
  dm/worker/status.go
Labels: needs-cherry-pick-1.0, priority/normal, status/LGTM2, type/bug-fix

#275 dm-worker: fix panic in query status (#274)
  dm/worker/status.go
Labels: release-note, status/LGTM2, type/cherry-pick

#276 checker: keep the original database error in the error message
  checker/checker.go
Labels: needs-cherry-pick-1.0, priority/normal, status/LGTM2, type/enhancement

#277 CHANGELOG: Add action required (#273)
  CHANGELOG.md
Labels: status/LGTM2, type/CHANGELOG, type/cherry-pick

#278 checker: keep the original database error in the error message (#276)
  checker/checker.go
Labels: priority/normal, status/LGTM1, type/cherry-pick, type/enhancement

#279 ansible: release v1.0.1
  dm/dm-ansible/inventory.ini
Labels: priority/normal, status/LGTM2, type/dm-ansible

#280 conn: add max idle conn config
  loader/db.go
  pkg/baseconn/conn.go
  pkg/baseconn/conn_test.go
  syncer/checkpoint_test.go
  syncer/db.go
  syncer/syncer_test.go
Labels: needs-cherry-pick-1.0, priority/important, release-note, status/LGTM2, type/enhancement

#281 conn: add max idle conn config (#280)
  loader/db.go
  pkg/baseconn/conn.go
  pkg/baseconn/conn_test.go
  syncer/checkpoint_test.go
  syncer/db.go
  syncer/syncer_test.go
Labels: priority/important, release-note, status/LGTM2, type/cherry-pick

#284 Changelog: Add 1.0.1
  CHANGELOG.md
Labels: needs-cherry-pick-1.0, priority/normal, status/LGTM2, type/CHANGELOG

#291 *: refine dmctl output for `DM-master`, `task-name` and `config-file`
  dm/ctl/master/check_task.go
  dm/ctl/master/pause_task.go
  dm/ctl/master/query_error.go
  dm/ctl/master/query_status.go
  dm/ctl/master/resume_task.go
  dm/ctl/master/show_ddl_locks.go
  dm/ctl/master/sql_inject.go
  dm/ctl/master/start_task.go
  dm/ctl/master/stop_task.go
  dm/ctl/master/update_masterconfig.go
  dm/ctl/master/update_relay.go
  dm/ctl/master/update_task.go
  tests/dmctl_advance/check_list/query_error.sh
  tests/dmctl_basic/check_list/check_task.sh
  tests/dmctl_basic/check_list/pause_task.sh
  tests/dmctl_basic/check_list/query_status.sh
  tests/dmctl_basic/check_list/resume_task.sh
  tests/dmctl_basic/check_list/show_ddl_locks.sh
  tests/dmctl_basic/check_list/start_task.sh
  tests/dmctl_basic/check_list/stop_task.sh
  tests/dmctl_basic/check_list/update_master_config.sh
  tests/dmctl_basic/check_list/update_relay.sh
  tests/dmctl_basic/check_list/update_task.sh
Labels: priority/unimportant, should-cherry-pick-1.0, status/LGT1, type/enhancement

#286 syncer: fix in-memory tps count
  syncer/syncer.go
  syncer/syncer_test.go
Labels: priority/unimportant, should-cherry-pick-1.0, status/LGT2, type/enhancement

#294 syncer: fix in-memory tps count (#286)
  syncer/syncer.go
  syncer/syncer_test.go
Labels: status/LGT2, type/cherry-pick

#289 dm-worker: split DDL sync from sync function
  syncer/syncer.go
Labels: priority/unimportant, should-cherry-pick-1.0, status/LGT2, type/enhancement

#295 cherry-pick: split DDL sync from sync function
  syncer/syncer.go
Labels: status/LGT2, type/cherry-pick

#292 *: refine dmctl output for `DM-master`, `task-name` and `config-file` (#291)
  dm/ctl/master/check_task.go
  dm/ctl/master/pause_task.go
  dm/ctl/master/query_error.go
  dm/ctl/master/query_status.go
  dm/ctl/master/resume_task.go
  dm/ctl/master/show_ddl_locks.go
  dm/ctl/master/sql_inject.go
  dm/ctl/master/start_task.go
  dm/ctl/master/stop_task.go
  dm/ctl/master/update_masterconfig.go
  dm/ctl/master/update_relay.go
  dm/ctl/master/update_task.go
  tests/dmctl_advance/check_list/query_error.sh
  tests/dmctl_basic/check_list/check_task.sh
  tests/dmctl_basic/check_list/pause_task.sh
  tests/dmctl_basic/check_list/query_status.sh
  tests/dmctl_basic/check_list/resume_task.sh
  tests/dmctl_basic/check_list/show_ddl_locks.sh
  tests/dmctl_basic/check_list/start_task.sh
  tests/dmctl_basic/check_list/stop_task.sh
  tests/dmctl_basic/check_list/update_master_config.sh
  tests/dmctl_basic/check_list/update_relay.sh
  tests/dmctl_basic/check_list/update_task.sh
Labels: priority/unimportant, status/LGT2, type/cherry-pick, type/enhancement

#288 pkg: update error level and class name
  _utils/terror_gen/errors_release.txt
  pkg/terror/error_list.go
  pkg/terror/terror.go
Labels: priority/unimportant, should-cherry-pick-1.0, status/LGT2, type/enhancement

#300 pkg: update error level and class name (#288)
  _utils/terror_gen/errors_release.txt
  pkg/terror/error_list.go
  pkg/terror/terror.go
Labels: status/LGT2, type/cherry-pick

#298 *: fix server startup panic
  _utils/terror_gen/errors_release.txt
  dm/master/server.go
  dm/master/server_test.go
  dm/worker/server.go
  dm/worker/server_test.go
  pkg/terror/error_list.go
Labels: priority/normal, should-cherry-pick-1.0, status/LGT2, type/bug-fix

#296 dmctl: refine commands' usage text
  dm/ctl/ctl.go
  dm/ctl/master/break_ddl_lock.go
  dm/ctl/master/check_task.go
  dm/ctl/master/migrate_relay.go
  dm/ctl/master/pause_relay.go
  dm/ctl/master/pause_task.go
  dm/ctl/master/purge_relay.go
  dm/ctl/master/query_error.go
  dm/ctl/master/query_status.go
  dm/ctl/master/resume_relay.go
  dm/ctl/master/resume_task.go
  dm/ctl/master/sql_inject.go
  dm/ctl/master/sql_replace.go
  dm/ctl/master/sql_skip.go
  dm/ctl/master/start_task.go
  dm/ctl/master/stop_task.go
  dm/ctl/master/switch_relay_master.go
  dm/ctl/master/unlock_ddl_lock.go
  dm/ctl/master/update_masterconfig.go
  dm/ctl/master/update_relay.go
  dm/ctl/master/update_task.go
  tests/dmctl_advance/check_list/break_ddl_lock.sh
  tests/dmctl_advance/check_list/switch_relay_master.sh
  tests/dmctl_basic/check_list/pause_relay.sh
  tests/dmctl_basic/check_list/purge_relay.sh
  tests/dmctl_basic/check_list/resume_relay.sh
  tests/dmctl_basic/check_list/update_relay.sh
Labels: priority/unimportant, should-cherry-pick-1.0, status/LGT2, type/enhancement

#302 dmctl: refine commands' usage text (#296)
  dm/ctl/ctl.go
  dm/ctl/master/break_ddl_lock.go
  dm/ctl/master/check_task.go
  dm/ctl/master/migrate_relay.go
  dm/ctl/master/pause_relay.go
  dm/ctl/master/pause_task.go
  dm/ctl/master/purge_relay.go
  dm/ctl/master/query_error.go
  dm/ctl/master/query_status.go
  dm/ctl/master/resume_relay.go
  dm/ctl/master/resume_task.go
  dm/ctl/master/sql_inject.go
  dm/ctl/master/sql_replace.go
  dm/ctl/master/sql_skip.go
  dm/ctl/master/start_task.go
  dm/ctl/master/stop_task.go
  dm/ctl/master/switch_relay_master.go
  dm/ctl/master/unlock_ddl_lock.go
  dm/ctl/master/update_masterconfig.go
  dm/ctl/master/update_relay.go
  dm/ctl/master/update_task.go
  tests/dmctl_advance/check_list/break_ddl_lock.sh
  tests/dmctl_advance/check_list/switch_relay_master.sh
  tests/dmctl_basic/check_list/pause_relay.sh
  tests/dmctl_basic/check_list/purge_relay.sh
  tests/dmctl_basic/check_list/resume_relay.sh
  tests/dmctl_basic/check_list/update_relay.sh
Labels: priority/unimportant, status/LGT2, type/cherry-pick, type/enhancement

#301 *: fix server startup panic (#298)
  _utils/terror_gen/errors_release.txt
  dm/master/server.go
  dm/master/server_test.go
  dm/worker/server.go
  dm/worker/server_test.go
  pkg/terror/error_list.go
Labels: status/LGT2, type/cherry-pick
