Repository pingcap/dm, pull requests merged in 2019-08, with the labels that each got.

#209 release mysql dependence in syncer test (1)
  pkg/binlog/event/dml.go
  pkg/binlog/event/event.go
  pkg/binlog/event/event_test.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: priority/unimportant, qa, status/LGTM1, type/test

#223 *: update go.mod
  go.mod
  go.sum
  pkg/parser/common_test.go
Labels: priority/normal, status/LGTM1, type/enhancement

#206 add failpoint test for db operation
  dm/worker/subtask.go
  loader/db.go
  pkg/utils/common.go
  pkg/utils/db.go
  syncer/checkpoint.go
  tests/_utils/kill_dm_master
  tests/_utils/kill_dm_worker
  tests/_utils/test_prepare
  tests/all_mode/run.sh
  tests/dmctl_advance/run.sh
  tests/dmctl_basic/run.sh
  tests/incremental_mode/run.sh
  tests/initial_unit/conf/diff_config.toml
  tests/initial_unit/conf/dm-master.toml
  tests/initial_unit/conf/dm-task.yaml
  tests/initial_unit/conf/dm-worker1.toml
  tests/initial_unit/run.sh
  tests/load_interrupt/run.sh
  tests/online_ddl/run.sh
  tests/others_integration.txt
  tests/print_status/run.sh
  tests/relay_interrupt/conf/diff_config.toml
  tests/relay_interrupt/conf/dm-master.toml
  tests/relay_interrupt/conf/dm-task.yaml
  tests/relay_interrupt/conf/dm-worker1.toml
  tests/relay_interrupt/run.sh
  tests/safe_mode/run.sh
  tests/sequence_safe_mode/run.sh
  tests/sequence_sharding/run.sh
  tests/sharding/run.sh
  tests/start_task/conf/diff_config.toml
  tests/start_task/conf/dm-master.toml
  tests/start_task/conf/dm-task.yaml
  tests/start_task/conf/dm-worker1.toml
  tests/start_task/run.sh
Labels: priority/important, qa, status/LGTM1

#225 worker: fix panic in handle task
  dm/worker/server_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
Labels: priority/important, status/LGTM2, status/PTAL, type/bug-fix

#224 dm-master: use grpc gateway to support http request
  dm/master/server.go
  dm/master/status.go
  dm/master/status_test.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmmaster.pb.gw.go
  dm/proto/dmmaster.proto
  generate-dm.sh
  go.mod
  go.sum
  tests/_utils/check_log_contains
  tests/http_apis/conf/diff_config.toml
  tests/http_apis/conf/dm-master.toml
  tests/http_apis/conf/dm-task.yaml
  tests/http_apis/conf/dm-worker1.toml
  tests/http_apis/run.sh
  tests/others_integration.txt
Labels: priority/normal, status/LGTM2, type/feature

#232 support to do benchmark that read binlog from master in any environment
  go.sum
  relay/metrics.go
  relay/relay.go
Labels: priority/normal, status/LGTM2, type/enhancement

#237 rfc: add task auto recovery
  docs/RFCS/20190814_task_auto_recovery.md
Labels: priority/important, status/LGTM2, type/enhancement

#239 log: fix panic when InitLogger failed
  pkg/log/log.go
Labels: priority/unimportant, status/LGTM2, type/bug-fix

#240 worker: fix subtask initialized state
  dm/worker/subtask.go
  tests/initial_unit/run.sh
Labels: priority/normal, status/LGTM2, type/bug-fix

#236 dm-worker: refine db operation
  dm/config/subtask.go
  dm/config/task.go
  dm/dm-ansible/conf/task.yaml.example
  dm/master/server_test.go
  dm/master/task.yaml
  dm/worker/subtask.toml
  loader/checkpoint.go
  loader/checkpoint_test.go
  loader/db.go
  loader/loader.go
  pkg/baseconn/conn.go
  pkg/baseconn/conn_test.go
  pkg/retry/errors.go
  pkg/retry/strategy.go
  pkg/retry/strategy_test.go
  pkg/utils/db.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/db.go
  syncer/error.go
  syncer/error_test.go
  syncer/online_ddl.go
  syncer/relay.go
  syncer/sharding_group.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/all_mode/conf/dm-task.yaml
  tests/dmctl_basic/conf/dm-task.yaml
  tests/http_apis/conf/dm-task.yaml
  tests/incremental_mode/conf/dm-task.yaml
  tests/initial_unit/conf/dm-task.yaml
  tests/load_interrupt/conf/dm-task.yaml
  tests/load_interrupt/run.sh
  tests/online_ddl/conf/dm-task.yaml
  tests/print_status/conf/dm-task.yaml
  tests/relay_interrupt/conf/dm-task.yaml
  tests/safe_mode/conf/dm-task.yaml
  tests/sequence_safe_mode/conf/dm-task.yaml
  tests/sequence_sharding/conf/dm-task.yaml
  tests/sharding/conf/dm-task.yaml
  tests/start_task/conf/dm-task.yaml
Labels: feature-request, priority/important, status/LGTM3, type/feature

#226 syncer: release mysql dependencies in syncer test (2)
  syncer/db_test.go
  syncer/ddl_test.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: priority/unimportant, qa, status/LGTM2, type/test

#251 *: fix some error scope in task units
  loader/checkpoint.go
  loader/loader.go
  syncer/checkpoint.go
  syncer/syncer.go
Labels: priority/normal, release-blocker, status/LGTM2, type/enhancement

#252 syncer: ignore error may skip execute some ddls
  pkg/baseconn/conn.go
  syncer/db.go
  syncer/db_test.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: priority/normal, release-blocker, status/LGTM2, type/bug-fix

#253 *: update go.mod
  dm/worker/metrics.go
  go.mod
  go.sum
  syncer/metrics.go
Labels: priority/normal, release-blocker, status/LGTM2, status/PTAL, type/enhancement

#246 worker: add task auto recovery framework
  _utils/terror_gen/errors_release.txt
  dm/master/server.go
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/worker/config.go
  dm/worker/dm-worker.toml
  dm/worker/server_test.go
  dm/worker/subtask.go
  dm/worker/task_checker.go
  dm/worker/task_checker_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  mydumper/mydumper.go
  pkg/backoff/backoff.go
  pkg/backoff/backoff_test.go
  pkg/terror/error_list.go
  tests/initial_unit/conf/dm-worker1.toml
Labels: priority/important, release-blocker, status/LGTM2, type/feature

#254 syncer: reset db connections during resume
  dm/master/server.go
  syncer/checkpoint.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: priority/important, release-blocker, status/LGTM2, type/enhancement

#255 tests: fix sync diff config in test cases
  tests/dmctl_basic/conf/diff_config.toml
  tests/print_status/conf/diff_config.toml
  tests/sequence_sharding/conf/diff_config.toml
  tests/sharding/conf/diff_config.toml
Labels: priority/unimportant, status/LGTM2, type/enhancement

#256 pkg/retry: add some retryable error
  pkg/retry/errors.go
Labels: priority/normal, status/LGTM2, type/enhancement

#257 *: limit the error message and log length; fix query cost check
  loader/db.go
  pkg/baseconn/conn.go
  pkg/utils/common.go
  pkg/utils/string.go
  pkg/utils/string_test.go
  syncer/db.go
Labels: priority/normal, status/LGTM2, type/enhancement

#260 *: add some necessary error check
  _utils/terror_gen/errors_release.txt
  dm/worker/worker.go
  loader/loader.go
  pkg/log/log.go
  pkg/terror/error_list.go
  relay/meta.go
  syncer/sharding_group.go
  syncer/syncer.go
Labels: priority/normal, status/LGTM2, type/enhancement

#261 *: log relay ignore reason; fix nil pointer for zap field
  dm/worker/log.go
  dm/worker/upgrade.go
  dm/worker/worker_test.go
  pkg/helper/value.go
  pkg/helper/value_test.go
  pkg/log/log.go
  relay/relay.go
  relay/transformer/transformer.go
  relay/transformer/transformer_test.go
  relay/writer/file.go
  relay/writer/file_test.go
  relay/writer/writer.go
Labels: priority/unimportant, status/LGTM2, type/enhancement

#259 DM-worker: refine lock usage
  dm/worker/log.go
  dm/worker/relay.go
  dm/worker/status.go
  dm/worker/subtask.go
  dm/worker/subtask_holder.go
  dm/worker/task_checker_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
Labels: priority/normal, status/LGTM2, type/enhancement
