Repository pingcap/dm, pull requests merged in 2019-05, with the labels that each got.

#130 Fix import dashboard
  dm/dm-ansible/roles/check_config_static/tasks/main.yml
  dm/dm-ansible/start.yml
Labels: priority/normal, status/LGTM2, type/bug-fix

#133 dmctl: remove worker mode and offline mode
  dm/ctl/common/config.go
  dm/ctl/common/util.go
  dm/ctl/ctl.go
  dm/ctl/worker/break_ddl_lock.go
  dm/ctl/worker/common.go
  dm/ctl/worker/operate_relay.go
  dm/ctl/worker/operate_sub_task.go
  dm/ctl/worker/pause_relay.go
  dm/ctl/worker/pause_sub_task.go
  dm/ctl/worker/query_error.go
  dm/ctl/worker/query_status.go
  dm/ctl/worker/resume_relay.go
  dm/ctl/worker/resume_sub_task.go
  dm/ctl/worker/start_sub_task.go
  dm/ctl/worker/stop_relay.go
  dm/ctl/worker/stop_sub_task.go
  dm/ctl/worker/switch_relay_master.go
  dm/ctl/worker/update_sub_task.go
Labels: priority/unimportant, status/LGTM1, type/enhancement

#125 tests: refine process exit path in failpoint test
  cmd/dm-worker/main_test.go
  loader/loader.go
  pkg/utils/util.go
  syncer/syncer.go
Labels: priority/normal, qa, status/LGTM2

#139 test: use rpc way to check port
  tests/all_mode/run.sh
Labels: priority/normal, qa, status/LGTM2, type/test

#145 tests: add unit test coverage report
  Makefile
  README.md
Labels: priority/normal, qa, status/LGTM2, type/test

#143 tests: fix print_status check, in some case log may not flushed to disk
  tests/all_mode/run.sh
  tests/incremental_mode/run.sh
  tests/load_interrupt/run.sh
  tests/online_ddl/run.sh
  tests/print_status/conf/dm-task.yaml
  tests/print_status/run.sh
  tests/safe_mode/run.sh
  tests/sharding/run.sh
Labels: priority/normal, qa, status/LGTM1, type/test

#146 tests: add codecov config
  .codecov.yml
Labels: priority/normal, qa, status/LGTM2, type/test

#151 *: refine log of checker
  checker/checker.go
Labels: priority/normal, status/LGTM2, type/enhancement

#152 pprof: enable pprof in dm-master and dm-worker
  cmd/dm-master/main.go
  cmd/dm-tracer/main.go
  cmd/dm-worker/main.go
  dm/master/status.go
  dm/tracer/http_status.go
  dm/worker/metrics.go
Labels: priority/normal, status/LGTM2, type/enhancement

#142 *: fix update relay processing order
  dm/worker/worker.go
  pkg/binlog/reader/tcp.go
  relay/relay.go
Labels: priority/normal, status/LGTM2, type/bug-fix

#132 *: fix some golint and vet warnings, so that `make check` passes
  checker/checker.go
  dm/command/argument.go
  loader/convert_data_test.go
  loader/loader.go
  mydumper/mydumper.go
  pkg/streamer/file_test.go
  pkg/streamer/utils.go
  pkg/tracing/tracer_test.go
  relay/relay.go
  syncer/syncer.go
Labels: priority/normal, status/LGTM2, type/enhancement

#116 *: refactor subtask management and communication model
  dm/config/subtask.go
  dm/master/server.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmworker.pb.go
  dm/pb/tracer.pb.go
  dm/pb/tracer_base.pb.go
  dm/pb/tracer_syncer.pb.go
  dm/proto/dmworker.proto
  dm/worker/db.go
  dm/worker/log.go
  dm/worker/log_test.go
  dm/worker/meta.go
  dm/worker/meta_test.go
  dm/worker/server.go
  dm/worker/status.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  go.mod
  go.sum
  loader/checkpoint.go
  loader/loader.go
  syncer/syncer.go
  tests/utils/dmctl.go
Labels: priority/normal, status/LGTM2

#117 *: add `Writer` for relay log
  pkg/binlog/common/stage.go
  pkg/binlog/common/stage_test.go
  pkg/binlog/event/common.go
  pkg/binlog/event/common_test.go
  pkg/binlog/event/event.go
  pkg/binlog/event/event_test.go
  pkg/binlog/event/helper.go
  pkg/binlog/event/helper_test.go
  pkg/binlog/filename.go
  pkg/binlog/filename_test.go
  pkg/binlog/reader/file.go
  pkg/binlog/reader/file_test.go
  pkg/binlog/reader/reader.go
  pkg/binlog/reader/tcp.go
  pkg/binlog/reader/tcp_test.go
  pkg/binlog/writer/file.go
  pkg/binlog/writer/file_test.go
  pkg/binlog/writer/writer.go
  relay/common/util.go
  relay/common/util_test.go
  relay/reader/reader.go
  relay/transformer/transformer.go
  relay/writer/file.go
  relay/writer/file_test.go
  relay/writer/file_util.go
  relay/writer/file_util_test.go
  relay/writer/writer.go
Labels: priority/important, status/LGTM2, type/enhancement

#135 dmctl: use dmctl binary directly in integration test
  Makefile
  cmd/dm-ctl/main_test.go
  dm/ctl/common/operate_relay.go
  dm/ctl/common/operate_task.go
  dm/ctl/ctl.go
  dm/ctl/master/pause_relay.go
  dm/ctl/master/pause_task.go
  dm/ctl/master/resume_relay.go
  dm/ctl/master/resume_task.go
  dm/ctl/master/sql_skip.go
  dm/ctl/master/stop_relay.go
  dm/ctl/master/stop_task.go
  tests/README.md
  tests/_utils/check_sync_diff
  tests/_utils/run_dm_ctl
  tests/_utils/test_prepare
  tests/all_mode/run.sh
  tests/dmctl_advance/check_list/break_ddl_lock.sh
  tests/dmctl_advance/check_list/migrate_relay.sh
  tests/dmctl_advance/check_list/query_error.sh
  tests/dmctl_advance/check_list/refresh_worker_tasks.sh
  tests/dmctl_advance/check_list/sql_inject.sh
  tests/dmctl_advance/check_list/sql_replace.sh
  tests/dmctl_advance/check_list/sql_skip.sh
  tests/dmctl_advance/check_list/switch_relay_master.sh
  tests/dmctl_advance/check_list/unlock_ddl_lock.sh
  tests/dmctl_advance/run.sh
  tests/dmctl_basic/check_list/check_task.sh
  tests/dmctl_basic/check_list/pause_relay.sh
  tests/dmctl_basic/check_list/pause_task.sh
  tests/dmctl_basic/check_list/purge_relay.sh
  tests/dmctl_basic/check_list/query_status.sh
  tests/dmctl_basic/check_list/resume_relay.sh
  tests/dmctl_basic/check_list/resume_task.sh
  tests/dmctl_basic/check_list/show_ddl_locks.sh
  tests/dmctl_basic/check_list/start_task.sh
  tests/dmctl_basic/check_list/stop_task.sh
  tests/dmctl_basic/check_list/update_master_config.sh
  tests/dmctl_basic/check_list/update_relay.sh
  tests/dmctl_basic/check_list/update_task.sh
  tests/dmctl_basic/conf/diff_config.toml
  tests/dmctl_basic/conf/dm-master.toml
  tests/dmctl_basic/conf/dm-task.yaml
  tests/dmctl_basic/conf/dm-task2.yaml
  tests/dmctl_basic/conf/dm-worker1.toml
  tests/dmctl_basic/conf/dm-worker2.toml
  tests/dmctl_basic/data/db1.increment.sql
  tests/dmctl_basic/data/db1.increment2.sql
  tests/dmctl_basic/data/db1.prepare.sql
  tests/dmctl_basic/data/db2.increment.sql
  tests/dmctl_basic/data/db2.increment2.sql
  tests/dmctl_basic/data/db2.prepare.sql
  tests/dmctl_basic/run.sh
  tests/dmctl_tools/dmctl_operate_task.go
  tests/incremental_mode/run.sh
  tests/load_interrupt/run.sh
  tests/online_ddl/run.sh
  tests/print_status/run.sh
  tests/safe_mode/run.sh
  tests/sharding/run.sh
Labels: priority/normal, qa, status/LGTM2, type/enhancement

#158 go.mod: update most dependencies to latest versions
  go.mod
  go.sum
Labels: priority/normal, status/LGTM2, type/feature

#156 *: refactor log of dmctl
  checker/checker.go
  cmd/dm-ctl/main.go
  dm/config/subtask.go
  dm/config/task.go
  dm/ctl/ctl.go
  go.mod
  pkg/func-rollback/rollback.go
  pkg/log/log.go
  pkg/parser/common.go
  pkg/utils/common.go
  pkg/utils/printer.go
Labels: status/LGTM2

#155 worker: Extract function mkResonse to eliminate duplicate code
  dm/worker/server.go
Labels: priority/unimportant, status/LGTM2, type/enhancement

#150 syncer: add unit test
  syncer/db_test.go
  syncer/ddl_exec_info_test.go
  syncer/dml_test.go
  syncer/heartbeat.go
  syncer/heartbeat_test.go
  syncer/job.go
  syncer/job_test.go
  syncer/syncer.go
  syncer/syncer_test.go
  syncer/util.go
  syncer/util_test.go
Labels: status/LGTM2, type/test

#154 dm-worker: improve unit test
  dm/master/server.go
  dm/worker/config_test.go
  dm/worker/hub_test.go
  dm/worker/log.go
  dm/worker/log_test.go
  dm/worker/meta_test.go
  dm/worker/relay.go
  dm/worker/relay_test.go
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  loader/loader.go
  relay/purger/purger.go
  relay/relay.go
Labels: priority/normal, qa, status/LGTM2

#148 tests: dm master module add unit test
  .codecov.yml
  Makefile
  checker/cmd.go
  dm/master/config_test.go
  dm/master/server.go
  dm/master/server_test.go
  dm/master/status_test.go
  dm/pbmock/dmmaster.go
  dm/pbmock/dmworker.go
  go.mod
  go.sum
  tests/generate-mock.sh
Labels: priority/normal, qa, status/LGTM2, type/test

#163 tests: support run integration tests in parallel
  Makefile
  tests/README.md
  tests/_dmctl_tools/check_master_online.go
  tests/_dmctl_tools/check_worker_online.go
  tests/others_integration.txt
  tests/prepare_tools.sh
  tests/run.sh
Labels: priority/normal, qa, status/LGTM1, type/test
