Repository pingcap/dm, pull requests merged in 2020-02, with the labels that each got.

#461 dm-ha: fullfill worker name with advertise-addr when worker name is empty
  _utils/terror_gen/errors_release.txt
  dm/common/common.go
  dm/common/common_test.go
  dm/master/coordinator/coordinator.go
  dm/master/server.go
  dm/master/server_test.go
  dm/worker/config.go
  dm/worker/server.go
  dm/worker/server_test.go
  pkg/terror/error_list.go
Labels: priority/normal, status/LGT2

#457 relay: start with the min binlog position in checkpoint
  dm/master/coordinator/coordinator.go
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  loader/loader.go
  relay/relay.go
  syncer/checkpoint.go
  tests/_utils/run_dm_ctl_with_retry
  tests/_utils/test_prepare
  tests/ha/conf/mysql1.toml
  tests/ha/conf/mysql2.toml
  tests/ha/run.sh
Labels: priority/important, status/LGT1

#397 add dockerfile
  Dockerfile
Labels: priority/normal, should-cherry-pick-1.0, status/PTAL, type/feature

#465 syncer: don't clear online ddl if execute ddl failed(#449)
  _utils/terror_gen/errors_release.txt
  pkg/binlog/position.go
  pkg/binlog/position_test.go
  pkg/terror/error_list.go
  syncer/checkpoint.go
  syncer/db.go
  syncer/online_ddl.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/online_ddl/conf/diff_config.toml
  tests/online_ddl/conf/dm-task.yaml
Labels: priority/important, status/LGT2, type/bug-fix, type/cherry-pick

#470 syncer: fix lock in streamer controller
  dm/portal/api_test.go
  dm/worker/worker_test.go
  syncer/streamer_controller.go
Labels: priority/normal, status/LGT2, type/bug-fix

#472 syncer: fix lock in streamer controller(#470)
  dm/worker/worker_test.go
  syncer/streamer_controller.go
Labels: priority/normal, status/LGT2, type/cherry-pick

#456 shard DDL: rewrite shard DDL in pessimism mode for HA
  cmd/dm-syncer/main.go
  dm/common/common.go
  dm/master/server.go
  dm/master/server_test.go
  dm/master/shardddl/pessimist.go
  dm/master/shardddl/pessimist_test.go
  dm/master/workerrpc/interface.go
  dm/master/workerrpc/rawgrpc.go
  dm/pb/dmworker.pb.go
  dm/pbmock/dmworker.go
  dm/proto/dmworker.proto
  dm/worker/server.go
  dm/worker/status.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  dm/worker/task_checker_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  pkg/shardddl/pessimism/doc.go
  pkg/shardddl/pessimism/info.go
  pkg/shardddl/pessimism/info_test.go
  pkg/shardddl/pessimism/keeper.go
  pkg/shardddl/pessimism/keeper_test.go
  pkg/shardddl/pessimism/lock.go
  pkg/shardddl/pessimism/lock_test.go
  pkg/shardddl/pessimism/operation.go
  pkg/shardddl/pessimism/operation_test.go
  pkg/shardddl/pessimism/ops.go
  pkg/shardddl/pessimism/ops_test.go
  pkg/tracing/tracer_syncer.go
  pkg/tracing/tracer_test.go
  syncer/db_test.go
  syncer/ddl_exec_info.go
  syncer/ddl_exec_info_test.go
  syncer/ddl_test.go
  syncer/error_test.go
  syncer/job.go
  syncer/job_test.go
  syncer/shardddl/pessimist.go
  syncer/shardddl/pessimist_test.go
  syncer/status.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/all_mode/run.sh
  tests/ha/run.sh
  tests/incremental_mode/run.sh
  tests/load_interrupt/run.sh
  tests/safe_mode/conf/mysql1.toml
  tests/safe_mode/conf/mysql2.toml
  tests/safe_mode/run.sh
  tests/sequence_safe_mode/conf/mysql1.toml
  tests/sequence_safe_mode/conf/mysql2.toml
  tests/sequence_safe_mode/run.sh
  tests/sharding/run.sh
Labels: priority/normal, should-update-docs, should-update-release-note, status/LGT2, type/enhancement

#474 dm-syncer: minor fix on password && print parse error
  cmd/dm-syncer/config.go
  cmd/dm-syncer/main.go
  dm/config/subtask.go
  dm/config/subtask_test.go
  dm/config/task.go
  dm/worker/meta.go
  dm/worker/meta_test.go
Labels: priority/normal, status/LGT2, type/bug-fix

#476 dm-portal: add i18n support
  dm/portal/frontend/package.json
  dm/portal/frontend/src/App.tsx
  dm/portal/frontend/src/components/BinlogFilterModal.tsx
  dm/portal/frontend/src/components/InstancesStep.tsx
  dm/portal/frontend/src/components/Layout.tsx
  dm/portal/frontend/src/components/MigrateStep.tsx
  dm/portal/frontend/src/components/NamingStep.tsx
  dm/portal/frontend/src/components/StartStep.tsx
  dm/portal/frontend/src/components/UploadStep.tsx
  dm/portal/frontend/src/locales/en-US.ts
  dm/portal/frontend/src/locales/index.ts
  dm/portal/frontend/src/locales/zh-CN.ts
  dm/portal/frontend/yarn.lock
Labels: should-cherry-pick-1.0, status/LGT1, status/LGT2

#480 Dm portal speical week and i18n
  dm/portal/dm-fe/src/components/Layout.tsx
  dm/portal/dm-fe/src/components/NamingStep.tsx
  dm/portal/frontend/.gitignore
  dm/portal/frontend/README.md
  dm/portal/frontend/config-overrides.js
  dm/portal/frontend/package.json
  dm/portal/frontend/public/favicon.ico
  dm/portal/frontend/public/index.html
  dm/portal/frontend/public/manifest.json
  dm/portal/frontend/src/App.test.tsx
  dm/portal/frontend/src/App.tsx
  dm/portal/frontend/src/components/BinlogFilterModal.tsx
  dm/portal/frontend/src/components/InstancesStep.tsx
  dm/portal/frontend/src/components/Layout.tsx
  dm/portal/frontend/src/components/MigrateStep.tsx
  dm/portal/frontend/src/components/NamingStep.tsx
  dm/portal/frontend/src/components/StartStep.tsx
  dm/portal/frontend/src/components/UploadStep.tsx
  dm/portal/frontend/src/index.css
  dm/portal/frontend/src/index.tsx
  dm/portal/frontend/src/locales/en-US.ts
  dm/portal/frontend/src/locales/index.ts
  dm/portal/frontend/src/locales/zh-CN.ts
  dm/portal/frontend/src/logo.svg
  dm/portal/frontend/src/react-app-env.d.ts
  dm/portal/frontend/src/serviceWorker.ts
  dm/portal/frontend/src/services/api.ts
  dm/portal/frontend/src/types.ts
  dm/portal/frontend/src/utils/config-util.ts
  dm/portal/frontend/src/utils/request.ts
  dm/portal/frontend/tsconfig.json
  dm/portal/frontend/yarn.lock
Labels: status/LGT2

#477 ha: follower forward request to leader
  _utils/terror_gen/errors_release.txt
  dm/master/config.go
  dm/master/config_test.go
  dm/master/coordinator/coordinator.go
  dm/master/dm-master.toml
  dm/master/election.go
  dm/master/etcd_test.go
  dm/master/server.go
  dm/master/server_test.go
  pkg/election/election.go
  pkg/election/election_test.go
  pkg/terror/error_list.go
  tests/_utils/test_prepare
  tests/all_mode/conf/dm-master.toml
  tests/compatibility/conf/dm-master.toml
  tests/dm_syncer/conf/dm-master.toml
  tests/dmctl_basic/conf/dm-master.toml
  tests/dmctl_command/conf/dm-master.toml
  tests/full_mode/conf/dm-master.toml
  tests/ha/conf/dm-master.toml
  tests/ha/conf/dm-master1.toml
  tests/ha/conf/dm-master2.toml
  tests/ha/conf/dm-master3.toml
  tests/ha/run.sh
  tests/http_apis/conf/dm-master.toml
  tests/import_goroutine_leak/conf/dm-master.toml
  tests/incremental_mode/conf/dm-master.toml
  tests/initial_unit/conf/dm-master.toml
  tests/load_interrupt/conf/dm-master.toml
  tests/online_ddl/conf/dm-master.toml
  tests/print_status/conf/dm-master.toml
  tests/relay_interrupt/conf/dm-master.toml
  tests/retry_cancel/conf/dm-master.toml
  tests/safe_mode/conf/dm-master.toml
  tests/sequence_safe_mode/conf/dm-master.toml
  tests/sequence_sharding/conf/dm-master.toml
  tests/sharding/conf/dm-master.toml
  tests/start_task/conf/dm-master.toml
Labels: status/LGT1, type/enhancement

#484 *: export `advertise-addr` as the command arg; use `master-addr`
  dm/master/config.go
  dm/master/config_test.go
  dm/worker/config.go
  dm/worker/config_test.go
Labels: priority/normal, status/LGT2, type/feature

#483 dm-ha: refine scheduler restart logic and add UTs
  dm/config/source_config_test.go
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
  dm/master/server_test.go
  dm/worker/config.go
  dm/worker/server_test.go
  dm/worker/worker.go
  pkg/ha/bound.go
  pkg/ha/ops_test.go
  pkg/ha/source.go
  pkg/ha/source_test.go
  tests/ha_master/conf/diff_config.toml
  tests/ha_master/conf/dm-master1.toml
  tests/ha_master/conf/dm-master2.toml
  tests/ha_master/conf/dm-master3.toml
  tests/ha_master/conf/dm-master4.toml
  tests/ha_master/conf/dm-master5.toml
  tests/ha_master/conf/dm-task.yaml
  tests/ha_master/conf/dm-worker1.toml
  tests/ha_master/conf/dm-worker2.toml
  tests/ha_master/conf/source1.toml
  tests/ha_master/conf/source2.toml
  tests/ha_master/data/db1.increment.sql
  tests/ha_master/data/db1.prepare.sql
  tests/ha_master/data/db2.increment.sql
  tests/ha_master/data/db2.prepare.sql
  tests/ha_master/run.sh
  tests/incremental_mode/run.sh
  tests/online_ddl/run.sh
  tests/others_integration.txt
Labels: priority/normal, status/LGT2

#486 ha: minor fix on election's unit test
  pkg/election/election_test.go
Labels: status/LGT2

#490 .*: add more dm-ctl info in ctl operations
  _utils/terror_gen/errors_release.txt
  dm/ctl/master/query_status.go
  dm/ctl/master/query_status_test.go
  dm/master/server.go
  dm/master/server_test.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmworker.pb.go
  dm/proto/dmmaster.proto
  dm/proto/dmworker.proto
  dm/worker/server.go
  dm/worker/server_test.go
  pkg/terror/error_list.go
  pkg/utils/string.go
  tests/_utils/test_prepare
  tests/all_mode/run.sh
  tests/dm_syncer/run.sh
  tests/dmctl_basic/check_list/pause_relay.sh
  tests/dmctl_basic/check_list/pause_task.sh
  tests/dmctl_basic/check_list/resume_relay.sh
  tests/dmctl_basic/check_list/resume_task.sh
  tests/dmctl_basic/run.sh
  tests/dmctl_command/run.sh
  tests/full_mode/run.sh
  tests/ha/run.sh
  tests/ha_master/run.sh
  tests/http_apis/run.sh
  tests/import_goroutine_leak/run.sh
  tests/incremental_mode/run.sh
  tests/initial_unit/run.sh
  tests/load_interrupt/run.sh
  tests/online_ddl/run.sh
  tests/print_status/run.sh
  tests/relay_interrupt/run.sh
  tests/retry_cancel/run.sh
  tests/safe_mode/run.sh
  tests/sequence_safe_mode/run.sh
  tests/sequence_sharding/run.sh
  tests/sharding/run.sh
  tests/start_task/run.sh
Labels: priority/normal, status/LGT2, type/feature

#493 .*: refine dm tests and some logic
  dm/master/scheduler/worker_test.go
  dm/master/shardddl/info.go
  dm/master/shardddl/info_test.go
  dm/master/shardddl/pessimist.go
  dm/master/shardddl/pessimist_test.go
  dm/worker/server.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  relay/relay.go
  relay/relay_test.go
  tests/all_mode/run.sh
  tests/dm_syncer/run.sh
  tests/incremental_mode/run.sh
  tests/load_interrupt/conf/diff_config.toml
  tests/load_interrupt/conf/dm-task.yaml
  tests/load_interrupt/conf/dm-worker2.toml
  tests/load_interrupt/conf/source2.toml
  tests/load_interrupt/run.sh
Labels: priority/important, status/LGT3

#482 dm-syncer: add config for task name
  cmd/dm-syncer/config.go
  tests/_utils/run_dm_syncer
  tests/_utils/test_prepare
  tests/dm_syncer/run.sh
  tests/incremental_mode/run.sh
Labels: priority/normal, status/LGT1, type/bug-fix

#494 ha: refactor online DDL
  dm/master/shardddl/pessimist_test.go
  syncer/online_ddl.go
  tests/incremental_mode/conf/dm-task.yaml
  tests/online_ddl/conf/dm-task.yaml
  tests/online_ddl/conf/dm-worker3.toml
  tests/online_ddl/data/db1.increment2.sql
  tests/online_ddl/data/db2.increment2.sql
  tests/online_ddl/run.sh
Labels: priority/normal, status/LGT2, type/enhancement
