Repository pingcap/dm, pull requests merged in 2020-10, with the labels that each got.

#1124 config: keep compatibility after remove tracer
  dm/config/source_config.go
  dm/config/source_config_test.go
  dm/master/bootstrap.go
  dm/master/bootstrap_test.go
  pkg/upgrade/upgrade.go
Labels: needs-cherry-pick-2.0, priority/release-blocker, status/LGT1, type/bug-fix

#1046 Quality reinforcement (4): fix unstable test cases
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/syncer.go
  tests/ha_cases/run.sh
  tests/ha_master/run.sh
  tests/import_goroutine_leak/run.sh
  tests/load_interrupt/run.sh
  tests/shardddl2/run.sh
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-2.0, status/LGT2, status/WIP, type/test

#1114 *: improve chaos-mesh actions
  .github/workflows/chaos-mesh.yml
  Makefile
  chaos/cases/cases.go
  chaos/cases/conf/task-optimistic.yaml
  chaos/cases/conf/task-pessimistic.yaml
  chaos/cases/db.go
  chaos/cases/main.go
  chaos/cases/result.go
  chaos/cases/single.go
  chaos/cases/stmt.go
  chaos/cases/task.go
  chaos/manifests/Dockerfile
  chaos/manifests/cases.yaml
  chaos/manifests/io-chaos-dm.yaml
  chaos/manifests/network-emulation-dm.yaml
  chaos/manifests/network-partition-dm.yaml
  chaos/scripts/check-case.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, status/PTAL

#1115 add dumpling unit test
  dumpling/dumpling.go
  dumpling/dumpling_test.go
  dumpling/util_test.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1

#1132 dep: update dumpling
  go.mod
  go.sum
  tests/all_mode/run.sh
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2, type/dependencies

#1128 test: bring `run-compatibility-test` back
  Makefile
  tests/compatibility/data/db1.prepare.sql
  tests/compatibility/start.sh
  tests/compatibility_run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, type/test

#1134 loader: fix bug that SQL Mode didn't take effect
  loader/loader.go
  tests/all_mode/conf/dm-task.yaml
  tests/all_mode/data/db1.prepare.sql
  tests/all_mode/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, type/bug-fix

#1138 *: add version info into the integration test binaries
  Makefile
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, type/test

#1142 dumpling: properly enable EscapeBackslash with upstream SQL mode
  dumpling/dumpling.go
  tests/full_mode/data/db1.prepare.sql
  tests/full_mode/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, type/bug-fix

#1127 Quality reinforcement (5): fix unstable test cases
  dumpling/dumpling_test.go
  pkg/election/election_test.go
  tests/http_apis/run.sh
Labels: needs-cherry-pick-2.0, status/WIP, type/test

#1146 README: unify installing steps with doc
  README.md
Labels: priority/unimportant, status/LGT1, type/doc

#1141 *: make chaos-mesh tests stabler
  .github/workflows/chaos-mesh.yml
  chaos/cases/instance.go
  chaos/cases/main.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, status/PTAL, type/test

#1118 election: don't forwarding when startLeaderComponent
  dm/master/election.go
  dm/master/server.go
  dm/master/server_test.go
  pkg/atomic2/atomic.go
  pkg/atomic2/atomic_test.go
Labels: priority/normal, status/LGT1, type/bug-fix

#1156 config: check default config
  dm/config/source_config.go
  dm/config/task.go
  dm/config/task_test.go
  dumpling/dumpling_test.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2

#1161 *: update go-sqlsmith to fix invalid timestamp
  chaos/cases/instance.go
  go.mod
  go.sum
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, status/PTAL, type/test

#1164 *: support TiDB v3 error message
  pkg/retry/errors.go
  syncer/error.go
  tests/handle_error/run.sh
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2, type/bug-fix

#1162 test: complete test for alter PK
  tests/_utils/run_tidb_server
  tests/shardddl3/conf/tidb-alter-pk-config.toml
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, type/test

#1174 syncer/checkpoint: ignore cancel for update/delete
  syncer/checkpoint.go
  syncer/syncer.go
Labels: priority/important, status/LGT2, type/bug-fix

#1176 pkg/binlog: support undocumented status vars
  pkg/binlog/event/util.go
  pkg/binlog/event/util_test.go
  pkg/binlog/reader/util.go
  syncer/syncer.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2

#1139 worker: sync master's endpoint peroidcally
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/worker_test.go
  pkg/ha/keepalive.go
  pkg/utils/common.go
  pkg/utils/common_test.go
  tests/ha/conf/dm-worker1.toml
  tests/ha/conf/dm-worker2.toml
Labels: needs-cherry-pick-2.0, needs-update-release-note, priority/normal, status/LGT1, type/bug-fix

#1150 dm-syncer support route-rules
  tests/dm_syncer/conf/diff_config.toml
  tests/dm_syncer/conf/diff_config_route_rules.toml
  tests/dm_syncer/conf/dm-task.yaml
  tests/dm_syncer/data/db2.prepare.sql
  tests/dm_syncer/run.sh
Labels: first-time-contributor, status/LGT2, status/PTAL, type/test

#1145 loader: add lock for memory cached checkpoint
  loader/checkpoint.go
  loader/checkpoint_test.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, type/bug-fix

#1165 worker: create subtask for paused stage
  .github/workflows/chaos-mesh.yml
  _utils/terror_gen/errors_release.txt
  chaos/cases/task.go
  dm/worker/config.go
  dm/worker/join.go
  dm/worker/metrics.go
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  errors.toml
  pkg/terror/error_list.go
  tests/ha/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, status/PTAL, type/bug-fix

#1188 dumpling: fix default values changed when specified extra-args
  dumpling/util.go
  dumpling/util_test.go
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/LGT1, type/bug-fix

#1184 syncer: split DDL after fetching online DDL to execute
  go.mod
  go.sum
  tests/_utils/run_sql_file_online_ddl
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT1, type/bug-fix

#1195 fix: fix wrong shorthand for `statement-size`
  dumpling/util.go
  dumpling/util_test.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, type/bug-fix, type/compatibility

#1189 loader: fix nil map after clone
  loader/loader.go
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2, type/bug-fix

#1193 fix: don't forbid DM-master leader startup for unexpected DDL locks
  .github/workflows/chaos-mesh.yml
  dm/master/election.go
  dm/master/scheduler/scheduler.go
  dm/master/shardddl/optimist.go
  dm/master/shardddl/pessimist.go
  pkg/parser/common.go
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, type/bug-fix

#1200 fix: accept comands with leading and trailing white spaces
  cmd/dm-ctl/main.go
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2, type/bug-fix

#1170 Improve performence
  dm/dm-ansible/scripts/dm.json
  dm/master/server.go
  dm/master/server_test.go
  pkg/binlog/position.go
  pkg/binlog/position_test.go
  pkg/conn/baseconn.go
  pkg/dumpling/utils.go
  pkg/dumpling/utils_test.go
  pkg/metricsproxy/countervec.go
  pkg/metricsproxy/gaugevec.go
  pkg/metricsproxy/histogramvec.go
  pkg/metricsproxy/proxy.go
  pkg/metricsproxy/summaryvec.go
  pkg/schema/tracker.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/err-operator/operator.go
  syncer/err-operator/operator_test.go
  syncer/job.go
  syncer/sharding-meta/shardmeta.go
  syncer/sharding_group.go
  syncer/status.go
  syncer/streamer_controller.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2

#1201 log: fix NaN and Dpanic log
  loader/loader.go
  loader/status.go
  loader/util.go
  syncer/syncer.go
  tests/full_mode/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1

#1198 add two shard DDL test cases
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2, status/PTAL, type/test

#1209 log: fix NaN and Dpanic log #1201
  loader/loader.go
  loader/status.go
  loader/util.go
  syncer/syncer.go
  tests/full_mode/run.sh
Labels: priority/normal, status/LGT1, type/cherry-pick

#1171 *: add test cases only support in MySQL 8.0
  go.mod
  go.sum
  tests/README.md
  tests/_utils/run_sql_file_online_ddl
  tests/all_mode/run.sh
  tests/full_mode/run.sh
  tests/handle_error/lib.sh
  tests/sequence_sharding_optimistic/data/db1.prepare.sql
  tests/sequence_sharding_optimistic/data/db2.prepare.sql
  tests/shardddl3/conf/single-source-optimistic-2.yaml
  tests/shardddl3/conf/single-source-pessimistic-2.yaml
  tests/shardddl3/run.sh
  tests/sharding/run.sh
Labels: needs-cherry-pick-2.0, status/PTAL, type/test

#1210 task_checker: don't resume for binlog not found
  dm/worker/task_checker.go
  dm/worker/task_checker_test.go
  pkg/retry/errors.go
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2

#1217 fix: support HTTP and HTTPS mixture for DM-master config items
  dm/master/server_test.go
  dm/master/tls_for_test/ca.pem
  dm/master/tls_for_test/dm.key
  dm/master/tls_for_test/dm.pem
  pkg/utils/util.go
  pkg/utils/util_test.go
  tests/tls/conf/dm-master1.toml
  tests/tls/conf/dm-master2.toml
  tests/tls/conf/dm-master3.toml
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, status/PTAL, type/bug-fix

#1221 test: implement some test cases about config name
  tests/_utils/test_prepare
  tests/ha_cases/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, type/test

#1233 test: update check text to latest tidb (#1232)
  tests/import_v10x/run.sh
Labels: priority/release-blocker, type/test

#1232 test: update check text to latest tidb
  tests/import_v10x/run.sh
Labels: priority/release-blocker, status/LGT1, status/PTAL, type/test

#1153 Quality reinforcement (6): fix unstable test cases
  Makefile
  dm/master/shardddl/optimist.go
  dm/master/shardddl/pessimist_test.go
  pkg/shardddl/optimism/info_test.go
  relay/relay_test.go
  tests/_utils/test_prepare
  tests/ha_cases/run.sh
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-2.0, status/LGT2, type/test

#1235 .github: add default sig label
  .github/challenge-bot.yml
Labels: priority/unimportant, status/LGT1

#1231 dep: update dumpling to 10/28
  go.mod
  go.sum
Labels: needs-cherry-pick-2.0, status/LGT1, type/dependencies

#1237 ansible: update dm_version to v2.0.0
  dm/dm-ansible/inventory.ini
Labels: status/PTAL, type/dm-ansible

#1228 tests: upgrade DM from 1.0 and 2.0 RC to 2.0 via TiUP
  .github/workflows/upgrade-via-tiup.yml
  tests/tiup/ansible_data/hosts.ini
  tests/tiup/ansible_data/inventory.ini
  tests/tiup/conf/diff_config.toml
  tests/tiup/conf/source1.yaml
  tests/tiup/conf/source2.yaml
  tests/tiup/conf/task.yaml
  tests/tiup/conf/topo.yaml
  tests/tiup/docker/control/Dockerfile
  tests/tiup/docker/control/bashrc
  tests/tiup/docker/control/init.sh
  tests/tiup/docker/docker-compose.yml
  tests/tiup/docker/node/Dockerfile
  tests/tiup/docker/node/bashrc
  tests/tiup/docker/node/run.sh
  tests/tiup/docker/secret/.gitkeep
  tests/tiup/docker/secret/control.env
  tests/tiup/docker/secret/id_rsa
  tests/tiup/docker/secret/id_rsa.pub
  tests/tiup/docker/secret/node.env
  tests/tiup/lib.sh
  tests/tiup/upgrade-from-v1.sh
  tests/tiup/upgrade-from-v2.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/PTAL, type/test

#1239 loader: filter context cancel error in loader
  loader/loader.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1

#1215 test: add handle-error test cases
  syncer/handle_error.go
  tests/handle_error/conf/single-source-no-sharding.yaml
  tests/handle_error/lib.sh
  tests/handle_error/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, status/PTAL, type/test

#1244 CHANGELOG: add 2.0 release note
  CHANGELOG.md
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1

#1243 tests: add test case for upgrading TiDB
  .github/workflows/upgrade-via-tiup.yml
  tests/tiup/docker/.gitignore
  tests/tiup/docker/docker-compose.yml
  tests/tiup/upgrade-tidb.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, status/PTAL, type/test

#1247 test: fix unstable handle-error test case
  tests/handle_error/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1

#1252 test: relax error message for more tidb version (#1251)
  tests/all_mode/run.sh
  tests/import_v10x/run.sh
  tests/shardddl1/run.sh
Labels: priority/release-blocker, status/LGT1, type/test

#1251 test: relax error message for more tidb version
  tests/all_mode/run.sh
  tests/import_v10x/run.sh
  tests/shardddl1/run.sh
Labels: priority/release-blocker, status/LGT1, type/test
