Repository pingcap/dm, pull requests merged in 2020-11, with the labels that each got.

#1256 fix: support "sql" prefix exists in table name
  loader/loader.go
  loader/util.go
  loader/util_test.go
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, priority/normal, status/LGT2, type/bug-fix

#1257 shardddl: add infoOpLock for pessmist shardddl
  dm/master/shardddl/pessimist.go
  tests/_utils/test_prepare
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, type/bug-fix

#1267 *: update roadmap
  roadmap.md
Labels: priority/normal, status/LGT2, status/PTAL

#1265 fix: do not block in load unit for stop/pause task
  loader/loader.go
  tests/import_goroutine_leak/conf/diff_config.toml
  tests/import_goroutine_leak/conf/dm-task.yaml
  tests/import_goroutine_leak/conf/dm-worker2.toml
  tests/import_goroutine_leak/conf/source2.yaml
  tests/import_goroutine_leak/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, priority/normal, status/LGT2, type/bug-fix

#1271 schemaTracker: lazy init table info in schema tracker
  dm/worker/server.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/syncer.go
  tests/start_task/run.sh
Labels: needs-cherry-pick-2.0, status/LGT1, type/bug-fix

#1276 fix: always wait for the sender to exit in the receiver for load unit
  loader/loader.go
Labels: needs-cherry-pick-2.0, needs-update-release-note, priority/normal, status/LGT2, type/bug-fix

#1270 *: update and fix CI for release-1.0
  Makefile
  _tools/manifest.json
  _tools/src/github.com/golang/protobuf/jsonpb/encode.go
  _tools/src/github.com/golang/protobuf/proto/text_decode.go
  _tools/src/github.com/pingcap/failpoint/code/expr_rewriter.go
  _tools/src/github.com/pingcap/failpoint/failpoint-ctl/main.go
  _tools/src/github.com/sergi/go-diff/diffmatchpatch/diff.go
  _tools/src/github.com/sergi/go-diff/diffmatchpatch/patch.go
  _tools/src/golang.org/x/tools/cover/profile.go
  _tools/src/golang.org/x/tools/go/internal/gcimporter/gcimporter.go
  _tools/src/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  _tools/src/golang.org/x/tools/go/packages/golist.go
  _tools/src/golang.org/x/tools/go/packages/golist_overlay.go
  _tools/src/golang.org/x/tools/go/packages/packages.go
  _tools/src/golang.org/x/tools/internal/gocommand/invoke.go
  _tools/src/golang.org/x/tools/internal/gocommand/version.go
  _tools/src/golang.org/x/tools/internal/packagesinternal/packages.go
  _tools/src/google.golang.org/genproto/googleapis/api/annotations/annotations.pb.go
  _tools/src/google.golang.org/genproto/googleapis/api/annotations/client.pb.go
  _tools/src/google.golang.org/genproto/googleapis/api/annotations/field_behavior.pb.go
  _tools/src/google.golang.org/genproto/googleapis/api/annotations/http.pb.go
  _tools/src/google.golang.org/genproto/googleapis/api/annotations/resource.pb.go
  _tools/src/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  _tools/src/google.golang.org/protobuf/internal/encoding/messageset/messageset.go
  _tools/src/google.golang.org/protobuf/internal/encoding/text/encode.go
  _tools/src/google.golang.org/protobuf/internal/impl/codec_gen.go
  _tools/src/google.golang.org/protobuf/proto/equal.go
  _tools/src/google.golang.org/protobuf/reflect/protoregistry/registry.go
  checker/check_test.go
  checker/checker.go
  checker/cmd.go
  dm/master/server.go
  dm/master/server_test.go
  go.mod
  go.sum
  syncer/error.go
  tests/all_mode/run.sh
  tests/compatibility/conf/dm-task.yaml
  tools.json
Labels: priority/normal, status/LGT2, status/PTAL, type/dependencies

#1266 fix: support "sql" prefix exists in table name (#1256)
  loader/checkpoint.go
  loader/loader.go
Labels: priority/normal, status/LGT1, type/bug-fix, type/cherry-pick

#1287 loader: fix bug of checkpoint, cherry-pick to 1.0 (#1042)(#1145)
  loader/checkpoint.go
  loader/checkpoint_test.go
  loader/loader.go
  loader/util.go
  tests/all_mode/run.sh
Labels: status/LGT1, type/cherry-pick

#1290 errors: replace doc URL to handle-error page
  _utils/terror_gen/errors_release.txt
  errors.toml
  pkg/terror/error_list.go
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2, type/doc

#1298 utils: support OVER_MAX_DBS_IN_EVENT_MTS (254) in binlog
  pkg/binlog/event/util.go
  pkg/binlog/event/util_test.go
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2, type/bug-fix

#1296 chaos: wait coredns more time
  .github/workflows/chaos-mesh.yml
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2, status/PTAL

#1297 handle-error: only support to handle query error
  syncer/handle_error.go
  syncer/syncer.go
  tests/handle_error/run.sh
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL

#1295 syncer: do not try to handle jobs anymore if the context is done
  syncer/syncer.go
  tests/incremental_mode/run.sh
Labels: needs-cherry-pick-2.0, status/LGT1, status/PTAL, type/bug-fix

#1306 sycner: automatically use upstream sql_mode
  syncer/syncer.go
  tests/all_mode/data/db2.increment.sql
Labels: needs-cherry-pick-2.0, status/LGT1

#1305 dm monitor initializer container building
  go.mod
  go.sum
  monitoring/Dockerfile
  monitoring/dashboards/dashboard.go
  monitoring/dashboards/dm.json
  monitoring/datasources/dm-cluster-datasource.yaml
  monitoring/init.sh
  monitoring/rules/dm_worker.rules.yml
  monitoring/run.sh
Labels: first-time-contributor, status/LGT2

#1289 dep: update parser and other dependencies to latest
  go.mod
  go.sum
  pkg/binlog/reader/util.go
  pkg/parser/common.go
  pkg/parser/common_test.go
  pkg/schema/tracker.go
  relay/writer/file_util.go
  syncer/db_test.go
  syncer/err-operator/operator.go
Labels: needs-cherry-pick-2.0, status/LGT1, type/dependencies

#1309 loader: support ANSI_QUOTES when sharing rename
  loader/loader.go
  loader/util.go
  loader/util_test.go
  tests/sharding/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, priority/normal, status/LGT1, status/PTAL, type/bug-fix

#1312 check-task: precheck server-id for all/incremental mode
  checker/check_test.go
  checker/checker.go
  checker/cmd.go
  dm/config/checking_item.go
  go.mod
  go.sum
Labels: needs-cherry-pick-2.0, needs-update-docs, status/LGT2

#1272 relay: support relay log in v2.0
  _utils/terror_gen/errors_release.txt
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/worker/relay.go
  dm/worker/relay_test.go
  dm/worker/subtask.go
  errors.toml
  loader/loader.go
  loader/status.go
  pkg/binlog/event/event.go
  pkg/binlog/reader/file.go
  pkg/binlog/reader/file_test.go
  pkg/streamer/hub.go
  pkg/streamer/reader.go
  pkg/streamer/reader_test.go
  pkg/terror/error_list.go
  relay/config.go
  relay/relay.go
  relay/relay_test.go
  syncer/streamer_controller.go
  tests/handle_error/conf/source1.yaml
  tests/handle_error/conf/source2.yaml
  tests/handle_error/run.sh
  tests/shardddl1/conf/source2.yaml
  tests/shardddl2/conf/source2.yaml
  tests/shardddl3/conf/source2.yaml
Labels: needs-cherry-pick-2.0, needs-update-docs, needs-update-release-note, priority/normal, status/LGT2, status/PTAL
