Repository pingcap/dm, pull requests merged in 2020-05, with the labels that each got.

#646 test,Makefile: Add more test information in README.md
  Makefile
  tests/README.md
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, type/qa

#650 .*: remove mydumper binary config
  Makefile
  dm/config/task_test.go
  dm/dm-ansible/conf/task_advanced.yaml.example
  dm/master/server_test.go
  dm/master/task_advanced.yaml
  dm/worker/subtask.toml
  tests/README.md
  tests/_utils/run_dm_worker
  tests/all_mode/conf/dm-task.yaml
  tests/compatibility/conf/dm-task.yaml
  tests/dm_syncer/conf/dm-task.yaml
  tests/dmctl_basic/conf/dm-task.yaml
  tests/dmctl_command/conf/dm-task.yaml
  tests/full_mode/conf/dm-task.yaml
  tests/ha/conf/dm-task.yaml
  tests/ha_cases/conf/dm-task.yaml
  tests/ha_cases/conf/dm-task2.yaml
  tests/ha_cases/conf/standalone-task.yaml
  tests/ha_master/conf/dm-task.yaml
  tests/http_apis/conf/dm-task.yaml
  tests/import_goroutine_leak/conf/dm-task.yaml
  tests/incremental_mode/conf/dm-task.yaml
  tests/initial_unit/conf/dm-task.yaml
  tests/load_interrupt/conf/dm-task.yaml
  tests/online_ddl/conf/dm-task.yaml
  tests/print_status/conf/dm-task.yaml
  tests/relay_interrupt/conf/dm-task.yaml
  tests/retry_cancel/run.sh.todo
  tests/safe_mode/conf/dm-task.yaml
  tests/sequence_safe_mode/conf/dm-task.yaml
  tests/sequence_sharding/conf/dm-task.yaml
  tests/sequence_sharding_optimistic/conf/dm-task.yaml
  tests/sharding/conf/dm-task.yaml
  tests/sharding2/conf/dm-task.yaml
  tests/start_task/conf/dm-task.yaml
Labels: priority/normal, status/LGT2, type/doc

#596 Proposal: Binlog replication(syncer) unit support plugin
  docs/RFCS/20200412_syncer_plugin.md
Labels: status/LGT2, type/doc

#648 ha_test: add ha cases for P1
  dm/master/server_test.go
  tests/ha_cases/conf/dm-worker-join1.toml
  tests/ha_cases/run.sh
Labels: priority/normal, status/LGT2, type/test

#655 binlog replication: add config DisableRetrySync for binlog syncer
  pkg/binlog/common/replication.go
Labels: status/LGT2, type/bug-fix

#656 shardddl: report error for conflicts between old and new table
  pkg/shardddl/optimism/lock.go
  pkg/shardddl/optimism/lock_test.go
Labels: priority/normal, status/LGT2, type/bug-fix

#664 update tools dependency
  go.mod
  go.sum
Labels: dependencies, status/LGT2

#660 refine mydumper exits error log
  mydumper/mydumper.go
Labels: status/LGT2

#665 *: export `operate-source` as HTTP API
  dm/pb/dmmaster.pb.go
  dm/pb/dmmaster.pb.gw.go
  dm/proto/dmmaster.proto
  tests/http_apis/run.sh
Labels: priority/normal, status/LGT2

#661 refine dump unit log
  dumpling/dumpling.go
  mydumper/mydumper.go
Labels: status/LGT2

#663 update tools dependency
  go.mod
  go.sum
Labels: dependencies, status/LGT1

#668 export `offline-worker` as HTTP API
  .gitignore
  dm/ctl/master/offline_worker.go
  dm/master/server.go
  dm/master/server_test.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmmaster.pb.gw.go
  dm/proto/dmmaster.proto
  tests/http_apis/run.sh
Labels: priority/normal, status/LGT2

#654 .*: add list-member command
  dm/ctl/ctl.go
  dm/ctl/master/list_member.go
  dm/master/scheduler/scheduler.go
  dm/master/server.go
  dm/pb/dmmaster.pb.go
  dm/pbmock/dmmaster.go
  dm/proto/dmmaster.proto
  tests/_utils/get_leader
  tests/dmctl_command/run.sh
  tests/ha_master/run.sh
Labels: priority/normal, status/LGT2, type/feature

#633 feat(encrypt): Support both encrypted and unencrypted passwords for the upstream and downstream database
  cmd/dm-ctl/main.go
  dm/config/source_config.go
  dm/config/source_config_test.go
  dm/config/subtask.go
  dm/config/subtask_test.go
  dm/ctl/common/config.go
  dm/master/server.go
  dm/master/server_test.go
  dm/portal/api.go
  dm/worker/relay.go
  dm/worker/worker.go
  pkg/utils/encrypt.go
  tests/dm_syncer/conf/source1.toml
  tests/dmctl_basic/conf/source1.toml
  tests/dmctl_command/conf/source1.toml
  tests/dmctl_command/run.sh
Labels: contribution, needs-cherry-pick-1.0, needs-update-docs, needs-update-release-note, priority/normal, status/LGT2, type/feature

#675 export `list-member` as HTTP API
  dm/ctl/master/list_member.go
  dm/master/server.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmmaster.pb.gw.go
  dm/proto/dmmaster.proto
  tests/http_apis/conf/dm-master.toml
  tests/http_apis/run.sh
Labels: priority/normal, status/LGT2

#676 feat: manual cherry merge PR #633 to `release-1.0`
  cmd/dm-ctl/main.go
  dm/config/subtask.go
  dm/config/subtask_test.go
  dm/ctl/common/config.go
  dm/master/server_test.go
  dm/portal/api.go
  dm/worker/config.go
  dm/worker/config_test.go
  dm/worker/relay.go
  dm/worker/worker.go
  pkg/utils/encrypt.go
  tests/dmctl_basic/conf/dm-worker1.toml
  tests/dmctl_command/conf/dm-worker1.toml
  tests/dmctl_command/run.sh
Labels: contribution, needs-update-docs, needs-update-release-note, priority/normal, status/LGT2, type/feature

#682 update dm-portal default name
  dm/portal/frontend/src/components/NamingStep.tsx
Labels: needs-cherry-pick-1.0, priority/unimportant, status/PTAL

#683 update dm-portal default name
  dm/portal/frontend/src/components/NamingStep.tsx
Labels: priority/unimportant, status/LGT1, type/cherry-pick

#679 *: support metadata with multiple GTID sets
  dm/master/server_test.go
  loader/loader.go
  pkg/utils/mydumper.go
  pkg/utils/mydumper_test.go
  syncer/checkpoint.go
Labels: priority/normal, status/LGT2, type/bug-fix

#670 master: add an interface to evict leader
  dm/ctl/ctl.go
  dm/ctl/master/operate_leader.go
  dm/master/server.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmmaster.pb.gw.go
  dm/pbmock/dmmaster.go
  dm/proto/dmmaster.proto
  pkg/election/election.go
  pkg/election/election_test.go
  tests/dmctl_command/run.sh
  tests/ha_master/run.sh
Labels: status/LGT2, type/feature

#687 config: support setting session variable
  dm/config/subtask.go
  pkg/conn/basedb.go
  tests/_utils/check_sync_diff
  tests/all_mode/conf/dm-task.yaml
  tests/all_mode/run.sh
Labels: needs-cherry-pick-1.0, needs-update-docs, priority/normal, status/LGT2, type/feature

#669 dm-master/: add offline master operation, combine offline-worker into offline-member
  _utils/terror_gen/errors_release.txt
  dm/ctl/common/config.go
  dm/ctl/ctl.go
  dm/ctl/master/offline_member.go
  dm/ctl/master/offline_worker.go
  dm/master/server.go
  dm/master/server_test.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmmaster.pb.gw.go
  dm/pbmock/dmmaster.go
  dm/proto/dmmaster.proto
  errors.toml
  pkg/election/election.go
  pkg/election/election_test.go
  pkg/etcdutil/etcdutil.go
  pkg/terror/error_list.go
  tests/ha_master/run.sh
  tests/http_apis/run.sh
Labels: priority/normal, status/LGT2, type/feature

#692 config: support setting session variable (#687)
  dm/config/subtask.go
  pkg/conn/basedb.go
  tests/_utils/check_sync_diff
  tests/all_mode/conf/dm-task.yaml
  tests/all_mode/data/db1.prepare.sql
  tests/all_mode/run.sh
Labels: status/LGT1, type/cherry-pick
