Repository pingcap/dm, pull requests merged in 2020-06, with the labels that each got.

#696 dm-worker: move cpu metrics to worker server level
  dm/worker/metrics.go
  dm/worker/worker.go
  syncer/metrics.go
  syncer/syncer.go
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT1, type/bug-fix

#695 dm-master: resign from leader when fail to start
  dm/master/election.go
  dm/master/election_test.go
  pkg/election/election.go
Labels: priority/normal, status/LGT2

#703 fix wrong usage of failpoint in #695
  dm/master/election.go
Labels: status/LGT1, type/bug-fix

#689 gtid: fix bug that binlog name dosen't update after rotate
  syncer/syncer.go
  tests/http_apis/run.sh
  tests/incremental_mode/run.sh
Labels: status/LGT1, type/bug-fix

#713 update dumpling dependency
  dm/config/task.go
  dm/portal/api.go
  dumpling/dumpling.go
  dumpling/util.go
  dumpling/util_test.go
  go.mod
  go.sum
  mydumper/mydumper.go
  mydumper/mydumper_test.go
  tests/ha_cases/run.sh
Labels: priority/unimportant, status/LGT1, type/dependencies

#716 syncer: remove needResync
  syncer/syncer.go
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT1, type/enhancement

#724 manually cherrypick #716
  syncer/syncer.go
Labels: status/PTAL, type/cherry-pick

#712 check-task: do not show successful pre-check items if fail
  checker/checker.go
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, type/feature

#704 syncer: refine heartbeat
  syncer/heartbeat.go
  tests/README.md
  tests/_utils/check_metric
  tests/all_mode/run.sh
Labels: status/LGT2, type/bug-fix

#729 syncer: refine heartbeat (#704)
  syncer/heartbeat.go
  tests/README.md
  tests/_utils/check_metric
  tests/all_mode/run.sh
Labels: priority/normal, status/LGT2, type/bug-fix, type/cherry-pick

#730 check-task: do not show successful pre-check items if fail(#712)
  checker/checker.go
Labels: priority/normal, status/LGT2, type/cherry-pick

#725 *: fix new shard DDL handle when the previous one has not complete
  dm/master/shardddl/pessimist.go
  pkg/etcdutil/etcdutil.go
  pkg/shardddl/pessimism/info.go
  pkg/shardddl/pessimism/info_test.go
  pkg/shardddl/pessimism/operation.go
  pkg/shardddl/pessimism/operation_test.go
  syncer/shardddl/pessimist.go
  syncer/shardddl/pessimist_test.go
  syncer/syncer.go
  tests/_utils/run_sql
  tests/_utils/run_sql_file
  tests/ha_cases/run.sh
  tests/sharding/run.sh
Labels: priority/normal, status/LGT2, type/bug-fix

#732 don't resume task for `unsupported collation` error
  dm/worker/task_checker.go
  pkg/retry/errors.go
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT1, status/LGT2

#733 error_message: cherry pick #546
  dm/ctl/master/query_error.go
  dm/ctl/master/query_status.go
  dm/unit/unit.go
Labels: needs-update-release-note, priority/normal, status/LGT2, type/enhancement

#735 don't resume task for `unsupported collation` error
  dm/worker/task_checker.go
  pkg/retry/errors.go
Labels: status/LGT2, type/cherry-pick

#711 error_message: fix misleading error message for `pt` online-ddl-scheme
  _utils/terror_gen/errors_release.txt
  errors.toml
  pkg/terror/error_list.go
  syncer/pt_osc.go
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, type/bug-fix

#738 error_message: fix misleading error message for `pt` online-ddl-schem…
  _utils/terror_gen/errors_release.txt
  pkg/terror/error_list.go
  syncer/pt_osc.go
Labels: priority/normal, status/LGT2, type/cherry-pick

#722 shardddl: fix resume conflict ddl.
  dm/worker/task_checker.go
  pkg/retry/errors.go
  syncer/sharding-meta/shardmeta.go
  syncer/sharding_group.go
  tests/sequence_sharding/data/db1.increment2.sql
  tests/sequence_sharding/data/db2.increment2.sql
  tests/sequence_sharding/run.sh
  tests/sharding/run.sh
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2

#739 shardddl: fix resume conflict ddl.
  dm/worker/task_checker.go
  dm/worker/worker.go
  pkg/retry/errors.go
  syncer/sharding-meta/shardmeta.go
  syncer/sharding_group.go
  tests/sequence_sharding/data/db1.increment3.sql
  tests/sequence_sharding/data/db2.increment3.sql
  tests/sequence_sharding/run.sh
  tests/sharding/run.sh
Labels: priority/normal, status/LGT2, type/cherry-pick

#741 fix(shardddl): do not auto resume for pessimistic conflicts
  dm/worker/task_checker_test.go
  pkg/retry/errors.go
  tests/sequence_sharding/run.sh
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, type/bug-fix

#742 *: cherry pick 741; update terror codes
  .gitignore
  _utils/terror_gen/errors_release.txt
  checker/checker.go
  checker/cmd.go
  dm/worker/subtask.go
  dm/worker/task_checker_test.go
  loader/loader.go
  pkg/encrypt/encrypt.go
  pkg/retry/errors.go
  pkg/terror/error_list.go
  pkg/terror/terror.go
  syncer/relay.go
  syncer/syncer.go
  tests/_utils/run_sql
  tests/_utils/run_sql_file
  tests/all_mode/run.sh
  tests/initial_unit/run.sh
  tests/relay_interrupt/run.sh
  tests/sequence_sharding/run.sh
Labels: priority/normal, status/LGT2, type/cherry-pick

#744 fix(load): stop goroutines after restore returned
  dm/worker/dm-worker.toml
  dm/worker/server_test.go
  dm/worker/task_checker_test.go
  dm/worker/worker_test.go
  loader/loader.go
  pkg/retry/errors.go
Labels: needs-cherry-pick-1.0, needs-update-release-note, priority/normal, status/LGT2, type/bug-fix

#748 CHANGELOG: add release notes for v1.0.6
  CHANGELOG.md
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, type/CHANGELOG

#747 fix(load): stop goroutines after restore returned (#744)
  dm/worker/status.go
  dm/worker/subtask_test.go
  dm/worker/task_checker.go
  dm/worker/task_checker_test.go
  loader/loader.go
  pkg/retry/errors.go
  tests/all_mode/run.sh
  tests/relay_interrupt/run.sh
Labels: needs-update-release-note, priority/normal, status/LGT2, type/bug-fix, type/cherry-pick

#750 *: update TiDB parser; update DM version for DM-Ansible
  dm/dm-ansible/inventory.ini
  go.mod
  go.sum
Labels: priority/normal, status/LGT2, type/CHANGELOG

#745 .*: fix bug that after execute pause-task the task may still running
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/unit/unit.go
  dm/unit/unit_test.go
  dm/worker/subtask.go
  loader/loader.go
  syncer/syncer.go
  tests/sharding/run.sh
Labels: needs-update-release-note, status/LGT2, type/cherry-pick

#752 track tool dependencies in the repo
  Makefile
  dm/pb/dmmaster.pb.go
  dm/pb/dmmaster.pb.gw.go
  dm/pb/dmworker.pb.go
  dm/pb/tracer.pb.go
  dm/pb/tracer_base.pb.go
  dm/pb/tracer_syncer.pb.go
  generate-dm.sh
  go.mod
  go.sum
  tests/generate-mock.sh
  tools.json
  tools/tools.go
Labels: dependencies, priority/normal, status/LGT2

#746 error_message: remove stack error message
  dm/ctl/common/util.go
  dm/ctl/master/check_task.go
  dm/ctl/master/list_member.go
  dm/ctl/master/migrate_relay.go
  dm/ctl/master/offline_member.go
  dm/ctl/master/operate_leader.go
  dm/ctl/master/operate_source.go
  dm/ctl/master/pause_relay.go
  dm/ctl/master/pause_task.go
  dm/ctl/master/purge_relay.go
  dm/ctl/master/query_error.go
  dm/ctl/master/query_status.go
  dm/ctl/master/resume_relay.go
  dm/ctl/master/resume_task.go
  dm/ctl/master/show_ddl_locks.go
  dm/ctl/master/sql_inject.go
  dm/ctl/master/sql_replace.go
  dm/ctl/master/sql_skip.go
  dm/ctl/master/start_task.go
  dm/ctl/master/stop_task.go
  dm/ctl/master/switch_relay_master.go
  dm/ctl/master/unlock_ddl_lock.go
  dm/ctl/master/update_masterconfig.go
  dm/ctl/master/update_relay.go
  dm/ctl/master/update_task.go
  dm/master/scheduler/scheduler.go
  dm/master/server.go
  dm/tracer/server.go
  dm/worker/server.go
Labels: needs-cherry-pick-1.0, needs-update-release-note, status/LGT2

#726 fix(shardddl): fix init schema fetch before applied DDL to downstream
  dm/common/common.go
  dm/master/shardddl/optimist.go
  dm/master/shardddl/optimist_test.go
  pkg/shardddl/optimism/info.go
  pkg/shardddl/optimism/info_test.go
  pkg/shardddl/optimism/lock.go
  pkg/shardddl/optimism/ops.go
  pkg/shardddl/optimism/ops_test.go
  pkg/shardddl/optimism/schema.go
  pkg/shardddl/optimism/schema_test.go
  syncer/checkpoint.go
  syncer/optimist.go
  syncer/shardddl/optimist.go
  syncer/shardddl/optimist_test.go
  syncer/syncer.go
  tests/sequence_sharding_optimistic/data/db1.increment0.sql
  tests/sequence_sharding_optimistic/data/db2.increment.sql
  tests/sequence_sharding_optimistic/data/db2.increment0.sql
  tests/sequence_sharding_optimistic/run.sh
Labels: priority/normal, status/LGT2, type/bug-fix

#731 .*: fix goroutine leak when stop task
  pkg/schema/tracker.go
  syncer/syncer.go
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, type/bug-fix

#754 cherry pick remove stack err
  dm/ctl/common/util.go
  dm/ctl/master/break_ddl_lock.go
  dm/ctl/master/check_task.go
  dm/ctl/master/migrate_relay.go
  dm/ctl/master/pause_relay.go
  dm/ctl/master/pause_task.go
  dm/ctl/master/purge_relay.go
  dm/ctl/master/query_error.go
  dm/ctl/master/query_status.go
  dm/ctl/master/refresh_worker_tasks.go
  dm/ctl/master/resume_relay.go
  dm/ctl/master/resume_task.go
  dm/ctl/master/show_ddl_locks.go
  dm/ctl/master/sql_inject.go
  dm/ctl/master/sql_replace.go
  dm/ctl/master/sql_skip.go
  dm/ctl/master/start_task.go
  dm/ctl/master/stop_task.go
  dm/ctl/master/switch_relay_master.go
  dm/ctl/master/unlock_ddl_lock.go
  dm/ctl/master/update_masterconfig.go
  dm/ctl/master/update_relay.go
  dm/ctl/master/update_task.go
  dm/master/server.go
  dm/tracer/server.go
  dm/worker/server.go
Labels: needs-update-release-note, status/LGT2, type/cherry-pick

#755 .*: fix gorountine leak
  syncer/syncer.go
Labels: status/LGT1, type/cherry-pick

#734 RFC: add document for optimistic ddl
  docs/RFCS/20191209_optimistic_ddl.md
  docs/media/add-drop-column.png
  docs/media/compatible-add-column-on-first-shard.png
  docs/media/compatible-character-sets-char-binary.png
  docs/media/compatible-character-types-text-blob.png
  docs/media/compatible-character-types.png
  docs/media/compatible-check.png
  docs/media/compatible-default.png
  docs/media/compatible-generated-columns.png
  docs/media/compatible-indices.png
  docs/media/compatible-integer-types.png
  docs/media/compatible-null.png
  docs/media/compatible-precision.png
  docs/media/compatible-sets-enums.png
  docs/media/compatible-stored-generated-columns.png
  docs/media/compatible.png
  docs/media/ddl-conflict.png
  docs/media/dm-master-ddl.png
  docs/media/modify-column-null.png
  docs/media/shard-table-merge.png
Labels: status/LGT2, type/doc

#753 error_message: add workaround for error
  _utils/terror_gen/checker_template.go
  _utils/terror_gen/errors_release.txt
  dm/config/source_config_test.go
  dm/config/subtask_test.go
  dm/config/task_test.go
  dm/master/config_test.go
  dm/master/server_test.go
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/tracer/http_handler_test.go
  dm/worker/server_test.go
  dm/worker/status.go
  dm/worker/subtask_test.go
  pkg/binlog/position_test.go
  pkg/terror/adapter_test.go
  pkg/terror/error_list.go
  pkg/terror/terror.go
  pkg/terror/terror_test.go
  syncer/db_test.go
  syncer/sharding-meta/shardmeta_test.go
  tests/dmctl_advance/check_list/sql_replace.sh
  tests/dmctl_advance/check_list/sql_skip.sh
  tests/relay_interrupt/run.sh
Labels: needs-cherry-pick-1.0, status/LGT2

#760 .*: replace black-white-list by block-allow-list
  _utils/terror_gen/errors_release.txt
  checker/checker.go
  dm/config/subtask.go
  dm/config/subtask_test.go
  dm/config/task.go
  dm/config/task_test.go
  dm/ctl/master/update_task.go
  dm/dm-ansible/conf/task_advanced.yaml.example
  dm/dm-ansible/conf/task_basic.yaml.example
  dm/master/server_test.go
  dm/master/task_advanced.yaml
  dm/master/task_basic.yaml
  dm/pb/dmmaster.pb.go
  dm/portal/api.go
  dm/portal/api_test.go
  dm/portal/config.go
  dm/portal/frontend/src/types.ts
  dm/portal/frontend/src/utils/config-util.ts
  dm/portal/statik/statik.go
  dm/proto/dmmaster.proto
  dm/worker/subtask.toml
  go.mod
  go.sum
  loader/loader.go
  mydumper/mydumper.go
  mydumper/util.go
  pkg/terror/error_list.go
  syncer/db_test.go
  syncer/ddl_test.go
  syncer/filter.go
  syncer/heartbeat.go
  syncer/heartbeat_test.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/_utils/check_not_contains
  tests/all_mode/conf/dm-task.yaml
  tests/all_mode/data/db1.prepare.sql
  tests/all_mode/data/db2.prepare.sql
  tests/all_mode/run.sh
  tests/compatibility/conf/dm-task.yaml
  tests/dmctl_basic/conf/dm-task.yaml
  tests/dmctl_command/conf/dm-task.yaml
  tests/full_mode/conf/dm-task.yaml
  tests/http_apis/conf/dm-task.yaml
  tests/import_goroutine_leak/conf/dm-task.yaml
  tests/incremental_mode/conf/dm-task.yaml
  tests/initial_unit/conf/dm-task.yaml
  tests/load_interrupt/conf/dm-task.yaml
  tests/online_ddl/conf/dm-task.yaml
  tests/print_status/conf/dm-task.yaml
  tests/relay_interrupt/conf/dm-task.yaml
  tests/retry_cancel/conf/dm-task.yaml
  tests/safe_mode/conf/dm-task.yaml
  tests/sequence_safe_mode/conf/dm-task.yaml
  tests/sequence_sharding/conf/dm-task.yaml
  tests/sharding/conf/dm-task.yaml
  tests/start_task/conf/dm-task.yaml
Labels: status/LGT2, type/cherry-pick

#758 checkpoint: flush global checkpoint when first time flush checkpoint
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/syncer_test.go
Labels: needs-cherry-pick-1.0, status/LGT2, type/bug-fix

#723 shardddl: add shardddl tests
  tests/_utils/shardddl_lib.sh
  tests/_utils/test_prepare
  tests/ha_cases/run.sh
  tests/shardddl1/conf/diff_config.toml
  tests/shardddl1/conf/dm-master.toml
  tests/shardddl1/conf/dm-worker1.toml
  tests/shardddl1/conf/dm-worker2.toml
  tests/shardddl1/conf/double-source-optimistic.yaml
  tests/shardddl1/conf/double-source-pessimistic.yaml
  tests/shardddl1/conf/no-sharding.yaml
  tests/shardddl1/conf/single-source-no-routes.yaml
  tests/shardddl1/conf/single-source-optimistic.yaml
  tests/shardddl1/conf/single-source-pessimistic.yaml
  tests/shardddl1/conf/source1.toml
  tests/shardddl1/conf/source2.toml
  tests/shardddl1/run.sh
  tests/shardddl2/conf/diff_config.toml
  tests/shardddl2/conf/dm-master.toml
  tests/shardddl2/conf/dm-worker1.toml
  tests/shardddl2/conf/dm-worker2.toml
  tests/shardddl2/conf/double-source-optimistic.yaml
  tests/shardddl2/conf/double-source-pessimistic.yaml
  tests/shardddl2/conf/source1.toml
  tests/shardddl2/conf/source2.toml
  tests/shardddl2/run.sh
  tests/shardddl3/conf/diff_config.toml
  tests/shardddl3/conf/dm-master.toml
  tests/shardddl3/conf/dm-worker1.toml
  tests/shardddl3/conf/dm-worker2.toml
  tests/shardddl3/conf/double-source-optimistic.yaml
  tests/shardddl3/conf/double-source-pessimistic.yaml
  tests/shardddl3/conf/single-source-optimistic.yaml
  tests/shardddl3/conf/single-source-pessimistic.yaml
  tests/shardddl3/conf/source1.toml
  tests/shardddl3/conf/source2.toml
  tests/shardddl3/run.sh
Labels: priority/normal, status/LGT2, type/test
