Repository pingcap/dm, pull requests merged in 2020-01, with the labels that each got.

#379 syncer,pkg/schema: implement schema tracker
  _utils/terror_gen/check.sh
  _utils/terror_gen/errors_release.txt
  dm/portal/api.go
  dm/portal/api_test.go
  pkg/schema/tracker.go
  pkg/schema/tracker_test.go
  pkg/terror/error_list.go
  pkg/terror/terror.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/db.go
  syncer/dml.go
  syncer/dml_test.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/_utils/check_log_contains
Labels: priority/normal, should-update-docs, should-update-release-note, status/LGT2, type/feature

#446 track tool dependencies in the repo
  .gitignore
  Makefile
  dm/pb/dmmaster.pb.go
  dm/pb/dmmaster.pb.gw.go
  dm/pb/dmworker.pb.go
  dm/pb/tracer.pb.go
  dm/pb/tracer_base.pb.go
  dm/pb/tracer_syncer.pb.go
  generate-dm.sh
  go.mod
  go.sum
  tests/generate-mock.sh
  tools.json
  tools/tools.go
Labels: dependencies, priority/normal, status/LGT2

#434 dm-worker: add enable-relay config and refine binlog streamer in binlog replication unit
  _utils/terror_gen/errors_release.txt
  cmd/dm-syncer/config.go
  cmd/dm-syncer/main.go
  cmd/dm-worker/main.go
  dm/config/subtask.go
  dm/config/task.go
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/worker/config.go
  dm/worker/config_test.go
  dm/worker/server.go
  dm/worker/subtask.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  pkg/binlog/filename.go
  pkg/binlog/filename_test.go
  pkg/binlog/position.go
  pkg/binlog/position_test.go
  pkg/streamer/reader.go
  pkg/streamer/streamer.go
  pkg/terror/error_list.go
  pkg/utils/db.go
  syncer/checkpoint.go
  syncer/relay.go
  syncer/sharding-meta/shardmeta.go
  syncer/sharding_group.go
  syncer/status.go
  syncer/streamer_controller.go
  syncer/syncer.go
  syncer/syncer_test.go
  syncer/util.go
  syncer/util_test.go
  tests/dmctl_basic/conf/dm-worker1.toml
  tests/dmctl_basic/conf/dm-worker2.toml
  tests/dmctl_basic/run.sh
  tests/initial_unit/conf/dm-worker1.toml
  tests/relay_interrupt/conf/dm-worker1.toml
  tests/relay_interrupt/run.sh
  tests/retry_cancel/conf/dm-worker1.toml
  tests/retry_cancel/conf/dm-worker2.toml
Labels: priority/important, status/LGT2, type/feature

#450 HA: add `advertise-addr` for DM-worker
  dm/worker/config.go
  dm/worker/dm-worker.toml
  dm/worker/join.go
  dm/worker/server.go
  dm/worker/server_test.go
  tests/_utils/run_dm_worker
Labels: priority/normal, should-update-dm-ansible, should-update-docs, status/LGT2, type/feature

#454 generate-dm.sh: allow running this script on Windows bash (MSYS2)
  generate-dm.sh
Labels: priority/unimportant, status/LGT2, type/enhancement

#449 syncer: don't clear online ddl if execute ddl failed
  _utils/terror_gen/errors_release.txt
  pkg/terror/error_list.go
  syncer/checkpoint.go
  syncer/db.go
  syncer/online_ddl.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/online_ddl/conf/diff_config.toml
  tests/online_ddl/conf/dm-task.yaml
Labels: priority/important, should-cherry-pick-1.0, status/LGT2, type/bug-fix

#462 ha: handle invalid operate type on worker
  dm/ctl/master/operate_mysql_worker.go
  dm/master/server.go
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  tests/dmctl_basic/run.sh
Labels: priority/unimportant, status/LGT2
