Repository pingcap/dm, pull requests merged in 2020-08, with the labels that each got.

#846 feat: get subtask config and status of v1.0.x from dm-worker
  _utils/terror_gen/errors_release.txt
  dm/pb/dmworker.pb.go
  dm/pbmock/dmworker.go
  dm/proto/dmworker.proto
  dm/worker/v1meta.go
  errors.toml
  go.mod
  pkg/terror/error_list.go
  pkg/v1workermeta/api.go
  pkg/v1workermeta/api_test.go
  pkg/v1workermeta/db.go
  pkg/v1workermeta/meta.go
  pkg/v1workermeta/meta_test.go
  pkg/v1workermeta/v106_data_for_test/kv/000002.ldb
  pkg/v1workermeta/v106_data_for_test/kv/000006.ldb
  pkg/v1workermeta/v106_data_for_test/kv/000007.ldb
  pkg/v1workermeta/v106_data_for_test/kv/000009.ldb
  pkg/v1workermeta/v106_data_for_test/kv/000010.ldb
  pkg/v1workermeta/v106_data_for_test/kv/000011.log
  pkg/v1workermeta/v106_data_for_test/kv/000012.ldb
  pkg/v1workermeta/v106_data_for_test/kv/000013.ldb
  pkg/v1workermeta/v106_data_for_test/kv/CURRENT
  pkg/v1workermeta/v106_data_for_test/kv/CURRENT.bak
  pkg/v1workermeta/v106_data_for_test/kv/LOCK
  pkg/v1workermeta/v106_data_for_test/kv/LOG
  pkg/v1workermeta/v106_data_for_test/kv/MANIFEST-000004
Labels: needs-update-docs, priority/important, status/LGT2, type/feature

#854 ctl: support using task-file when need task-name
  dm/ctl/common/util.go
  dm/ctl/master/get_task_config.go
  dm/ctl/master/operate_schema.go
  dm/ctl/master/pause_task.go
  dm/ctl/master/resume_task.go
  dm/ctl/master/stop_task.go
  tests/dmctl_basic/check_list/pause_task.sh
  tests/dmctl_basic/check_list/resume_task.sh
  tests/dmctl_basic/check_list/stop_task.sh
  tests/dmctl_basic/run.sh
Labels: needs-cherry-pick-1.0, needs-update-docs, needs-update-release-note, priority/normal, status/LGT1, type/feature

#855 *: support sourceID on operate-source stop
  dm/ctl/master/operate_source.go
  dm/master/server.go
  dm/pb/dmmaster.pb.go
  dm/proto/dmmaster.proto
  tests/dmctl_basic/check_list/operate_source.sh
  tests/dmctl_basic/run.sh
Labels: needs-update-docs, needs-update-release-note, priority/normal, status/LGT2, type/feature

#857 mydumper, worker: don't auto-resume when can't acquire global lock
  _utils/terror_gen/errors_release.txt
  dm/worker/task_checker.go
  mydumper/mydumper.go
  pkg/terror/error_list.go
  tests/full_mode/run.sh
Labels: priority/normal, status/LGT2, type/bug-fix

#858 feat: upgrade v1.0.x metadata tables
  _utils/terror_gen/errors_release.txt
  errors.toml
  pkg/binlog/reader/util.go
  pkg/binlog/reader/util_test.go
  pkg/terror/error_list.go
  pkg/v1dbschema/schema.go
  pkg/v1dbschema/schema_test.go
  pkg/v1dbschema/v106_data_for_test/v106_syncer_checkpoint-schema.sql
  pkg/v1dbschema/v106_data_for_test/v106_syncer_checkpoint.sql
  pkg/v1dbschema/v106_data_for_test/v106_syncer_onlineddl-schema.sql
  pkg/v1dbschema/v106_data_for_test/v106_syncer_onlineddl.sql
Labels: needs-update-docs, priority/important, status/LGT2, type/feature

#853 *: add panel for start leader and heartbeat update error
  dm/dm-ansible/conf/dm_worker.rules.yml
  dm/dm-ansible/scripts/dm.json
  dm/master/election.go
  dm/master/metrics/metrics.go
  pkg/election/election.go
  syncer/heartbeat.go
  syncer/metrics.go
Labels: priority/normal, status/LGT2, type/dm-ansible, type/feature

#860 errors: sync error with release-1.0
  _utils/terror_gen/errors_release.txt
  errors.toml
  pkg/terror/error_list.go
Labels: priority/unimportant, status/LGT1

#866 *: don't auto-resume for dump unit error
  _utils/terror_gen/errors_release.txt
  dm/worker/task_checker.go
  mydumper/mydumper.go
  pkg/retry/errors.go
  pkg/terror/error_list.go
  tests/full_mode/run.sh
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, type/bug-fix

#868 worker: avoid illegal zero value of channel
  dm/worker/server.go
  go.mod
  go.sum
Labels: priority/unimportant, status/LGT2, type/bug-fix

#871 test: disable task_checker for sharding test
  tests/sharding/conf/source2.yaml
  tests/sharding/run.sh
Labels: priority/unimportant, status/LGT1, type/bug-fix

#873 test: add log to investigate test fail
  dm/master/server_test.go
Labels: priority/unimportant, status/LGT1, type/bug-fix

#872 *: don't auto-resume for dump unit error #866
  _utils/terror_gen/errors_release.txt
  dm/worker/task_checker.go
  dumpling/dumpling.go
  errors.toml
  mydumper/mydumper.go
  pkg/retry/errors.go
  pkg/terror/error_list.go
  tests/full_mode/run.sh
Labels: priority/normal, status/LGT2, type/cherry-pick

#875 dumpling: fix args config
  dumpling/util.go
  dumpling/util_test.go
  tests/shardddl1/conf/single-source-no-sharding.yaml
  tests/shardddl1/run.sh
Labels: priority/normal, status/LGT2, type/bug-fix

#870 precheck: support primary/unique key check
  go.mod
  go.sum
  tests/dm_syncer/data/db1.prepare.sql
  tests/dmctl_command/data/db1.prepare.sql
  tests/full_mode/data/db1.prepare.sql
  tests/full_mode/run.sh
  tests/ha/data/db1.prepare.sql
  tests/ha_cases/data/db1.prepare.sql
  tests/ha_master/data/db1.prepare.sql
  tests/incremental_mode/data/db1.prepare.sql
  tests/shardddl1/conf/double-source-optimistic.yaml
  tests/shardddl1/conf/double-source-pessimistic.yaml
  tests/shardddl1/conf/single-source-no-routes.yaml
  tests/shardddl1/conf/single-source-no-sharding.yaml
  tests/shardddl1/conf/single-source-optimistic.yaml
  tests/shardddl1/conf/single-source-pessimistic.yaml
  tests/shardddl2/conf/double-source-optimistic.yaml
  tests/shardddl2/conf/double-source-pessimistic.yaml
  tests/shardddl3/conf/double-source-optimistic.yaml
  tests/shardddl3/conf/double-source-pessimistic.yaml
  tests/shardddl3/conf/single-source-optimistic.yaml
  tests/shardddl3/conf/single-source-pessimistic.yaml
Labels: needs-cherry-pick-1.0, needs-update-release-note, priority/normal, status/LGT1, type/feature

#861 feat: import/upgrade from v1.0.x cluster
  _utils/terror_gen/errors_release.txt
  dm/master/bootstrap.go
  dm/master/bootstrap_test.go
  dm/master/config.go
  dm/master/election.go
  dm/master/workerrpc/interface.go
  dm/master/workerrpc/rawgrpc.go
  errors.toml
  pkg/terror/error_list.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/version.go
  pkg/upgrade/version_test.go
  pkg/v1dbschema/schema.go
  syncer/checkpoint.go
  syncer/optimist.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/import_v10x/conf/diff_config.toml
  tests/import_v10x/conf/dm-master.toml
  tests/import_v10x/conf/dm-worker1.toml
  tests/import_v10x/conf/dm-worker2.toml
  tests/import_v10x/conf/source1.yaml
  tests/import_v10x/conf/source2.yaml
  tests/import_v10x/data/db1.increment.sql
  tests/import_v10x/data/db1.prepare.sql
  tests/import_v10x/data/db2.increment.sql
  tests/import_v10x/data/db2.prepare.sql
  tests/import_v10x/data/v106_syncer_checkpoint.sql
  tests/import_v10x/dm_worker1_meta/kv/000002.ldb
  tests/import_v10x/dm_worker1_meta/kv/000005.log
  tests/import_v10x/dm_worker1_meta/kv/000006.ldb
  tests/import_v10x/dm_worker1_meta/kv/000007.ldb
  tests/import_v10x/dm_worker1_meta/kv/000010.log
  tests/import_v10x/dm_worker1_meta/kv/CURRENT
  tests/import_v10x/dm_worker1_meta/kv/CURRENT.bak
  tests/import_v10x/dm_worker1_meta/kv/LOCK
  tests/import_v10x/dm_worker1_meta/kv/LOG
  tests/import_v10x/dm_worker1_meta/kv/MANIFEST-000004
  tests/import_v10x/dm_worker1_meta/kv/MANIFEST-000011
  tests/import_v10x/dm_worker2_meta/kv/000002.ldb
  tests/import_v10x/dm_worker2_meta/kv/000005.log
  tests/import_v10x/dm_worker2_meta/kv/000006.ldb
  tests/import_v10x/dm_worker2_meta/kv/000007.ldb
  tests/import_v10x/dm_worker2_meta/kv/000010.log
  tests/import_v10x/dm_worker2_meta/kv/CURRENT
  tests/import_v10x/dm_worker2_meta/kv/CURRENT.bak
  tests/import_v10x/dm_worker2_meta/kv/LOCK
  tests/import_v10x/dm_worker2_meta/kv/LOG
  tests/import_v10x/dm_worker2_meta/kv/MANIFEST-000004
  tests/import_v10x/dm_worker2_meta/kv/MANIFEST-000011
  tests/import_v10x/run.sh
  tests/others_integration.txt
Labels: needs-update-docs, needs-update-release-note, priority/important, status/LGT2, type/feature

#881 syncer: add test for upstream instance restart
  syncer/streamer_controller.go
  tests/drop_column_with_index/run.sh
Labels: priority/normal, status/LGT2, status/PTAL, type/test

#883 test: fix TestOperateSource
  dm/master/server_test.go
Labels: priority/unimportant, status/LGT1, type/bug-fix

#876 syncer: fix wrong conversion for mysql BIT
  syncer/dml.go
  syncer/dml_test.go
  tests/all_mode/data/db1.increment.sql
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, type/bug-fix

#882 pkg/binlog: parse statusVars and get ansi-quotes mode
  _utils/terror_gen/errors_release.txt
  errors.toml
  go.sum
  pkg/binlog/event/util.go
  pkg/binlog/event/util_test.go
  pkg/terror/error_list.go
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, type/feature

#890 fix: reset the start part of GTID sets when recovering from relay log or upgrading v1.0.x checkpoint
  pkg/gtid/gtid.go
  pkg/gtid/gtid_test.go
  pkg/v1dbschema/schema.go
  pkg/v1dbschema/schema_test.go
  relay/relay.go
  relay/relay_test.go
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, type/bug-fix

#887 precheck: support primary/unique key check #870
  go.mod
  go.sum
  tests/dmctl_command/data/db1.prepare.sql
  tests/filter_user_cancel/data/db1.prepare.sql
  tests/full_mode/data/db1.prepare.sql
  tests/full_mode/run.sh
  tests/incremental_mode/data/db1.prepare.sql
Labels: needs-update-release-note, status/LGT2, type/cherry-pick

#886 syncer: fix wrong conversion for mysql BIT (#876)
  syncer/dml.go
  syncer/dml_test.go
  tests/all_mode/data/db1.increment.sql
Labels: priority/normal, status/LGT2, type/cherry-pick

#850 feat: add handle-error command
  _utils/terror_gen/errors_release.txt
  dm/command/argument.go
  dm/command/argument_test.go
  dm/ctl/common/util.go
  dm/ctl/ctl.go
  dm/ctl/master/handle_error.go
  dm/ctl/master/sql_inject.go
  dm/ctl/master/sql_operation.go
  dm/ctl/master/sql_replace.go
  dm/ctl/master/sql_skip.go
  dm/master/server.go
  dm/master/shardddl/pessimist.go
  dm/master/sql-operator/operator.go
  dm/master/sql-operator/operator_test.go
  dm/master/workerrpc/interface.go
  dm/master/workerrpc/rawgrpc.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmmaster.pb.gw.go
  dm/pb/dmworker.pb.go
  dm/pbmock/dmmaster.go
  dm/pbmock/dmworker.go
  dm/proto/dmmaster.proto
  dm/proto/dmworker.proto
  dm/worker/server.go
  dm/worker/subtask.go
  dm/worker/worker.go
  errors.toml
  pkg/binlog/event/util.go
  pkg/binlog/position.go
  pkg/binlog/position_test.go
  pkg/terror/error_list.go
  syncer/checkpoint.go
  syncer/err-operator/operator.go
  syncer/err-operator/operator_test.go
  syncer/handle_error.go
  syncer/inject_sql.go
  syncer/job.go
  syncer/job_test.go
  syncer/operator.go
  syncer/optimist.go
  syncer/sql-operator/operator.go
  syncer/sql-operator/operator_test.go
  syncer/syncer.go
  tests/dmctl_advance/check_list/handle_error.sh
  tests/dmctl_advance/check_list/sql_replace.sh
  tests/dmctl_advance/check_list/sql_skip.sh
  tests/dmctl_advance/run.sh
  tests/dmctl_command/run.sh
  tests/handle_error/conf/diff_config.toml
  tests/handle_error/conf/dm-master.toml
  tests/handle_error/conf/dm-worker1.toml
  tests/handle_error/conf/dm-worker2.toml
  tests/handle_error/conf/double-source-no-sharding.yaml
  tests/handle_error/conf/double-source-optimistic.yaml
  tests/handle_error/conf/double-source-pessimistic.yaml
  tests/handle_error/conf/source1.yaml
  tests/handle_error/conf/source2.yaml
  tests/handle_error/lib.sh
  tests/handle_error/run.sh
  tests/others_integration.txt
Labels: needs-update-docs, needs-update-release-note, priority/important, status/LGT2

#884 fix: support `--tables-list` for dumpling
  dumpling/dumpling.go
  dumpling/util.go
  dumpling/util_test.go
  go.mod
  go.sum
Labels: priority/normal, status/LGT2, type/bug-fix

#892 ctl: support using task-file when need task-name (#854)
  dm/ctl/common/util.go
  dm/ctl/master/pause_task.go
  dm/ctl/master/resume_task.go
  dm/ctl/master/stop_task.go
  tests/dmctl_basic/check_list/pause_task.sh
  tests/dmctl_basic/check_list/resume_task.sh
  tests/dmctl_basic/check_list/stop_task.sh
  tests/dmctl_basic/run.sh
Labels: priority/normal, status/LGT2, type/cherry-pick

#888 pkg/binlog: parse statusVars and get ansi-quotes mode (#882)
  _utils/terror_gen/errors_release.txt
  pkg/binlog/event/util.go
  pkg/binlog/event/util_test.go
  pkg/terror/error_list.go
Labels: priority/normal, status/LGT2, type/cherry-pick

#894 fix: redirect stream when get last replace
  syncer/syncer.go
  tests/handle_error/run.sh
Labels: priority/normal, status/LGT2, type/bug-fix

#895 *: fix test and yaml suffix
  dm/ctl/common/util.go
  dm/worker/worker_test.go
Labels: priority/unimportant, status/LGT2, status/PTAL, type/bug-fix

#898 *: check shard mode for `unlock-ddl-lock`
  dm/master/ddl_lock.go
  dm/master/server.go
  pkg/shardddl/optimism/keeper.go
  pkg/shardddl/pessimism/keeper.go
  pkg/utils/common.go
  tests/sequence_sharding_optimistic/run.sh
Labels: needs-update-docs, status/LGT2, type/bug-fix

#899 fix: TLS support for dumpling and syncer in v2.0
  dumpling/dumpling.go
  dumpling/util.go
  syncer/syncer.go
Labels: priority/normal, status/LGT2, type/bug-fix

#901 dmctl: disable unsupported command
  dm/ctl/ctl.go
  pkg/retry/errors.go
  tests/dmctl_advance/run.sh
  tests/dmctl_basic/run.sh
  tests/dmctl_command/run.sh
  tests/shardddl3/run.sh
Labels: priority/normal, status/LGT2

#902 dep: update tidb-tools to support Aurora S3 privileges
  go.mod
  go.sum
Labels: priority/unimportant, status/LGT2, type/dependencies

#903 master: replace wrong usage of utils.Decrypt
  dm/master/server.go
Labels: priority/unimportant, status/LGT1, type/bug-fix

#904 README: update build status icon
  README.md
Labels: priority/unimportant, status/PTAL

#906 feat: support to dump data with column name
  dumpling/dumpling.go
  go.mod
  go.sum
  tests/print_status/run.sh
Labels: dependencies, needs-update-docs, priority/normal, status/LGT2, type/enhancement

#905 syncer: ignore TRUNCATE TABLE in optimistic mode
  syncer/syncer.go
  tests/shardddl1/run.sh
Labels: priority/normal, status/LGT1, type/bug-fix

#908 log: hide password in log
  dm/config/task.go
  dm/master/server.go
  pkg/utils/util.go
  pkg/utils/util_test.go
  tests/_utils/check_log_not_contains
  tests/all_mode/run.sh
Labels: priority/normal, status/LGT1, type/bug-fix

#910 dmctl: update help message of command
  dm/ctl/common/config.go
  dm/ctl/ctl.go
  dm/ctl/master/check_task.go
  dm/ctl/master/get_task_config.go
  dm/ctl/master/handle_error.go
  dm/ctl/master/list_member.go
  dm/ctl/master/offline_member.go
  dm/ctl/master/operate_leader.go
  dm/ctl/master/operate_schema.go
  dm/ctl/master/operate_source.go
  dm/ctl/master/pause_task.go
  dm/ctl/master/query_status.go
  dm/ctl/master/resume_task.go
  dm/ctl/master/show_ddl_locks.go
  dm/ctl/master/start_task.go
  dm/ctl/master/stop_task.go
  dm/ctl/master/unlock_ddl_lock.go
  tests/dmctl_advance/check_list/unlock_ddl_lock.sh
Labels: priority/normal, status/LGT2

#911 feat: support `get-task-config` for tasks imported from v1.0.x
  dm/config/task.go
  dm/config/task_test.go
  dm/master/bootstrap.go
  tests/import_v10x/conf/task.yaml
  tests/import_v10x/run.sh
Labels: priority/normal, status/LGT1, status/PTAL, type/feature

#912 dumpling: hide password in dumpling log
  Makefile
  _utils/mod_check/check.sh
  _utils/terror_gen/check.sh
  dumpling/dumpling.go
  go.mod
  go.sum
  tests/all_mode/run.sh
Labels: priority/normal, status/LGT2

#922 test: remove wait time to reduce indetermination
  syncer/streamer_controller.go
  tests/drop_column_with_index/run.sh
Labels: priority/unimportant, status/LGT2, type/bug-fix

#925 checkpoint: fix data race
  syncer/checkpoint.go
Labels: needs-cherry-pick-1.0, priority/unimportant, status/LGT1, type/bug-fix

#909 dump: retrieve ANSI_QUOTES from upstream
  dm/config/task.go
  dm/worker/worker.go
  dumpling/dumpling.go
  tests/drop_column_with_index/conf/dm-task.yaml
  tests/drop_column_with_index/run.sh
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, priority/normal, status/LGT2, type/feature

#927 checkpoint: fix data race (#925)
  syncer/checkpoint.go
Labels: priority/unimportant, status/LGT2, type/cherry-pick

#923 test: move status check later
  _utils/terror_gen/errors_release.txt
  errors.toml
  pkg/terror/error_list.go
  tests/full_mode/run.sh
Labels: priority/unimportant, status/PTAL, type/bug-fix

#931 dep: update pingcap/pd to tikv/pd
  checker/checker.go
  dm/master/election_test.go
  dm/master/etcd_test.go
  dm/master/server_test.go
  dm/worker/server_test.go
  dm/worker/worker_test.go
  go.mod
  go.sum
  pkg/election/election_test.go
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, priority/unimportant, status/LGT2, type/dependencies

#928 dump: retrieve ANSI_QUOTES from upstream (#909)
  dm/config/task.go
  dm/worker/worker.go
  dumpling/dumpling.go
  tests/drop_column_with_index/conf/dm-task.yaml
  tests/drop_column_with_index/run.sh
Labels: priority/normal, status/LGT2, type/cherry-pick

#929 dump: retrieve ANSI_QUOTES from upstream (#909)
  dm/config/task.go
  mydumper/mydumper.go
Labels: priority/normal, status/LGT2, type/cherry-pick

#933 Fix auto resume
  dm/worker/worker_test.go
Labels: priority/unimportant, status/PTAL, type/bug-fix

#926 config: support domain:port as well as ip:port
  dm/master/config.go
  dm/master/config_test.go
  dm/worker/config.go
  pkg/utils/util.go
  pkg/utils/util_test.go
  tests/ha_master/conf/diff_config.toml
  tests/ha_master/conf/dm-master-join1.toml
  tests/ha_master/conf/dm-master1.toml
  tests/ha_master/conf/dm-master2.toml
  tests/ha_master/conf/dm-master3.toml
  tests/ha_master/conf/dm-master4.toml
  tests/ha_master/conf/dm-master5.toml
  tests/ha_master/conf/dm-task.yaml
  tests/ha_master/conf/dm-worker1.toml
  tests/ha_master/conf/dm-worker2.toml
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, type/bug-fix

#942 basedb: close db when fail ping
  pkg/conn/basedb.go
  pkg/conn/basedb_test.go
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, priority/unimportant, status/LGT2, type/bug-fix

#939 shardddl: fix lock not found after try sync
  dm/master/shardddl/optimist.go
Labels: already-update-release-note, needs-cherry-pick-2.0, status/LGT1, type/bug-fix

#945 basedb: close db when fail ping (#942)
  pkg/conn/basedb.go
  pkg/conn/basedb_test.go
Labels: needs-update-release-note, priority/unimportant, status/LGT1, type/bug-fix, type/cherry-pick

#916 Quality reinforcement: fix unstable test cases
  _utils/terror_gen/errors_release.txt
  dm/worker/worker_test.go
  errors.toml
  pkg/streamer/reader_test.go
  pkg/terror/error_list.go
  syncer/checkpoint.go
  syncer/streamer_controller.go
  syncer/syncer_test.go
  tests/_utils/get_leader
  tests/_utils/run_dm_master
  tests/_utils/run_dm_worker
  tests/_utils/test_prepare
  tests/drop_column_with_index/run.sh
  tests/full_mode/run.sh
  tests/ha_master/run.sh
Labels: needs-cherry-pick-2.0, status/LGT2, type/test

#947 dep: update tidb-tools to support AWS privileges
  go.mod
  go.sum
Labels: dependencies, needs-cherry-pick-2.0, needs-update-release-note, priority/unimportant, status/LGT2

#948 fix: handle `null` table_info after importing from v1.0.x
  syncer/checkpoint.go
  tests/import_v10x/data/v106_syncer_checkpoint.sql
Labels: needs-cherry-pick-2.0, needs-update-release-note, priority/important, status/LGT2, type/bug-fix

#949 command: support task-file for more command
  dm/ctl/master/query_status.go
  dm/ctl/master/show_ddl_locks.go
  tests/dmctl_basic/check_list/query_status.sh
  tests/dmctl_basic/check_list/show_ddl_locks.sh
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, needs-update-docs, priority/unimportant, status/LGT2

#937 config: check and correct format of addr and URL
  dm/master/config.go
  dm/worker/config.go
  dm/worker/join.go
  pkg/utils/util.go
  pkg/utils/util_test.go
  tests/ha_master/conf/dm-worker1.toml
Labels: needs-cherry-pick-2.0, needs-update-docs, priority/normal, status/LGT2, type/bug-fix

#953 Quality reinforcement: fix unstable test cases (#916)
  _utils/terror_gen/errors_release.txt
  dm/worker/worker_test.go
  errors.toml
  pkg/streamer/reader_test.go
  pkg/terror/error_list.go
  syncer/checkpoint.go
  syncer/streamer_controller.go
  syncer/syncer_test.go
  tests/_utils/get_leader
  tests/_utils/run_dm_master
  tests/_utils/run_dm_worker
  tests/_utils/test_prepare
  tests/drop_column_with_index/run.sh
  tests/full_mode/run.sh
  tests/ha_master/run.sh
Labels: status/LGT2, type/test

#946 source: check whether GTID is `ON` in the upstream ealier
  _utils/terror_gen/errors_release.txt
  dm/config/source_config.go
  dm/master/server.go
  errors.toml
  pkg/terror/error_list.go
  pkg/terror/terror.go
  pkg/utils/db.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, status/PTAL, type/bug-fix

#958 dumpling: compatibility for `--no-locks`
  _utils/terror_gen/errors_release.txt
  dm/dm-ansible/conf/task_advanced.yaml.example
  dm/master/task_advanced.yaml
  dumpling/util.go
  dumpling/util_test.go
  errors.toml
  pkg/terror/error_list.go
Labels: needs-cherry-pick-2.0, needs-update-release-note, priority/normal, status/LGT2

#962 *: check channel closed in select{}
  dm/worker/server.go
  dm/worker/worker.go
  pkg/ha/bound.go
  pkg/ha/keepalive.go
  pkg/ha/stage.go
  pkg/shardddl/optimism/info.go
  pkg/shardddl/optimism/operation.go
  pkg/shardddl/optimism/table.go
  pkg/shardddl/pessimism/info.go
  pkg/shardddl/pessimism/operation.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, type/bug-fix

#964 *: warn the deprecated `remove-meta` in task config
  dm/config/task.go
  dm/master/server.go
  syncer/checkpoint.go
  tests/dmctl_command/conf/dm-task.yaml
  tests/dmctl_command/run.sh
  tests/import_v10x/conf/task.yaml
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2, type/bug-fix
