Repository pingcap/dm, pull requests merged in 2020-04, with the labels that each got.

#572 syncer: minor fix
  syncer/sharding_group.go
  syncer/syncer.go
  tests/others_integration.txt
  tests/sharding2/conf/diff_config.toml
  tests/sharding2/conf/dm-master.toml
  tests/sharding2/conf/dm-task.yaml
  tests/sharding2/conf/dm-worker1.toml
  tests/sharding2/conf/dm-worker2.toml
  tests/sharding2/conf/source1.toml
  tests/sharding2/conf/source2.toml
  tests/sharding2/data/db1.dropdb.sql
  tests/sharding2/data/db1.increment.sql
  tests/sharding2/data/db2.dropdb.sql
  tests/sharding2/data/db2.increment.sql
  tests/sharding2/run.sh
Labels: priority/important, status/LGT1, type/bug-fix

#574 syncer/: fix track ddl
  dm/master/config.go
  dm/master/config_test.go
  dm/master/etcd_test.go
  dm/master/server.go
  syncer/syncer.go
  tests/_utils/env_variables
  tests/ha/conf/dm-master1.toml
  tests/ha/conf/dm-master2.toml
  tests/ha/conf/dm-master3.toml
  tests/ha/conf/dm-master5.toml
  tests/ha/conf/dm-master6.toml
  tests/ha/conf/dm-worker1.toml
  tests/ha/conf/dm-worker2.toml
  tests/ha/conf/dm-worker3.toml
  tests/ha/run.sh
  tests/sharding2/data/db1.increment.sql
  tests/sharding2/data/db1.increment2.sql
  tests/sharding2/data/db2.increment.sql
  tests/sharding2/data/db2.increment2.sql
  tests/sharding2/run.sh
Labels: priority/important, status/LGT2, type/bug-fix

#555 pessimism/: handle shard ddl watch error
  dm/master/scheduler/scheduler.go
  dm/master/shardddl/pessimist.go
  dm/master/shardddl/pessimist_test.go
  dm/worker/server.go
  dm/worker/worker.go
  pkg/shardddl/pessimism/info.go
  pkg/shardddl/pessimism/info_test.go
  pkg/shardddl/pessimism/operation.go
  pkg/shardddl/pessimism/operation_test.go
  syncer/shardddl/pessimist.go
Labels: priority/normal, status/LGT2

#568 *: add optimistic sharding mode
  _utils/terror_gen/errors_release.txt
  dm/common/common.go
  dm/config/subtask.go
  dm/config/subtask_test.go
  dm/config/task.go
  dm/config/task_test.go
  dm/master/election.go
  dm/master/server.go
  dm/master/shardddl/optimist.go
  dm/master/shardddl/optimist_test.go
  dm/master/shardddl/pessimist_test.go
  go.mod
  go.sum
  pkg/shardddl/optimism/doc.go
  pkg/shardddl/optimism/info.go
  pkg/shardddl/optimism/info_test.go
  pkg/shardddl/optimism/keeper.go
  pkg/shardddl/optimism/keeper_test.go
  pkg/shardddl/optimism/lock.go
  pkg/shardddl/optimism/lock_test.go
  pkg/shardddl/optimism/operation.go
  pkg/shardddl/optimism/operation_test.go
  pkg/shardddl/optimism/ops.go
  pkg/shardddl/optimism/ops_test.go
  pkg/shardddl/optimism/table.go
  pkg/shardddl/optimism/table_test.go
  pkg/terror/error_list.go
  relay/relay.go
  syncer/optimist.go
  syncer/shardddl/optimist.go
  syncer/shardddl/optimist_test.go
  syncer/shardddl/pessimist_test.go
  syncer/status.go
  syncer/syncer.go
  tests/others_integration.txt
  tests/sequence_sharding_optimistic/conf/diff_config.toml
  tests/sequence_sharding_optimistic/conf/dm-master.toml
  tests/sequence_sharding_optimistic/conf/dm-task.yaml
  tests/sequence_sharding_optimistic/conf/dm-worker1.toml
  tests/sequence_sharding_optimistic/conf/dm-worker2.toml
  tests/sequence_sharding_optimistic/conf/source1.toml
  tests/sequence_sharding_optimistic/conf/source2.toml
  tests/sequence_sharding_optimistic/data/db1.increment.sql
  tests/sequence_sharding_optimistic/data/db1.increment0.sql
  tests/sequence_sharding_optimistic/data/db1.prepare.sql
  tests/sequence_sharding_optimistic/data/db2.increment.sql
  tests/sequence_sharding_optimistic/data/db2.increment0.sql
  tests/sequence_sharding_optimistic/data/db2.prepare.sql
  tests/sequence_sharding_optimistic/run.sh
Labels: needs-update-docs, needs-update-release-note, priority/important, status/LGT2, type/feature

#573 readme, media: update outdated doc and image links in readme
  README.md
  docs/media/dm-architecture.png
Labels: contribution, needs-cherry-pick-1.0, status/LGT2

#579 worker/: fix subtask config pointer usage
  dm/worker/server.go
Labels: priority/important, status/LGT1, type/bug-fix

#575 feature: remove metrics when stopping task
  dm/worker/metrics.go
  dm/worker/subtask.go
  dumpling/dumpling.go
  dumpling/metrics.go
  loader/loader.go
  loader/metrics.go
  mydumper/metrics.go
  mydumper/mydumper.go
  pkg/metricsproxy/countervec.go
  pkg/metricsproxy/countervec_test.go
  pkg/metricsproxy/gaugevec.go
  pkg/metricsproxy/gaugevec_test.go
  pkg/metricsproxy/histogramvec.go
  pkg/metricsproxy/histogramvec_test.go
  pkg/metricsproxy/proxy.go
  pkg/metricsproxy/proxy_test.go
  pkg/metricsproxy/summaryvec.go
  pkg/metricsproxy/summaryvec_test.go
  relay/metrics.go
  syncer/metrics.go
  syncer/syncer.go
Labels: contribution, needs-cherry-pick-1.0, needs-update-release-note, priority/normal, status/LGT1, type/feature

#578 .*/: fix dm unit tests and integration tests
  dm/master/scheduler/scheduler_test.go
  loader/loader.go
  pkg/ha/keepalive_test.go
  pkg/metricsproxy/countervec.go
  pkg/metricsproxy/gaugevec.go
  pkg/metricsproxy/histogramvec.go
  pkg/metricsproxy/summaryvec.go
  pkg/shardddl/optimism/info_test.go
  pkg/shardddl/optimism/table_test.go
  pkg/streamer/reader_test.go
  tests/_dmctl_tools/check_master_online.go
  tests/_dmctl_tools/check_worker_online.go
  tests/dm_syncer/run.sh
  tests/initial_unit/run.sh
  tests/relay_interrupt/run.sh
  tests/start_task/run.sh
Labels: priority/normal, status/LGT2

#580 *: add show-ddl-locks support for optimistic mode
  dm/master/server.go
  dm/master/shardddl/optimist.go
  dm/master/shardddl/optimist_test.go
  dm/master/shardddl/pessimist.go
  dm/master/shardddl/pessimist_test.go
  dm/pb/dmmaster.pb.go
  dm/proto/dmmaster.proto
Labels: needs-update-docs, priority/normal, status/LGT2, type/enhancement

#542 syncer: handle connetion refused error
  pkg/binlog/common/replication.go
  pkg/binlog/reader/file.go
  relay/reader/reader.go
  relay/relay.go
  syncer/streamer_controller.go
  syncer/streamer_controller_test.go
  syncer/syncer.go
Labels: priority/normal, status/LGT2, type/bug-fix

#581 tests/: add ha integration test cases
  dm/master/server.go
  tests/_utils/env_variables
  tests/ha_cases/conf/diff-standalone-config.toml
  tests/ha_cases/conf/diff_config.toml
  tests/ha_cases/conf/diff_config_multi_task.toml
  tests/ha_cases/conf/dm-master-join1.toml
  tests/ha_cases/conf/dm-master-join2.toml
  tests/ha_cases/conf/dm-master-join3.toml
  tests/ha_cases/conf/dm-master-join4.toml
  tests/ha_cases/conf/dm-master-join5.toml
  tests/ha_cases/conf/dm-master1.toml
  tests/ha_cases/conf/dm-master2.toml
  tests/ha_cases/conf/dm-master3.toml
  tests/ha_cases/conf/dm-task.yaml
  tests/ha_cases/conf/dm-task2.yaml
  tests/ha_cases/conf/dm-worker1.toml
  tests/ha_cases/conf/dm-worker2.toml
  tests/ha_cases/conf/dm-worker3.toml
  tests/ha_cases/conf/dm-worker4.toml
  tests/ha_cases/conf/dm-worker5.toml
  tests/ha_cases/conf/source1.toml
  tests/ha_cases/conf/source2.toml
  tests/ha_cases/conf/standalone-task.yaml
  tests/ha_cases/data/db1.increment.sql
  tests/ha_cases/data/db1.increment2.sql
  tests/ha_cases/data/db1.prepare.sql
  tests/ha_cases/data/db2.increment.sql
  tests/ha_cases/data/db2.increment2.sql
  tests/ha_cases/data/db2.prepare.sql
  tests/ha_cases/lib.sh
  tests/ha_cases/run.sh
  tests/others_integration.txt
Labels: priority/normal, status/LGT2, type/test

#590 syncer: add more metrics; refine batch handle
  dm/dm-ansible/scripts/dm.json
  loader/db.go
  loader/metrics.go
  pkg/conn/baseconn.go
  pkg/conn/baseconn_test.go
  pkg/conn/basedb_test.go
  relay/metrics.go
  syncer/db.go
  syncer/error_test.go
  syncer/metrics.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: priority/normal, status/WIP, type/enhancement

#593 *: extract ha_cases from others_integration.txt
  tests/others_integration.txt
  tests/run.sh
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, type/test

#594 syncer: improve performance
  dm/config/task.go
  dm/dm-ansible/scripts/dm.json
  loader/metrics.go
  relay/metrics.go
  syncer/dml.go
  syncer/dml_test.go
  syncer/metrics.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: priority/normal, status/LGT2, type/enhancement

#598 fix(*): add line break in command error output
  cmd/dm-ctl/main.go
  cmd/dm-master/main.go
  cmd/dm-syncer/main.go
  cmd/dm-tracer/main.go
  cmd/dm-worker/main.go
  debug-tools/binlog-event-blackhole/main.go
Labels: contribution, status/LGT1

#597 syncer: improve performance - part 2
  dm/config/subtask.go
  dm/config/task.go
  dm/dm-ansible/scripts/dm.json
  syncer/checkpoint.go
  syncer/dml.go
  syncer/metrics.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: needs-update-docs, priority/important, status/LGT2, type/enhancement

#611 *: extract ha_cases from others_integration.txt (#593)
  tests/run.sh
Labels: priority/normal, status/PTAL, type/test

#609 *: fix metrics
  dm/dm-ansible/scripts/dm.json
  relay/metrics.go
Labels: priority/unimportant, status/LGT2, type/bug-fix

#606 *: improve performance
  dm/config/subtask.go
  dm/config/task.go
  dm/dm-ansible/scripts/dm.json
  loader/db.go
  loader/metrics.go
  pkg/conn/baseconn.go
  pkg/conn/baseconn_test.go
  pkg/conn/basedb_test.go
  relay/metrics.go
  syncer/checkpoint.go
  syncer/db.go
  syncer/dml.go
  syncer/dml_test.go
  syncer/error_test.go
  syncer/metrics.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: needs-update-docs, needs-update-release-note, priority/normal, status/LGT2, type/enhancement

#616 cherry-pick #575 and #578 to release-1.0 and resolve conflicts
  dm/worker/metrics.go
  dm/worker/subtask.go
  loader/loader.go
  loader/metrics.go
  mydumper/metrics.go
  mydumper/mydumper.go
  pkg/conn/baseconn.go
  pkg/conn/baseconn_test.go
  pkg/metricsproxy/countervec.go
  pkg/metricsproxy/countervec_test.go
  pkg/metricsproxy/gaugevec.go
  pkg/metricsproxy/gaugevec_test.go
  pkg/metricsproxy/histogramvec.go
  pkg/metricsproxy/histogramvec_test.go
  pkg/metricsproxy/proxy.go
  pkg/metricsproxy/proxy_test.go
  pkg/metricsproxy/summaryvec.go
  pkg/metricsproxy/summaryvec_test.go
  pkg/streamer/reader_test.go
  relay/metrics.go
  syncer/metrics.go
  syncer/syncer.go
  tests/_dmctl_tools/check_master_online.go
  tests/_dmctl_tools/check_worker_online.go
  tests/initial_unit/run.sh
  tests/relay_interrupt/run.sh
  tests/start_task/run.sh
Labels: needs-update-release-note, priority/normal, status/LGT1, type/cherry-pick

#589 worker/: fix worker stuck in unitTransWaitCondition
  dm/worker/relay.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, type/bug-fix

#587 syncer/: fix flush checkpoint for ddls for situations that IsSharding is false
  dm/worker/subtask.go
  syncer/job.go
  syncer/job_test.go
  syncer/optimist.go
  syncer/syncer.go
  syncer/syncer_test.go
  syncer/util.go
  syncer/util_test.go
  tests/ha_cases/data/db2.increment.sql
  tests/ha_cases/run.sh
  tests/sharding2/data/db1.increment2.sql
  tests/sharding2/data/db1.increment3.sql
  tests/sharding2/data/db2.increment2.sql
  tests/sharding2/data/db2.increment3.sql
  tests/sharding2/run.sh
Labels: needs-cherry-pick-1.0, priority/important, status/LGT2, type/bug-fix

#614 syncer: minor fix on location
  pkg/binlog/position.go
  pkg/binlog/position_test.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/sharding-meta/shardmeta.go
  syncer/sharding-meta/shardmeta_test.go
  syncer/sharding_group.go
  syncer/sharding_group_test.go
  syncer/syncer.go
  tests/sharding/data/db1.increment.sql
Labels: status/LGT2, type/bug-fix

#622 worker/: fix worker stuck in unitTransWaitCondition(#589)
  dm/worker/relay.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
Labels: needs-update-release-note, priority/normal, status/LGT2, type/bug-fix, type/cherry-pick

#621 shardddl: add test cases for two scenarios
  dm/master/shardddl/optimist_test.go
  dm/master/shardddl/pessimist_test.go
  pkg/ha/bound_test.go
  pkg/ha/stage_test.go
  pkg/shardddl/optimism/lock_test.go
  pkg/shardddl/optimism/operation_test.go
Labels: needs-update-docs, priority/unimportant, status/LGT2, type/qa

#630 master,ansible:minor suggestion for help message
  dm/dm-ansible/scripts/dm.json
  dm/master/config.go
  dm/master/dm-master.toml
Labels: priority/unimportant, status/LGT1

#631 go.mod/: update dumpling and tidb-tools
  go.mod
  go.sum
Labels: dependencies, priority/normal, status/LGT2

#632 *: update go mod
  go.mod
  go.sum
  syncer/heartbeat_test.go
Labels: needs-update-release-note, priority/normal, status/LGT2, type/dependencies

#624 syncer/: fix flush checkpoint for ddls for situations that IsSharding is false(#587)
  dm/master/status_test.go
  syncer/job.go
  syncer/job_test.go
  syncer/syncer.go
  syncer/syncer_test.go
  syncer/util.go
  syncer/util_test.go
  tests/sequence_sharding/data/db1.increment.sql
  tests/sequence_sharding/data/db1.increment2.sql
  tests/sequence_sharding/data/db2.increment.sql
  tests/sequence_sharding/data/db2.increment2.sql
  tests/sequence_sharding/run.sh
Labels: priority/normal, status/LGT1, type/bug-fix, type/cherry-pick

#636 CHANGELOG: add release notes for v1.0.5
  CHANGELOG.md
Labels: needs-cherry-pick-1.0, needs-update-dm-ansible, needs-update-docs, priority/important, status/LGT2, type/CHANGELOG

#639 ansible: release v1.0.5
  dm/dm-ansible/inventory.ini
Labels: needs-update-release-note, priority/normal, status/LGT2, type/dm-ansible

#640 fix wrong port
  tests/_utils/run_sql_file
Labels: needs-cherry-pick-1.0, status/LGT2, type/bug-fix

#615 *: fix remove optimistic shard DDL lock after all tables done the operation
  dm/master/shardddl/optimist.go
  dm/master/shardddl/optimist_test.go
  pkg/shardddl/optimism/lock.go
  pkg/shardddl/optimism/lock_test.go
Labels: needs-update-release-note, priority/normal, status/LGT2, type/bug-fix

#625 *: rollback schema in the tracker; fix save table checkpoint in optimistic mode
  _utils/terror_gen/errors_release.txt
  cmd/dm-master/main_test.go
  cmd/dm-syncer/main_test.go
  cmd/dm-tracer/main_test.go
  cmd/dm-worker/main_test.go
  dm/master/scheduler/scheduler_test.go
  dm/master/shardddl/pessimist.go
  pkg/schema/tracker_test.go
  pkg/terror/error_list.go
  syncer/checkpoint.go
  syncer/optimist.go
  syncer/syncer.go
  syncer/test_injector.go
  tests/incremental_mode/conf/source1.toml
  tests/incremental_mode/run.sh
  tests/sequence_sharding_optimistic/conf/source1.toml
  tests/sequence_sharding_optimistic/run.sh
  tests/sharding/conf/source1.toml
  tests/sharding/data/db1.increment.sql
  tests/sharding/data/db2.increment.sql
  tests/sharding/data/db2.prepare.sql
  tests/sharding/run.sh
Labels: priority/normal, status/LGT1, type/bug-fix

#635 sync unit: disable retry for binlog syncer
  pkg/binlog/common/replication.go
  relay/relay.go
  syncer/syncer.go
Labels: status/LGT2, type/bug-fix

#643 pkg/shardddl: make optimistic shard ddl able to handle `MODIFY COLUMN` from `INT` to `BIGINT`
  go.mod
  go.sum
  pkg/shardddl/optimism/lock_test.go
Labels: needs-update-release-note, priority/normal, status/LGT2, type/dependencies

#604 support to handle database's DDLs and fix multiple target tables exist for one task in optimistic mode
  dm/master/shardddl/optimist.go
  dm/master/shardddl/optimist_test.go
  pkg/shardddl/optimism/keeper.go
  pkg/shardddl/optimism/keeper_test.go
  pkg/shardddl/optimism/lock.go
  pkg/shardddl/optimism/lock_test.go
  pkg/shardddl/optimism/ops_test.go
  pkg/shardddl/optimism/table.go
  pkg/shardddl/optimism/table_test.go
  syncer/optimist.go
  syncer/shardddl/optimist.go
  syncer/shardddl/optimist_test.go
  syncer/syncer.go
  tests/sequence_sharding_optimistic/conf/dm-task.yaml
  tests/sequence_sharding_optimistic/data/db1.increment.sql
  tests/sequence_sharding_optimistic/data/db1.increment0.sql
  tests/sequence_sharding_optimistic/run.sh
Labels: needs-update-release-note, priority/important, status/LGT2, type/bug-fix, type/compatibility

#644 .*: fix bug that after execute pause-task the task may still running
  _utils/terror_gen/errors_release.txt
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/unit/unit.go
  dm/unit/unit_test.go
  dm/worker/subtask.go
  loader/loader.go
  pkg/terror/error_list.go
  syncer/syncer.go
  tests/sharding/run.sh
Labels: status/LGT2, type/bug-fix
