Repository pingcap/dm, pull requests merged in 2020-12, with the labels that each got.

#1284 Quality reinforcement (7): fix unstable test cases
  pkg/schema/tracker.go
  tests/_utils/run_sql_file_online_ddl
  tests/_utils/shardddl_lib.sh
  tests/handle_error/conf/double-source-no-sharding.yaml
  tests/handle_error/conf/double-source-optimistic.yaml
  tests/handle_error/conf/double-source-pessimistic.yaml
  tests/handle_error/conf/single-source-no-sharding.yaml
  tests/handle_error/lib.sh
  tests/handle_error/run.sh
  tests/sequence_sharding/run.sh
  tests/shardddl1/conf/double-source-optimistic.yaml
  tests/shardddl1/conf/double-source-pessimistic.yaml
  tests/shardddl1/conf/single-source-no-routes.yaml
  tests/shardddl1/conf/single-source-no-sharding.yaml
  tests/shardddl1/conf/single-source-optimistic.yaml
  tests/shardddl1/conf/single-source-pessimistic.yaml
  tests/shardddl1/run.sh
  tests/shardddl2/conf/double-source-optimistic.yaml
  tests/shardddl2/conf/double-source-pessimistic.yaml
  tests/shardddl2/run.sh
  tests/shardddl3/conf/double-source-optimistic.yaml
  tests/shardddl3/conf/double-source-pessimistic.yaml
  tests/shardddl3/conf/single-source-optimistic.yaml
  tests/shardddl3/conf/single-source-pessimistic.yaml
  tests/shardddl3/run.sh
Labels: status/LGT1, type/test

#1325 chaos: Update io-chaos-dm.yaml
  chaos/manifests/io-chaos-dm.yaml
Labels: priority/unimportant, status/LGT1

#1321 load: load should not need metadata
  _utils/terror_gen/errors_release.txt
  errors.toml
  loader/loader.go
  pkg/dumpling/utils.go
  pkg/dumpling/utils_test.go
  pkg/terror/error_list.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, type/bug-fix

#1329 bug-fix: fix currentLocation not increase in rows event
  syncer/syncer.go
Labels: needs-cherry-pick-2.0, priority/important, status/LGT1, type/bug-fix

#1331 *: add test for #1329 and add VIEW & EVENT in builtin filter
  pkg/utils/util.go
  syncer/filter_test.go
  syncer/syncer_test.go
  tests/others_integration.txt
  tests/safe_mode/data/db2.increment.sql
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, type/bug-fix

#1335 bug-fix: no need to check gtid of Mariadb
  _utils/terror_gen/errors_release.txt
  dm/config/source_config.go
  errors.toml
  pkg/dumpling/utils_test.go
  pkg/terror/error_list.go
  syncer/ddl.go
  tests/handle_error/run.sh
  tests/sharding/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, priority/normal, status/LGT2, type/bug-fix

#1340 parser: split ALTER TABLE ADD COLUMN
  pkg/parser/common.go
  pkg/parser/common_test.go
  tests/sequence_safe_mode/data/db1.increment.sql
  tests/sequence_safe_mode/data/db2.increment.sql
Labels: needs-cherry-pick-2.0, needs-update-release-note, priority/normal, status/LGT1

#1346 utils: filter out EVENT
  pkg/utils/util.go
  syncer/filter_test.go
Labels: needs-update-release-note, status/LGT2

#1333 dmctl: support and sync mutiple endpoints
  cmd/dm-ctl/main.go
  dm/ctl/common/config.go
  dm/ctl/common/operate_relay.go
  dm/ctl/common/operate_task.go
  dm/ctl/common/util.go
  dm/ctl/master/check_task.go
  dm/ctl/master/get_config.go
  dm/ctl/master/handle_error.go
  dm/ctl/master/list_member.go
  dm/ctl/master/offline_member.go
  dm/ctl/master/operate_leader.go
  dm/ctl/master/operate_schema.go
  dm/ctl/master/operate_source.go
  dm/ctl/master/purge_relay.go
  dm/ctl/master/query_status.go
  dm/ctl/master/show_ddl_locks.go
  dm/ctl/master/start_task.go
  dm/ctl/master/unlock_ddl_lock.go
  dm/ctl/master/update_task.go
  tests/dmctl_basic/check_list/dmctl.sh
  tests/dmctl_basic/run.sh
  tests/dmctl_command/run.sh
  tests/ha_cases/run.sh
Labels: needs-cherry-pick-2.0, needs-update-docs, priority/normal, status/LGT2

#1350 chaos: fix diffIncrData has no effect
  chaos/cases/config.go
  chaos/cases/diff.go
  chaos/cases/task.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, type/test

#1355 test: fix upgrade tidb via tiup
  .github/workflows/upgrade-via-tiup.yml
Labels: needs-cherry-pick-2.0, status/LGT1, type/test

#1360 ansible: update the version for DM-Ansible
  dm/dm-ansible/inventory.ini
Labels: status/LGT1

#1358 purge-relay: update purge relay command args
  dm/ctl/master/purge_relay.go
  tests/dmctl_basic/check_list/purge_relay.sh
Labels: needs-cherry-pick-2.0, needs-update-docs, status/LGT1

#1359 CHANGELOG: add v2.0.1 release note
  CHANGELOG.md
Labels: needs-cherry-pick-2.0, needs-update-docs, status/LGT2

#1356 dep: update for release
  dumpling/dumpling.go
  dumpling/util.go
  go.mod
  go.sum
Labels: needs-cherry-pick-2.0, status/LGT1, type/dependencies
