Repository pingcap/dm, pull requests merged in 2020-03, with the labels that each got.

#498 election: output the leader's information
  dm/master/election.go
  dm/master/server.go
  pkg/election/election.go
  pkg/election/election_test.go
  tests/_utils/env_variables
  tests/ha/conf/dm-master4.toml
  tests/ha/conf/dm-master5.toml
  tests/ha/run.sh
Labels: status/LGT1, type/bug-fix

#499 dm/master, dm/worker: handle etcd retryable errors for watcher
  _utils/terror_gen/errors_release.txt
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  pkg/etcdutil/etcdutil.go
  pkg/etcdutil/etcdutil_test.go
  pkg/ha/bound.go
  pkg/ha/bound_test.go
  pkg/ha/ops_test.go
  pkg/ha/source.go
  pkg/ha/source_test.go
  pkg/ha/stage.go
  pkg/ha/stage_test.go
  pkg/ha/subtask.go
  pkg/ha/subtask_test.go
  pkg/terror/error_list.go
Labels: priority/normal, status/LGT2

#510 .*/: fix invalid relay dir output, delete Error Type for status
  _utils/terror_gen/errors_release.txt
  checker/checker.go
  checker/cmd.go
  dm/ctl/master/query_status_test.go
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/unit/unit.go
  dm/worker/relay_test.go
  dm/worker/server.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  dm/worker/task_checker.go
  dm/worker/task_checker_test.go
  loader/loader.go
  mydumper/mydumper.go
  pkg/terror/error_list.go
  relay/relay.go
  syncer/mode.go
  syncer/relay.go
  syncer/syncer.go
  tests/relay_interrupt/run.sh
Labels: priority/normal, status/LGT1

#512 dm-worker/: refine query error
  dm/worker/server_test.go
  dm/worker/status.go
  dm/worker/worker.go
Labels: status/LGT2

#513 dm-master: fix DM-master can not exit when starting timeout
  dm/master/etcd.go
  dm/master/etcd_test.go
  dm/master/server.go
Labels: priority/normal, status/LGT2, type/bug-fix

#515 go.mod: update tidb-tools dependency to v3.0.11
  go.mod
  go.sum
Labels: priority/normal, status/LGT2

#523 dm-ctl/: add `--more` index for `query-status` command to get full task information
  dm/ctl/master/query_status.go
Labels: contribution, needs-cherry-pick-1.0, priority/normal, status/LGT1

#497 update dm-ansible, support ha
  dm/dm-ansible/group_vars/dm_master_servers.yml
  dm/dm-ansible/group_vars/dm_worker_servers.yml
  dm/dm-ansible/inventory.ini
  dm/dm-ansible/roles/check_config_static/tasks/main.yml
  dm/dm-ansible/roles/dm-master/defaults/main.yml
  dm/dm-ansible/roles/dm-master/tasks/binary_deployment.yml
  dm/dm-ansible/roles/dm-master/tasks/main.yml
  dm/dm-ansible/roles/dm-master/templates/dm-master.toml.j2
  dm/dm-ansible/roles/dm-master/templates/run_dm-master.sh.j2
  dm/dm-ansible/roles/dm-worker/defaults/main.yml
  dm/dm-ansible/roles/dm-worker/tasks/binary_deployment.yml
  dm/dm-ansible/roles/dm-worker/tasks/main.yml
  dm/dm-ansible/roles/dm-worker/templates/dm-worker.toml.j2
  dm/dm-ansible/roles/dm-worker/templates/run_dm-worker.sh.j2
  dm/dm-ansible/roles/download/templates/packages.yml.j2
  dm/dm-ansible/roles/grafana/defaults/main.yml
  dm/dm-ansible/roles/grafana/tasks/binary_deployment.yml
  dm/dm-ansible/rolling_update.yml
  dm/dm-ansible/scripts/dm.json
  dm/dm-ansible/scripts/dm_instances.json
  dm/dm-ansible/scripts/import_grafana_dashboards.py
  dm/dm-ansible/start.yml
Labels: status/LGT2, type/dm-ansible

#521 binlog replication: support GTID
  _utils/terror_gen/errors_release.txt
  dm/config/task.go
  dm/master/server_test.go
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/worker/server.go
  loader/loader.go
  pkg/binlog/position.go
  pkg/binlog/position_test.go
  pkg/gtid/gtid.go
  pkg/gtid/gtid_test.go
  pkg/terror/error_list.go
  pkg/utils/mydumper.go
  pkg/utils/mydumper_test.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/inject_sql.go
  syncer/job.go
  syncer/job_test.go
  syncer/operator.go
  syncer/relay.go
  syncer/sharding-meta/shardmeta.go
  syncer/sharding-meta/shardmeta_test.go
  syncer/sharding_group.go
  syncer/sharding_group_test.go
  syncer/status.go
  syncer/streamer_controller.go
  syncer/syncer.go
  syncer/syncer_test.go
  syncer/warning.go
  tests/_utils/check_sync_diff
  tests/ha/conf/source1.toml
  tests/ha_master/conf/source1.toml
  tests/http_apis/conf/source1.toml
  tests/incremental_mode/conf/dm-task.yaml
  tests/incremental_mode/conf/source1.toml
  tests/incremental_mode/run.sh
  tests/online_ddl/conf/source1.toml
  tests/safe_mode/conf/source1.toml
  tests/sequence_safe_mode/conf/source1.toml
  tests/sequence_sharding/conf/source1.toml
  tests/sequence_sharding/run.sh
  tests/sharding/conf/source1.toml
  tests/start_task/conf/source1.toml
Labels: priority/important, status/LGT2, type/feature

#518 .*/: handle etcd retryable error when using etcd client's `Get with revision`
  _utils/terror_gen/errors_release.txt
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
  dm/master/server_test.go
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/worker.go
  pkg/etcdutil/etcdutil.go
  pkg/ha/bound.go
  pkg/ha/bound_test.go
  pkg/ha/ops.go
  pkg/ha/ops_test.go
  pkg/ha/source.go
  pkg/ha/source_test.go
  pkg/ha/stage.go
  pkg/ha/stage_test.go
  pkg/ha/subtask.go
  pkg/ha/worker.go
  pkg/terror/error_list.go
Labels: priority/normal, status/LGT2

#522 HA: refactor unlock-ddl-lock and break-ddl-lock
  dm/ctl/ctl.go
  dm/ctl/master/break_ddl_lock.go
  dm/ctl/master/unlock_ddl_lock.go
  dm/master/election.go
  dm/master/server.go
  dm/master/shardddl/pessimist.go
  dm/master/shardddl/pessimist_test.go
  dm/master/workerrpc/interface.go
  dm/pb/dmmaster.pb.go
  dm/pbmock/dmmaster.go
  dm/proto/dmmaster.proto
  pkg/shardddl/pessimism/info.go
  pkg/shardddl/pessimism/lock.go
  pkg/shardddl/pessimism/lock_test.go
  pkg/shardddl/pessimism/operation.go
  pkg/shardddl/pessimism/ops.go
  pkg/shardddl/pessimism/ops_test.go
  syncer/shardddl/pessimist.go
  syncer/shardddl/pessimist_test.go
  syncer/syncer.go
  tests/dmctl_advance/check_list/break_ddl_lock.sh
  tests/dmctl_advance/check_list/unlock_ddl_lock.sh
  tests/dmctl_advance/run.sh
  tests/dmctl_command/run.sh
Labels: priority/normal, status/LGT1, type/enhancement

#519 dm-worker/: refine query error(#512)
  dm/worker/server_test.go
  dm/worker/status.go
  pkg/utils/string.go
Labels: status/LGT2, type/cherry-pick

#529 election: reset oldLeaderID after retire from leader
  pkg/election/election.go
Labels: priority/important, status/LGT2, type/bug-fix

#530 *: support recover relay log file with a subset of metadata
  _utils/terror_gen/errors_release.txt
  go.mod
  go.sum
  pkg/binlog/event/common.go
  pkg/binlog/event/common_test.go
  pkg/binlog/event/event.go
  pkg/binlog/event/event_test.go
  pkg/binlog/event/generator_test.go
  pkg/binlog/event/helper.go
  pkg/binlog/event/helper_test.go
  pkg/terror/error_list.go
  relay/relay.go
  relay/relay_test.go
  relay/writer/file_util.go
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, type/bug-fix

#533 dm-ctl/: add `--more` index for `query-status` command to get full task information(#523)
  dm/ctl/master/query_status.go
Labels: status/LGT2, type/cherry-pick

#534 *: support recover relay log file with a subset of metadata (#530)
  _utils/terror_gen/errors_release.txt
  go.mod
  go.sum
  pkg/binlog/event/common.go
  pkg/binlog/event/common_test.go
  pkg/binlog/event/event.go
  pkg/binlog/event/event_test.go
  pkg/binlog/event/generator_test.go
  pkg/binlog/event/helper.go
  pkg/binlog/event/helper_test.go
  pkg/terror/error_list.go
  relay/relay.go
  relay/relay_test.go
  relay/writer/file_util.go
Labels: priority/normal, status/LGT2, type/bug-fix, type/cherry-pick

#535 ansible: release v1.0.4
  dm/dm-ansible/inventory.ini
Labels: status/LGT1, type/dm-ansible

#537 utils: fix `value out of range` for getting `server_id`
  pkg/utils/db.go
  pkg/utils/db_test.go
Labels: needs-cherry-pick-1.0, needs-update-release-note, priority/normal, status/PTAL, type/bug-fix

#539 CHANGELOG: add release notes for v1.0.4
  CHANGELOG.md
Labels: needs-update-dm-ansible, needs-update-docs, priority/important, status/LGT1, type/CHANGELOG

#547 portal: update go file generated by statik
  Makefile
  dm/portal/statik/statik.go
  tools.json
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2

#549 portal: update go file generated by statik(#547)
  Makefile
  dm/portal/statik/statik.go
Labels: status/LGT2, type/cherry-pick

#546 feat: replace errors.ErrorStack to terror.Message
  dm/ctl/master/query_error.go
  dm/ctl/master/query_status.go
  dm/unit/unit.go
Labels: contribution, priority/normal, status/LGT1, type/enhancement

#528 pkg/: add retry for etcd put/delete operation
  pkg/etcdutil/etcdutil.go
  pkg/ha/bound.go
  pkg/ha/ops.go
  pkg/ha/source.go
  pkg/ha/stage.go
  pkg/ha/subtask.go
  pkg/ha/worker.go
  pkg/shardddl/pessimism/operation.go
  pkg/shardddl/pessimism/ops.go
Labels: priority/normal, status/LGT2

#552 loader: fix concurrent usage of checkpoint's DBconn.
  loader/checkpoint.go
  loader/loader.go
Labels: needs-cherry-pick-1.0, needs-update-release-note, priority/normal, status/LGT2, type/bug-fix

#540 dump/: integrate dumpling
  dm/config/task.go
  dm/master/etcd_test.go
  dm/master/server_test.go
  dm/worker/metrics.go
  dm/worker/server_test.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  dm/worker/worker_test.go
  dumpling/dumpling.go
  dumpling/metrics.go
  dumpling/util.go
  dumpling/util_test.go
  go.mod
  go.sum
  pkg/election/election_test.go
  pkg/schema/tracker.go
  syncer/heartbeat_test.go
  tests/all_mode/data/db1.increment.sql
  tests/ha/data/db1.increment.sql
  tests/ha_master/data/db1.increment.sql
  tests/http_apis/conf/dm-task.yaml
  tests/import_goroutine_leak/conf/dm-task.yaml
  tests/initial_unit/conf/dm-task.yaml
  tests/load_interrupt/conf/dm-task.yaml
  tests/load_interrupt/run.sh
  tests/print_status/conf/dm-task.yaml
  tests/print_status/run.sh
  tests/relay_interrupt/conf/dm-task.yaml
  tests/start_task/conf/dm-task.yaml
Labels: priority/normal, status/LGT2

#557 ansible: update `dm_version` to `v1.0.4-hotfix`
  dm/dm-ansible/inventory.ini
Labels: status/LGT2, type/dm-ansible

#556 dumpling/: update dumpling dependency
  dm/master/scheduler/scheduler_test.go
  go.mod
  go.sum
Labels: priority/normal, status/LGT2

#559 worker/: don't quit worker immediately when dialed master is offline
  cmd/dm-worker/main.go
  dm/master/scheduler/scheduler_test.go
  dm/worker/join.go
  tests/ha_master/run.sh
Labels: priority/normal, status/LGT2, type/bug-fix

#548 pkg/keepalive: revoke lease if we quit normally
  dm/worker/server_test.go
  pkg/etcdutil/etcdutil.go
  pkg/ha/keepalive.go
  pkg/ha/keepalive_test.go
Labels: priority/normal, status/LGT2, type/enhancement

#558 fix: reset some metrics when loader resume
  dm/dm-ansible/scripts/dm.json
  loader/loader.go
  loader/metrics.go
Labels: contribution, needs-cherry-pick-1.0, priority/normal, status/LGT1, type/bug-fix

#563 ha: set etcdClient to component at the beginning initialization
  _utils/terror_gen/errors_release.txt
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
  dm/master/shardddl/pessimist.go
  dm/master/shardddl/pessimist_test.go
  pkg/terror/error_list.go
Labels: priority/normal, status/LGT2, type/bug-fix
