Repository pingcap/dm, pull requests merged in 2020-09, with the labels that each got.

#967 master: fix panic when etcd member not started
  dm/master/server.go
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, priority/unimportant, status/LGT2

#969 ansible: update dm_version to v2.0.0-rc.2
  dm/dm-ansible/inventory.ini
Labels: priority/normal, status/PTAL, type/dm-ansible

#972 CHANGELOG: add 2.0.0-rc.2 release notes
  CHANGELOG.md
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, status/PTAL, type/CHANGELOG

#968 dep: update tidb (fix print massive log) and parser
  go.mod
  go.sum
  syncer/syncer.go
  tests/handle_error/lib.sh
  tests/handle_error/run.sh
Labels: dependencies, needs-cherry-pick-2.0, needs-update-release-note, priority/unimportant, status/DNM, status/LGT1

#977 task_checker: don't auto-resume for wrong datetime value
  pkg/retry/errors.go
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2, type/bug-fix

#915 *: use dumpling's finish building connection location to leave safe mode
  dm/config/task.go
  dumpling/dumpling.go
  go.mod
  go.sum
  loader/loader.go
  pkg/dumpling/utils.go
  pkg/dumpling/utils_test.go
  pkg/utils/mydumper.go
  pkg/utils/mydumper_test.go
  syncer/checkpoint.go
  syncer/mode.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/safe_mode/run.sh
Labels: needs-cherry-pick-2.0, needs-update-docs, needs-update-release-note, priority/normal, status/LGT2

#981 *: use dumpling's finish building connection location to leave safe mode #915
  dm/config/task.go
  dumpling/dumpling.go
  go.mod
  go.sum
  loader/loader.go
  pkg/dumpling/utils.go
  pkg/dumpling/utils_test.go
  pkg/utils/mydumper.go
  pkg/utils/mydumper_test.go
  syncer/checkpoint.go
  syncer/mode.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/safe_mode/run.sh
Labels: priority/normal, status/LGT1, type/cherry-pick

#982 dependency: update TiDB and integration test
  go.mod
  go.sum
  syncer/syncer.go
  tests/handle_error/lib.sh
  tests/handle_error/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1

#983 config: fix `binlog-gtid` verify
  _utils/terror_gen/errors_release.txt
  dm/config/task.go
  dm/config/task_test.go
  errors.toml
  pkg/terror/error_list.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, status/PTAL, type/bug-fix

#985 syncer: table no need exist when drop
  syncer/syncer.go
  tests/all_mode/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, status/PTAL, type/bug-fix

#980 loader: support percent escape in dump files
  loader/loader.go
  tests/_utils/test_prepare
  tests/full_mode/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, type/feature

#992 log: support change the level of etcd for debugging
  dm/master/config.go
  dm/master/etcd_test.go
  dm/master/server.go
Labels: needs-cherry-pick-2.0, status/LGT2, type/feature

#994 relay: fix invalid flavor after restart dm-master
  dm/worker/server.go
  dm/worker/worker.go
Labels: needs-cherry-pick-2.0, status/LGT1, type/bug-fix

#959 Quality reinforcement(2): fix unstable test cases
  dm/worker/worker_test.go
  pkg/utils/string.go
  tests/ha_cases/run.sh
  tests/incremental_mode/conf/source2.yaml
  tests/sequence_sharding_optimistic/conf/source2.yaml
  tests/sequence_sharding_removemeta/run.sh
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, type/bug-fix

#889 *: auto discover ANSI_QUOTES
  checker/check_test.go
  checker/checker.go
  checker/cmd.go
  dm/config/subtask.go
  dm/config/task.go
  dm/config/task_test.go
  dm/master/server.go
  dm/master/server_test.go
  dumpling/dumpling.go
  go.mod
  go.sum
  loader/convert_data.go
  loader/convert_data_test.go
  loader/loader.go
  pkg/binlog/event/util.go
  pkg/binlog/reader/tcp_test.go
  pkg/binlog/reader/util.go
  pkg/binlog/reader/util_test.go
  pkg/parser/common.go
  pkg/utils/db.go
  pkg/v1dbschema/schema.go
  relay/relay.go
  syncer/db.go
  syncer/ddl_test.go
  syncer/error.go
  syncer/handle_error.go
  syncer/schema.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/relay_interrupt/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, type/feature

#1005 *: auto discover ANSI_QUOTES #889
  checker/check_test.go
  checker/checker.go
  checker/cmd.go
  dm/config/subtask.go
  dm/config/task.go
  dm/config/task_test.go
  dm/master/server.go
  dm/master/server_test.go
  dumpling/dumpling.go
  go.mod
  go.sum
  loader/convert_data.go
  loader/convert_data_test.go
  loader/loader.go
  pkg/binlog/event/util.go
  pkg/binlog/reader/tcp_test.go
  pkg/binlog/reader/util.go
  pkg/binlog/reader/util_test.go
  pkg/parser/common.go
  pkg/utils/db.go
  pkg/v1dbschema/schema.go
  relay/relay.go
  syncer/db.go
  syncer/ddl_test.go
  syncer/error.go
  syncer/handle_error.go
  syncer/schema.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/relay_interrupt/run.sh
Labels: status/LGT2, type/cherry-pick

#1004 master: extract common logic to a function
  dm/master/server.go
  dm/pb/hide_password.go
  pkg/utils/util.go
Labels: priority/normal, status/LGT2, type/enhancement

#1011 test: improve common unit test coverage to 81.2%
  dm/common/common_test.go
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2

#1012 dep: update dumpling to fix null string error
  go.mod
  go.sum
  tests/print_status/run.sh
Labels: dependencies, needs-cherry-pick-2.0, priority/unimportant, status/LGT2, type/bug-fix

#1010 test: improve coverage to 71.4% for pkg/conn
  pkg/conn/baseconn_test.go
  pkg/conn/basedb_test.go
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT1

#1002 test: improve unit test coverage of checker
  _utils/terror_gen/errors_release.txt
  checker/check_test.go
  errors.toml
  pkg/terror/error_list.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1

#988 *: save exitSafeModeLoc in checkpoint, load it, upgrade strategy
  _utils/terror_gen/errors_release.txt
  dm/config/task.go
  dm/master/bootstrap.go
  dm/master/scheduler/scheduler.go
  errors.toml
  loader/loader.go
  pkg/dumpling/utils.go
  pkg/terror/error_list.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  pkg/upgrade/version.go
  pkg/utils/util.go
  pkg/v1dbschema/schema.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/mode.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/import_v10x/run.sh
Labels: needs-cherry-pick-2.0, needs-update-docs, needs-update-release-note, status/LGT2, type/feature

#1001 test: improve coverage to 73.4% for dm/config
  dm/config/task_test.go
Labels: priority/unimportant, status/LGT2

#1019 test: improve unit and binlog.common unit test coverage to 100%
  dm/unit/unit_test.go
  pkg/binlog/common/replication_test.go
  pkg/binlog/common/stage_test.go
  pkg/log/log_test.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, status/PTAL

#1017 *: save exitSafeModeLoc in checkpoint, load it, upgrade strategy (#988)
  _utils/terror_gen/errors_release.txt
  dm/config/task.go
  dm/master/bootstrap.go
  dm/master/scheduler/scheduler.go
  errors.toml
  loader/loader.go
  pkg/dumpling/utils.go
  pkg/terror/error_list.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  pkg/upgrade/version.go
  pkg/utils/util.go
  pkg/v1dbschema/schema.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/mode.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/import_v10x/run.sh
Labels: priority/normal, status/LGT2, type/cherry-pick

#1020 *: clear some useless code
  dm/ctl/common/util.go
  dm/master/ddl_lock.go
  dm/master/ddl_lock_test.go
  dm/master/lock.go
  dm/master/lock_test.go
  dm/worker/subtask.go
  mydumper/metrics.go
  mydumper/mydumper.go
  mydumper/mydumper_test.go
  mydumper/util.go
  mydumper/util_test.go
  pkg/utils/common.go
  pkg/utils/hash.go
  syncer/syncer.go
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2, status/PTAL, type/enhancement

#1007 Quality reinforcement (3): fix unstable test cases
  dm/master/election_test.go
  dm/master/scheduler/scheduler_test.go
  dm/master/server.go
  dm/master/server_test.go
  dm/master/shardddl/pessimist_test.go
  dm/worker/server_test.go
  dm/worker/subtask_test.go
  pkg/utils/string.go
  tests/dmctl_basic/run.sh
Labels: status/LGT1, status/PTAL

#1027 loader: don't print ERROR log, clean dump file when all finished
  loader/checkpoint.go
  loader/checkpoint_test.go
  loader/loader.go
  tests/import_goroutine_leak/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2

#1008 tls: minor fix on http api
  dm/master/server.go
  tests/_dmctl_tools/check_master_http_apis.go
  tests/tls/run.sh
Labels: status/LGT2, type/bug-fix

#1033 test: improve pkg/etcdutil unit test coverage to 87%
  pkg/etcdutil/etcdutil.go
  pkg/etcdutil/etcdutil_test.go
  syncer/status.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1

#1039 syncer: do not ignore fake rotate event to the next file
  syncer/syncer.go
Labels: needs-cherry-pick-2.0, needs-update-release-note, priority/important, status/LGT2, type/bug-fix

#1040 README: add slack badge
  README.md
Labels: priority/unimportant, status/LGT2

#1042 loader, test: fix bug of clean dump file and update checkpoint
  loader/checkpoint.go
  loader/loader.go
  loader/util.go
  tests/all_mode/run.sh
Labels: priority/normal, status/LGT2, type/bug-fix

#1045 tls: use tls in list-member
  dm/master/server.go
  tests/tls/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, type/bug-fix

#1043 loader: don't print ERROR log, clean dump file when all finished (#1027)
  loader/checkpoint.go
  loader/checkpoint_test.go
  loader/loader.go
  loader/util.go
  tests/all_mode/run.sh
  tests/import_goroutine_leak/run.sh
Labels: priority/normal, status/LGT2, type/cherry-pick

#1035 shardddl: add lock and version for optimistic info
  dm/master/shardddl/optimist.go
  pkg/binlog/reader/util.go
  pkg/conn/basedb.go
  pkg/conn/basedb_test.go
  pkg/shardddl/optimism/info.go
  pkg/shardddl/optimism/info_test.go
  pkg/shardddl/optimism/keeper.go
  pkg/shardddl/optimism/lock.go
  pkg/shardddl/optimism/lock_test.go
  pkg/shardddl/optimism/ops.go
  pkg/shardddl/optimism/ops_test.go
  syncer/shardddl/optimist_test.go
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, status/PTAL, type/bug-fix

#1047 test: improve master/workerrpc unit test coverage to 91%
  dm/master/workerrpc/workerrpc_test.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, status/PTAL

#1049 test: improve coverage of syncer/checkpoint.go to 85.8%
  syncer/checkpoint_test.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2

#1055 ddl: pause subtask when exec ddl err
  syncer/optimist.go
  syncer/syncer.go
  tests/handle_error/run.sh
Labels: priority/normal, status/LGT2, status/PTAL, type/bug-fix

#1061 syncer: remove KEY index in DML concurrency keys
  syncer/dml.go
  syncer/dml_test.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, status/PTAL, type/bug-fix

#1060 test: improve coverage of syncer/error.go to 89.6%
  syncer/error.go
  syncer/error_test.go
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2

#1032 tracker: get some session variables from downtream
  _utils/terror_gen/errors_release.txt
  dm/config/subtask.go
  dm/worker/worker.go
  errors.toml
  loader/status.go
  pkg/conn/basedb.go
  pkg/retry/errors.go
  pkg/schema/tracker.go
  pkg/schema/tracker_test.go
  pkg/terror/error_list.go
  syncer/checkpoint_test.go
  syncer/status.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/sharding/conf/dm-task.yaml
  tests/sharding/run.sh
Labels: needs-cherry-pick-2.0, needs-update-docs, needs-update-release-note, priority/normal, status/LGT2, type/feature

#1067 test: add syncer/handle_error unit test
  syncer/handle_error_test.go
Labels: needs-cherry-pick-2.0, status/LGT2

#1071 tracker: get some session variables from downtream (#1032)
  _utils/terror_gen/errors_release.txt
  dm/config/subtask.go
  dm/worker/worker.go
  errors.toml
  loader/status.go
  pkg/conn/basedb.go
  pkg/retry/errors.go
  pkg/schema/tracker.go
  pkg/schema/tracker_test.go
  pkg/terror/error_list.go
  syncer/checkpoint_test.go
  syncer/status.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/sharding/conf/dm-task.yaml
  tests/sharding/run.sh
Labels: status/LGT1, type/cherry-pick

#930 *: run chaos-mesh operations with GitHub action
  .github/workflows/chaos-mesh.yml
  Makefile
  chaos/cases/conf/source1.yaml
  chaos/cases/conf/source2.yaml
  chaos/cases/conf/task-single.yaml
  chaos/cases/config.go
  chaos/cases/db.go
  chaos/cases/diff.go
  chaos/cases/dml.go
  chaos/cases/main.go
  chaos/cases/member.go
  chaos/cases/schema.go
  chaos/cases/single.go
  chaos/cases/source.go
  chaos/manifests/Dockerfile
  chaos/manifests/cases.yaml
  chaos/manifests/dm-master.yaml
  chaos/manifests/dm-worker.yaml
  chaos/manifests/mysql.yaml
  chaos/manifests/pod-failure-dm.yaml
  chaos/manifests/pod-kill-dm.yaml
  chaos/manifests/tidb.yaml
  go.mod
  go.sum
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, type/qa

#1054 test: refine and improve pkg/utils unit test coverage to 82.3%
  Makefile
  dm/master/server.go
  dm/unit/unit.go
  dm/unit/unit_test.go
  dm/worker/server.go
  dm/worker/status.go
  dumpling/dumpling.go
  loader/db.go
  pkg/retry/errors.go
  pkg/utils/common.go
  pkg/utils/common_test.go
  pkg/utils/db.go
  pkg/utils/db_test.go
  pkg/utils/encrypt_test.go
  pkg/utils/file.go
  pkg/utils/file_test.go
  pkg/utils/hash_test.go
  pkg/utils/printer_test.go
  pkg/utils/relay_test.go
  pkg/utils/storage_test.go
  pkg/utils/string.go
  pkg/utils/util_test.go
  relay/retry/reader.go
  syncer/ddl_test.go
  syncer/error.go
  syncer/error_test.go
  syncer/streamer_controller.go
  syncer/syncer.go
Labels: priority/normal, status/LGT2

#1073 *: run chaos-mesh operations with GitHub action (#930)
  .github/workflows/chaos-mesh.yml
  Makefile
  chaos/cases/conf/source1.yaml
  chaos/cases/conf/source2.yaml
  chaos/cases/conf/task-single.yaml
  chaos/cases/config.go
  chaos/cases/db.go
  chaos/cases/diff.go
  chaos/cases/dml.go
  chaos/cases/main.go
  chaos/cases/member.go
  chaos/cases/schema.go
  chaos/cases/single.go
  chaos/cases/source.go
  chaos/manifests/Dockerfile
  chaos/manifests/cases.yaml
  chaos/manifests/dm-master.yaml
  chaos/manifests/dm-worker.yaml
  chaos/manifests/mysql.yaml
  chaos/manifests/pod-failure-dm.yaml
  chaos/manifests/pod-kill-dm.yaml
  chaos/manifests/tidb.yaml
  go.mod
  go.sum
Labels: status/LGT1, status/PTAL, type/cherry-pick, type/qa

#1069 improve coverage for syncer/sharding_group.go to 82.4%
  syncer/sharding_group.go
  syncer/sharding_group_test.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2

#1078 actions: cache go modules and retool
  .github/workflows/chaos-mesh.yml
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1

#1077 task_checker: ignore more unrecoverable error
  pkg/retry/errors.go
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2

#1084 *: remove unused `query-error`
  dm/ctl/ctl.go
  dm/ctl/master/query_error.go
  dm/master/server.go
  dm/master/server_test.go
  dm/master/workerrpc/interface.go
  dm/master/workerrpc/rawgrpc.go
  dm/master/workerrpc/workerrpc_test.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmworker.pb.go
  dm/pbmock/dmmaster.go
  dm/pbmock/dmworker.go
  dm/proto/dmmaster.proto
  dm/proto/dmworker.proto
  dm/unit/unit.go
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/status.go
  dm/worker/subtask_test.go
  dm/worker/worker.go
  dumpling/dumpling.go
  loader/status.go
  syncer/syncer.go
  syncer/syncer_test.go
  syncer/warning.go
  tests/dmctl_advance/check_list/query_error.sh
  tests/dmctl_advance/run.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1

#1087 *: remove unused `query-error` (#1084)
  dm/ctl/ctl.go
  dm/ctl/master/query_error.go
  dm/master/server.go
  dm/master/server_test.go
  dm/master/workerrpc/interface.go
  dm/master/workerrpc/rawgrpc.go
  dm/master/workerrpc/workerrpc_test.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmworker.pb.go
  dm/pbmock/dmmaster.go
  dm/pbmock/dmworker.go
  dm/proto/dmmaster.proto
  dm/proto/dmworker.proto
  dm/unit/unit.go
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/status.go
  dm/worker/subtask_test.go
  dm/worker/worker.go
  dumpling/dumpling.go
  loader/status.go
  syncer/syncer.go
  syncer/syncer_test.go
  syncer/warning.go
  tests/dmctl_advance/check_list/query_error.sh
  tests/dmctl_advance/run.sh
Labels: priority/normal, status/LGT1, type/cherry-pick

#1086 test: move some functions into dm/pkg
  dm/command/argument.go
  dm/ctl/common/util.go
  dm/ctl/master/handle_error.go
  dm/ctl/master/purge_relay.go
  pkg/binlog/position.go
  pkg/binlog/position_test.go
  pkg/utils/common.go
  pkg/utils/common_test.go
  syncer/handle_error.go
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2, type/test

#1098 *: add roadmap
  README.md
  roadmap.md
Labels: priority/normal, status/PTAL

#1094 dumpling: remove a confusing log
  dumpling/dumpling.go
Labels: needs-cherry-pick-2.0, priority/unimportant, status/LGT2, type/bug-fix

#1093 tracker: don't execute add FK on tracker
  syncer/syncer.go
  syncer/syncer_test.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2, type/bug-fix

#1091 *: clear and refine some code for RPC methods
  cmd/dm-ctl/main.go
  dm/ctl/ctl.go
  dm/ctl/master/migrate_relay.go
  dm/ctl/master/switch_relay_master.go
  dm/ctl/master/update_masterconfig.go
  dm/ctl/master/update_relay.go
  dm/master/config.go
  dm/master/config_test.go
  dm/master/dm-master.toml
  dm/master/scheduler/scheduler_test.go
  dm/master/scheduler/worker_test.go
  dm/master/server.go
  dm/master/server_test.go
  dm/master/workerrpc/interface.go
  dm/master/workerrpc/rawgrpc.go
  dm/master/workerrpc/workerrpc_test.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmworker.pb.go
  dm/pbmock/dmmaster.go
  dm/pbmock/dmworker.go
  dm/proto/dmmaster.proto
  dm/proto/dmworker.proto
  dm/worker/metrics.go
  dm/worker/relay.go
  dm/worker/relay_test.go
  dm/worker/server.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  relay/relay.go
  tests/dmctl_advance/check_list/switch_relay_master.sh
  tests/dmctl_basic/check_list/update_task.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1

#1104 OperateSchema: init workerReq with source
  dm/master/server.go
  tests/sequence_sharding_optimistic/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, priority/normal, status/LGT1, type/bug-fix

#1079 performance: use OPTIMISTIC transaction as the default
  dm/config/task.go
  dm/config/task_test.go
  dm/master/server.go
  dm/master/server_test.go
  go.mod
  pkg/schema/tracker.go
  pkg/schema/tracker_test.go
  pkg/utils/db.go
  pkg/utils/db_test.go
  syncer/checkpoint_test.go
  syncer/syncer_test.go
  tests/all_mode/run.sh
  tests/dmctl_basic/check_list/check_task.sh
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2

#1105 tracker: fetch ref table at CREATE LIKE and more
  _utils/terror_gen/errors_release.txt
  errors.toml
  pkg/parser/common.go
  pkg/parser/common_test.go
  pkg/terror/error_list.go
  pkg/utils/util.go
  syncer/filter_test.go
  syncer/ghost.go
  syncer/pt_osc.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: needs-cherry-pick-2.0, needs-update-docs, needs-update-release-note, priority/normal, status/LGT2, type/bug-fix

#1111 Revert "dump: retrieve ANSI_QUOTES from upstream (#909) (#929)"
  dm/config/task.go
  mydumper/mydumper.go
Labels: priority/normal, status/LGT2, type/bug-fix

#1048 *: update parser to support `GRANT CREATE TABLESPACE` syntax
  go.mod
  go.sum
  pkg/parser/common_test.go
  syncer/error.go
Labels: dependencies, priority/normal, status/LGT2, status/PTAL, type/bug-fix

#1113 *: update parser to support `GRANT CREATE TABLESPACE` syntax (#1048)
  go.mod
  go.sum
  pkg/parser/common_test.go
  syncer/error.go
Labels: dependencies, priority/normal, status/LGT1, type/bug-fix, type/cherry-pick

#1109 syncer: improve coverage for syncer/ddl.go to 85.1%
  syncer/ddl.go
  syncer/ddl_test.go
  syncer/pt_osc.go
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT2

#1116 *: remove dm-tracer
  Dockerfile
  Makefile
  cmd/dm-tracer/main.go
  cmd/dm-tracer/main_test.go
  dm/config/source_config.go
  dm/master/server.go
  dm/pb/tracer.pb.go
  dm/pb/tracer_base.pb.go
  dm/pb/tracer_syncer.pb.go
  dm/proto/tracer.proto
  dm/proto/tracer_base.proto
  dm/proto/tracer_syncer.proto
  dm/tracer/README.md
  dm/tracer/config.go
  dm/tracer/http_handler.go
  dm/tracer/http_handler_test.go
  dm/tracer/http_status.go
  dm/tracer/server.go
  dm/tracer/store.go
  dm/worker/worker.go
  pkg/tracing/config.go
  pkg/tracing/event.go
  pkg/tracing/hub.go
  pkg/tracing/tracer.go
  pkg/tracing/tracer_syncer.go
  pkg/tracing/tracer_test.go
  pkg/tracing/utils.go
  pkg/tracing/utils_test.go
  syncer/job.go
  syncer/job_test.go
  syncer/optimist.go
  syncer/syncer.go
  tests/_dmctl_tools/check_safe_mode.go
  tests/_utils/env_variables
  tests/_utils/run_dm_tracer
  tests/_utils/test_prepare
  tests/generate-mock.sh
  tests/safe_mode/conf/dm-tracer.toml
  tests/sequence_safe_mode/conf/dm-tracer.toml
Labels: needs-cherry-pick-2.0, priority/important, status/LGT2

#1121 *: remove dm-tracer (#1116)
  Dockerfile
  Makefile
  cmd/dm-tracer/main.go
  cmd/dm-tracer/main_test.go
  dm/config/source_config.go
  dm/master/server.go
  dm/pb/tracer.pb.go
  dm/pb/tracer_base.pb.go
  dm/pb/tracer_syncer.pb.go
  dm/proto/tracer.proto
  dm/proto/tracer_base.proto
  dm/proto/tracer_syncer.proto
  dm/tracer/README.md
  dm/tracer/config.go
  dm/tracer/http_handler.go
  dm/tracer/http_handler_test.go
  dm/tracer/http_status.go
  dm/tracer/server.go
  dm/tracer/store.go
  dm/worker/worker.go
  pkg/tracing/config.go
  pkg/tracing/event.go
  pkg/tracing/hub.go
  pkg/tracing/tracer.go
  pkg/tracing/tracer_syncer.go
  pkg/tracing/tracer_test.go
  pkg/tracing/utils.go
  pkg/tracing/utils_test.go
  syncer/job.go
  syncer/job_test.go
  syncer/optimist.go
  syncer/syncer.go
  tests/_dmctl_tools/check_safe_mode.go
  tests/_utils/env_variables
  tests/_utils/run_dm_tracer
  tests/_utils/test_prepare
  tests/generate-mock.sh
  tests/safe_mode/conf/dm-tracer.toml
  tests/sequence_safe_mode/conf/dm-tracer.toml
Labels: priority/important, status/LGT1, type/cherry-pick

#1122 dumpling: support metadata without GTID
  pkg/dumpling/utils.go
  pkg/dumpling/utils_test.go
Labels: needs-cherry-pick-2.0, priority/release-blocker, status/LGT1
