Repository pingcap/dm, pull requests merged in 2020-07, with the labels that each got.

#763 checkpoint: cherrypick flush global checkpoint when first time flush checkpoint
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/syncer_test.go
Labels: status/LGT2, type/cherry-pick

#769 check_task: ping db when apply dbconfig
  dm/master/server_test.go
  pkg/conn/basedb.go
  tests/dmctl_basic/check_list/check_task.sh
  tests/dmctl_basic/run.sh
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, type/bug-fix

#768 doc: provide more detailed instructions
  tests/README.md
Labels: priority/unimportant, status/LGT2, type/doc

#778 check_task: cherrypick ping db when apply dbconfig
  pkg/conn/basedb.go
  tests/all_mode/run.sh
  tests/dmctl_basic/check_list/check_task.sh
  tests/dmctl_basic/run.sh
Labels: priority/normal, status/LGT2, type/cherry-pick

#762 .*: cherrypick add workaround for error
  _utils/terror_gen/checker_template.go
  _utils/terror_gen/errors_release.txt
  dm/config/subtask_test.go
  dm/config/task_test.go
  dm/master/config_test.go
  dm/master/server_test.go
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/tracer/http_handler_test.go
  dm/worker/config_test.go
  dm/worker/server_test.go
  dm/worker/upgrade_test.go
  pkg/binlog/position_test.go
  pkg/terror/adapter_test.go
  pkg/terror/error_list.go
  pkg/terror/terror.go
  pkg/terror/terror_test.go
  syncer/db_test.go
  syncer/sharding-meta/shardmeta_test.go
  tests/dmctl_advance/check_list/sql_replace.sh
  tests/dmctl_advance/check_list/sql_skip.sh
Labels: status/LGT2, type/cherry-pick

#772 worker: add metrics
  dm/worker/metrics.go
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/subtask.go
  dm/worker/task_checker_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
Labels: priority/normal, status/LGT1, type/feature

#765 workaround: add instruction for err
  _utils/terror_gen/errors_release.txt
  checker/checker.go
  errors.toml
  pkg/terror/error_list.go
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2

#776 master: add metrics for worker state
  dm/master/metrics/metrics.go
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/worker.go
  dm/master/server.go
Labels: priority/normal, status/LGT2, type/feature

#780 log: set log level for embed etcd and ddl tracker
  cmd/dm-worker/main.go
  dm/master/config.go
Labels: priority/normal, status/LGT2, type/feature

#785 test: improve stability for tests
  dm/master/server_test.go
  dm/master/shardddl/optimist_test.go
  pkg/ha/keepalive_test.go
  pkg/shardddl/pessimism/info_test.go
  pkg/shardddl/pessimism/operation_test.go
  pkg/streamer/reader_test.go
  tests/ha_cases/run.sh
  tests/sharding2/run.sh
Labels: priority/unimportant, status/LGT1, status/PTAL, type/bug-fix

#771 error_message: more friendly error message
  _utils/terror_gen/checker_template.go
  _utils/terror_gen/errors_release.txt
  checker/cmd.go
  dm/config/subtask_test.go
  dm/ctl/master/query_status_test.go
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/unit/unit.go
  dm/worker/relay.go
  dm/worker/status.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  dm/worker/task_checker.go
  errors.toml
  pkg/election/election_test.go
  pkg/terror/adapter_test.go
  pkg/terror/error_list.go
  pkg/terror/terror.go
  pkg/terror/terror_test.go
  syncer/sharding-meta/shardmeta_test.go
  tests/dmctl_advance/check_list/sql_replace.sh
  tests/dmctl_advance/check_list/sql_skip.sh
  tests/dmctl_basic/check_list/check_task.sh
  tests/relay_interrupt/run.sh
  tests/shardddl1/run.sh
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, status/PTAL

#786 dmctl: check master connection when start.
  _utils/terror_gen/errors_release.txt
  cmd/dm-ctl/main.go
  dm/ctl/common/util.go
  errors.toml
  pkg/terror/error_list.go
  pkg/terror/terror.go
  tests/dmctl_advance/check_list/migrate_relay.sh
  tests/dmctl_advance/check_list/query_error.sh
  tests/dmctl_advance/check_list/sql_replace.sh
  tests/dmctl_advance/check_list/sql_skip.sh
  tests/dmctl_advance/check_list/switch_relay_master.sh
  tests/dmctl_advance/check_list/unlock_ddl_lock.sh
  tests/dmctl_advance/conf/dm-master.toml
  tests/dmctl_advance/run.sh
  tests/dmctl_basic/check_list/check_task.sh
  tests/dmctl_basic/check_list/operate_source.sh
  tests/dmctl_basic/check_list/pause_relay.sh
  tests/dmctl_basic/check_list/pause_task.sh
  tests/dmctl_basic/check_list/purge_relay.sh
  tests/dmctl_basic/check_list/query_status.sh
  tests/dmctl_basic/check_list/resume_task.sh
  tests/dmctl_basic/check_list/show_ddl_locks.sh
  tests/dmctl_basic/check_list/start_task.sh
  tests/dmctl_basic/check_list/stop_task.sh
  tests/dmctl_basic/check_list/update_master_config.sh
  tests/dmctl_basic/check_list/update_relay.sh
  tests/dmctl_basic/check_list/update_task.sh
  tests/dmctl_basic/run.sh
  tests/dmctl_command/run.sh
Labels: priority/normal, status/LGT2, type/feature

#789 master: add HTTP interface for getting subtask's config
  dm/master/server.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmmaster.pb.gw.go
  dm/proto/dmmaster.proto
  tests/http_apis/run.sh
Labels: status/LGT2, type/feature

#787 master: fix unit test for OfflineMember
  dm/master/election.go
  dm/master/server.go
  dm/master/server_test.go
  tests/ha_cases/run.sh
  tests/ha_master/run.sh
Labels: status/LGT2, type/bug-fix

#779 ctl, master: support multiple sources create/stop
  dm/ctl/common/config.go
  dm/ctl/master/operate_source.go
  dm/master/server.go
  dm/master/server_test.go
  dm/pb/dmmaster.pb.go
  dm/proto/dmmaster.proto
  tests/dmctl_basic/check_list/operate_source.sh
  tests/http_apis/run.sh
Labels: priority/normal, status/LGT2, type/feature

#770 config, loader: auto-remove imported dump file
  dm/config/subtask.go
  dm/config/task.go
  loader/checkpoint.go
  loader/loader.go
  syncer/syncer.go
  tests/all_mode/run.sh
  tests/dm_syncer/conf/dm-task.yaml
  tests/full_mode/run.sh
  tests/import_goroutine_leak/run.sh
  tests/incremental_mode/conf/dm-task.yaml
  tests/load_interrupt/run.sh
Labels: needs-update-docs, priority/normal, status/LGT2, type/feature

#797 doc: fix a typo in pull_request_template.md
  .github/pull_request_template.md
Labels: priority/unimportant, status/LGT1, type/doc

#800 workaround: add instruction for err (#765)
  _utils/terror_gen/errors_release.txt
  checker/checker.go
  pkg/terror/error_list.go
Labels: priority/normal, status/LGT2, type/cherry-pick

#799 error_message: more friendly error message #711
  _utils/terror_gen/checker_template.go
  _utils/terror_gen/errors_release.txt
  checker/checker.go
  checker/cmd.go
  dm/config/subtask_test.go
  dm/ctl/master/query_status_test.go
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/unit/unit.go
  dm/unit/unit_test.go
  dm/worker/relay.go
  dm/worker/relay_test.go
  dm/worker/status.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  dm/worker/task_checker.go
  dm/worker/task_checker_test.go
  loader/loader.go
  mydumper/mydumper.go
  pkg/terror/adapter_test.go
  pkg/terror/error_list.go
  pkg/terror/terror.go
  pkg/terror/terror_test.go
  relay/relay.go
  syncer/mode.go
  syncer/sharding-meta/shardmeta_test.go
  syncer/syncer.go
  tests/dmctl_advance/check_list/sql_replace.sh
  tests/dmctl_advance/check_list/sql_skip.sh
  tests/dmctl_basic/check_list/check_task.sh
  tests/relay_interrupt/run.sh
Labels: priority/normal, status/LGT2, type/cherry-pick

#802 dmctl: check master connection when start. (#786)
  _utils/terror_gen/errors_release.txt
  cmd/dm-ctl/main.go
  dm/ctl/common/util.go
  pkg/terror/error_list.go
  pkg/terror/terror.go
  tests/dmctl_advance/check_list/break_ddl_lock.sh
  tests/dmctl_advance/check_list/migrate_relay.sh
  tests/dmctl_advance/check_list/query_error.sh
  tests/dmctl_advance/check_list/refresh_worker_tasks.sh
  tests/dmctl_advance/check_list/sql_replace.sh
  tests/dmctl_advance/check_list/sql_skip.sh
  tests/dmctl_advance/check_list/switch_relay_master.sh
  tests/dmctl_advance/check_list/unlock_ddl_lock.sh
  tests/dmctl_advance/conf/dm-master.toml
  tests/dmctl_advance/run.sh
  tests/dmctl_basic/check_list/check_task.sh
  tests/dmctl_basic/check_list/pause_relay.sh
  tests/dmctl_basic/check_list/pause_task.sh
  tests/dmctl_basic/check_list/purge_relay.sh
  tests/dmctl_basic/check_list/query_status.sh
  tests/dmctl_basic/check_list/resume_task.sh
  tests/dmctl_basic/check_list/show_ddl_locks.sh
  tests/dmctl_basic/check_list/start_task.sh
  tests/dmctl_basic/check_list/stop_task.sh
  tests/dmctl_basic/check_list/update_master_config.sh
  tests/dmctl_basic/check_list/update_relay.sh
  tests/dmctl_basic/check_list/update_task.sh
  tests/dmctl_basic/run.sh
  tests/dmctl_command/run.sh
Labels: priority/normal, status/LGT2, type/cherry-pick

#764 feat: add `operate-schema` command
  _utils/terror_gen/errors_release.txt
  dm/ctl/ctl.go
  dm/ctl/master/operate_schema.go
  dm/master/server.go
  dm/master/workerrpc/interface.go
  dm/master/workerrpc/rawgrpc.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmmaster.pb.gw.go
  dm/pb/dmworker.pb.go
  dm/pbmock/dmmaster.go
  dm/pbmock/dmworker.go
  dm/proto/dmmaster.proto
  dm/proto/dmworker.proto
  dm/worker/server.go
  dm/worker/subtask.go
  dm/worker/worker.go
  errors.toml
  pkg/schema/tracker.go
  pkg/schema/tracker_test.go
  pkg/terror/error_list.go
  syncer/schema.go
  syncer/shardddl/pessimist.go
  tests/dmctl_command/run.sh
  tests/sequence_sharding_optimistic/data/db1.increment2.sql
  tests/sequence_sharding_optimistic/data/db2.increment2.sql
  tests/sequence_sharding_optimistic/run.sh
Labels: needs-update-docs, priority/normal, status/LGT2, type/feature

#804 config, loader: auto-remove imported dump file (#770)
  dm/config/subtask.go
  dm/config/task.go
  loader/checkpoint.go
  loader/loader.go
  syncer/syncer.go
  tests/all_mode/run.sh
  tests/full_mode/run.sh
  tests/import_goroutine_leak/run.sh
  tests/incremental_mode/conf/dm-task.yaml
  tests/load_interrupt/run.sh
Labels: priority/normal, status/LGT2, type/cherry-pick

#794 *: detect user cancel and omit according error
  _utils/terror_gen/errors_release.txt
  errors.toml
  pkg/atomic2/atomic.go
  pkg/atomic2/atomic_test.go
  pkg/terror/error_list.go
  syncer/optimist.go
  syncer/shardddl/pessimist.go
  syncer/syncer.go
  tests/incremental_mode/run.sh
Labels: status/LGT1, status/PTAL, type/bug-fix

#798 feat: add get-task-config command
  CONTRIBUTING.md
  _utils/terror_gen/errors_release.txt
  dm/common/common.go
  dm/config/task.go
  dm/ctl/ctl.go
  dm/ctl/master/get_task_config.go
  dm/master/scheduler/scheduler.go
  dm/master/server.go
  dm/master/server_test.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmmaster.pb.gw.go
  dm/pbmock/dmmaster.go
  dm/proto/dmmaster.proto
  errors.toml
  pkg/ha/source.go
  pkg/ha/task.go
  pkg/ha/task_test.go
  pkg/terror/error_list.go
  step_by_step_contribute.md
  tests/dmctl_basic/check_list/get_task_config.sh
  tests/dmctl_basic/run.sh
  tests/dmctl_command/run.sh
  tests/http_apis/run.sh
Labels: priority/normal, status/LGT2, type/feature

#805 test: fix TestPauseAndResumeSubtask
  dm/worker/subtask_test.go
Labels: needs-cherry-pick-1.0, priority/unimportant, status/LGT1, type/bug-fix

#808 *: add `json` log format support
  .gitignore
  cmd/dm-master/main.go
  cmd/dm-syncer/config.go
  cmd/dm-syncer/main.go
  cmd/dm-tracer/main.go
  cmd/dm-worker/main.go
  debug-tools/binlog-event-blackhole/config.go
  debug-tools/binlog-event-blackhole/main.go
  dm/config/subtask.go
  dm/master/config.go
  dm/tracer/config.go
  dm/worker/config.go
  dm/worker/server.go
  pkg/log/log.go
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT1, type/enhancement

#801 syncer: auto drop index before drop column
  pkg/schema/tracker.go
  pkg/schema/tracker_test.go
  syncer/error.go
  syncer/error_test.go
  syncer/syncer.go
  tests/drop_column_with_index/conf/diff_config.toml
  tests/drop_column_with_index/conf/dm-master.toml
  tests/drop_column_with_index/conf/dm-task.yaml
  tests/drop_column_with_index/conf/dm-worker1.toml
  tests/drop_column_with_index/conf/source1.toml
  tests/drop_column_with_index/data/db1.increment.sql
  tests/drop_column_with_index/data/db1.prepare.sql
  tests/drop_column_with_index/run.sh
  tests/others_integration.txt
Labels: priority/normal, status/LGT2, type/feature

#810 *: add `json` log format support (#808)
  .gitignore
  cmd/dm-master/main.go
  cmd/dm-tracer/main.go
  cmd/dm-worker/main.go
  dm/config/subtask.go
  dm/master/config.go
  dm/tracer/config.go
  dm/worker/config.go
  dm/worker/worker.go
  go.mod
  go.sum
  pkg/log/log.go
Labels: priority/normal, status/LGT1, type/cherry-pick, type/enhancement

#790 master: add metrics for handle DDL
  dm/dm-ansible/scripts/dm.json
  dm/master/election.go
  dm/master/metrics/metrics.go
  dm/master/shardddl/optimist.go
  dm/master/shardddl/pessimist.go
Labels: priority/normal, status/LGT2, type/feature

#807 loader: support enable-ansi-quotes
  checker/check_test.go
  checker/checker.go
  checker/cmd.go
  cmd/dm-syncer/config.go
  dm/config/subtask.go
  dm/config/task.go
  dm/master/server.go
  dm/master/server_test.go
  go.mod
  go.sum
  loader/convert_data.go
  loader/convert_data_test.go
  loader/dumpfile/test1.t2-schema.sql
  loader/loader.go
  tests/all_mode/conf/diff_config.toml
  tests/all_mode/conf/dm-task.yaml
  tests/all_mode/data/db1.prepare.sql
  tests/all_mode/run.sh
  tests/full_mode/run.sh
Labels: needs-cherry-pick-1.0, needs-update-docs, priority/normal, status/LGT2, type/compatibility

#803 ansible: add & update metric panels for syncer and misc
  dm/dm-ansible/scripts/dm.json
  syncer/metrics.go
  syncer/syncer.go
Labels: priority/normal, status/LGT2, type/dm-ansible

#812 test: increase TTL to improve stability
  dm/master/scheduler/scheduler_test.go
Labels: priority/unimportant, status/LGT2, type/bug-fix

#820 dm-master: fix wrong clientURL
  dm/master/config.go
  dm/master/config_test.go
Labels: priority/normal, status/LGT1, status/PTAL, type/bug-fix

#821 portal: minor fix on db config
  dm/portal/api.go
Labels: needs-cherry-pick-1.0, status/LGT2, type/bug-fix

#824 master: fix unit test for OfflineMember
  dm/master/server.go
  dm/master/server_test.go
Labels: status/LGT2, type/test

#822 error_message: remove stack error for flag
  cmd/dm-ctl/main.go
  cmd/dm-master/main.go
  cmd/dm-syncer/main.go
  cmd/dm-tracer/main.go
  cmd/dm-worker/main.go
  dm/worker/server.go
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2

#815 loader: support enable-ansi-quotes (#807)
  _utils/terror_gen/errors_release.txt
  checker/check_test.go
  checker/checker.go
  checker/cmd.go
  dm/config/subtask.go
  dm/config/task.go
  dm/master/server.go
  dm/master/server_test.go
  go.mod
  go.sum
  loader/convert_data.go
  loader/convert_data_test.go
  loader/dumpfile/test1.t2-schema.sql
  loader/loader.go
  pkg/terror/error_list.go
  tests/all_mode/conf/diff_config.toml
  tests/all_mode/conf/dm-task.yaml
  tests/all_mode/data/db1.increment.sql
  tests/all_mode/data/db1.prepare.sql
  tests/all_mode/run.sh
  tests/full_mode/run.sh
Labels: status/LGT2, type/cherry-pick

#813 *: change panels for loader, dumpling
  dm/dm-ansible/scripts/dm.json
  dumpling/dumpling.go
  dumpling/metrics.go
  loader/db.go
  loader/loader.go
  loader/metrics.go
  loader/status.go
  mydumper/metrics.go
  mydumper/mydumper.go
Labels: priority/normal, status/LGT2, type/dm-ansible, type/feature

#817 worker, utils: show same master status in one response
  dm/worker/server.go
  dm/worker/server_test.go
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, type/bug-fix

#827 source: add print-sample-config flag for operate-source
  Makefile
  dm/config/source_config.go
  dm/ctl/master/operate_source.go
  dm/master/source.toml
  tests/dmctl_basic/check_list/operate_source.sh
Labels: priority/normal, status/LGT2

#791 master: add metric indicate number of pending DDL state (pessimistic only)
  dm/dm-ansible/scripts/dm.json
  dm/master/metrics/metrics.go
  dm/master/shardddl/optimist.go
  dm/master/shardddl/pessimist.go
  pkg/shardddl/pessimism/lock.go
Labels: priority/normal, status/LGT2, type/feature

#814 shardddl/optimism: add `synced` as struct member
  pkg/shardddl/optimism/lock.go
  pkg/shardddl/optimism/lock_test.go
Labels: priority/normal, status/LGT1, type/feature

#829 tracker: support session config for tracker
  pkg/schema/tracker.go
  pkg/schema/tracker_test.go
  syncer/checkpoint_test.go
  syncer/syncer.go
  tests/sharding/conf/dm-task.yaml
  tests/sharding/data/db1.increment.sql
  tests/sharding/data/db1.increment2.sql
  tests/sharding/data/db2.increment.sql
  tests/sharding/data/db2.increment2.sql
  tests/sharding/run.sh
Labels: priority/normal, status/LGT2, type/bug-fix

#830 worker, utils: show same master status in one response (#817)
  dm/worker/server.go
  dm/worker/server_test.go
Labels: priority/normal, status/LGT2, type/cherry-pick

#834 test: increase waiting time
  dm/master/scheduler/scheduler_test.go
  pkg/ha/keepalive_test.go
  tests/sequence_sharding/run.sh
Labels: priority/unimportant, status/LGT1, type/bug-fix

#831 *: add metrics for optimistic shard DDL lock
  dm/master/metrics/metrics.go
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/worker.go
  dm/master/shardddl/optimist.go
  dm/master/shardddl/pessimist.go
  pkg/shardddl/optimism/lock.go
  pkg/shardddl/pessimism/lock.go
Labels: priority/normal, status/LGT1, type/feature

#833 master: add metric for worker event error
  dm/dm-ansible/scripts/dm.json
  dm/master/metrics/metrics.go
  dm/master/scheduler/scheduler.go
Labels: priority/normal, status/LGT1, type/feature

#835 *: back quote and escape MySQL identifier
  dm/master/server.go
  loader/checkpoint.go
  syncer/checkpoint.go
  syncer/online_ddl.go
  syncer/sharding-meta/shardmeta.go
  syncer/sharding-meta/shardmeta_test.go
  syncer/sharding_group.go
  tests/all_mode/run.sh
Labels: needs-cherry-pick-1.0, priority/normal, status/LGT2, type/bug-fix

#843 test: remove repeated lines
  tests/all_mode/run.sh
Labels: priority/unimportant, status/LGT1, type/bug-fix

#839 feat: add a simple cluster upgrade framework
  Makefile
  _utils/terror_gen/errors_release.txt
  dm/common/common.go
  dm/ctl/master/operate_source.go
  dm/master/config.go
  dm/master/election.go
  dm/master/server_test.go
  dm/worker/worker.go
  errors.toml
  pkg/shardddl/optimism/info.go
  pkg/terror/error_list.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  pkg/upgrade/version.go
  pkg/upgrade/version_test.go
  syncer/error.go
  syncer/syncer.go
  tests/ha_master/run.sh
Labels: needs-update-docs, priority/important, status/LGT2, type/feature

#836 schema: update tidb, support multi drop of column and partition
  go.mod
  go.sum
  pkg/schema/tracker.go
  pkg/schema/tracker_test.go
  tools.json
Labels: needs-cherry-pick-1.0, needs-update-release-note, priority/normal, status/LGT2, type/dependencies

#838 master: add `operate-source show`
  dm/ctl/master/operate_source.go
  dm/master/scheduler/scheduler.go
  dm/master/server.go
  dm/pb/dmmaster.pb.go
  dm/proto/dmmaster.proto
  tests/dmctl_basic/check_list/operate_source.sh
  tests/dmctl_basic/run.sh
Labels: needs-cherry-pick-1.0, needs-update-docs, needs-update-release-note, priority/normal, status/LGT2, type/bug-fix

#840 *: back quote and escape MySQL identifier #835
  loader/checkpoint.go
  syncer/checkpoint.go
  syncer/online_ddl.go
  syncer/sharding-meta/shardmeta.go
  syncer/sharding_group.go
  tests/all_mode/run.sh
Labels: priority/normal, status/LGT2, type/cherry-pick

#848 *: use terror for some error
  _utils/terror_gen/errors_release.txt
  dm/worker/join.go
  errors.toml
  pkg/ha/bound.go
  pkg/ha/source.go
  pkg/ha/stage.go
  pkg/ha/subtask.go
  pkg/ha/task.go
  pkg/terror/error_list.go
Labels: needs-cherry-pick-1.0, priority/unimportant, status/LGT2, type/feature

#845 dmctl: add exit code for command mode
  cmd/dm-ctl/main.go
  dm/ctl/common/util.go
  dm/ctl/ctl.go
  dm/ctl/master/check_task.go
  dm/ctl/master/get_task_config.go
  dm/ctl/master/list_member.go
  dm/ctl/master/migrate_relay.go
  dm/ctl/master/offline_member.go
  dm/ctl/master/operate_leader.go
  dm/ctl/master/operate_schema.go
  dm/ctl/master/operate_source.go
  dm/ctl/master/pause_relay.go
  dm/ctl/master/pause_task.go
  dm/ctl/master/purge_relay.go
  dm/ctl/master/query_error.go
  dm/ctl/master/query_status.go
  dm/ctl/master/resume_relay.go
  dm/ctl/master/resume_task.go
  dm/ctl/master/show_ddl_locks.go
  dm/ctl/master/sql_inject.go
  dm/ctl/master/sql_replace.go
  dm/ctl/master/sql_skip.go
  dm/ctl/master/start_task.go
  dm/ctl/master/stop_task.go
  dm/ctl/master/switch_relay_master.go
  dm/ctl/master/unlock_ddl_lock.go
  dm/ctl/master/update_masterconfig.go
  dm/ctl/master/update_relay.go
  dm/ctl/master/update_task.go
  tests/dmctl_basic/check_list/check_task.sh
  tests/dmctl_basic/check_list/operate_source.sh
  tests/dmctl_basic/check_list/start_task.sh
  tests/dmctl_basic/check_list/update_master_config.sh
  tests/dmctl_basic/check_list/update_relay.sh
  tests/dmctl_basic/check_list/update_task.sh
  tests/dmctl_command/run.sh
Labels: priority/normal, status/LGT1, type/bug-fix

#851 *: change `dm_version` to `nightly`
  dm/dm-ansible/inventory.ini
Labels: priority/unimportant, status/PTAL, type/dm-ansible

#849 remove stack error for flag (#822)
  cmd/dm-ctl/main.go
  cmd/dm-master/main.go
  cmd/dm-tracer/main.go
  cmd/dm-worker/main.go
Labels: priority/normal, status/LGT1, type/cherry-pick
