Repository pingcap/dm, pull requests merged in 2021-05, with the labels that each got.

#1635 etcd: fix json unmarshall error and sources not found after upgrade to 2.0.2
  .github/workflows/upgrade-via-tiup.yml
  dm/master/bootstrap.go
  dm/master/election.go
  dm/master/workerrpc/rawgrpc.go
  pkg/shardddl/optimism/info.go
  pkg/shardddl/optimism/info_test.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  tests/tiup/conf/diff_config_optimistic.toml
  tests/tiup/conf/task_optimistic.yaml
  tests/tiup/docker/docker-compose.yml
  tests/tiup/lib.sh
  tests/tiup/upgrade-from-v1.sh
  tests/tiup/upgrade-from-v2.sh
Labels: needs-cherry-pick-release-2.0, severity/critical, size/XL, status/LGT2, status/can-merge, type/bug-fix

#1638 *: show an unsynced message for workers which didn't get any shard DDL
  dm/master/server.go
  dm/master/server_test.go
  dm/worker/worker.go
  pkg/utils/common.go
  tests/sequence_sharding_removemeta/run.sh
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/L, status/LGT2, status/can-merge

#1657 loader: revert #1544 to reduce risks
  .gitignore
  loader/loader.go
  loader/loader_test.go
Labels: needs-cherry-pick-release-2.0, size/XL, status/LGT2, status/can-merge

#1659 syncer: save empty SQL when online DDL is filtered
  _utils/terror_gen/errors_release.txt
  dm/master/server.go
  dm/worker/worker.go
  errors.toml
  pkg/terror/error_list.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  pkg/upgrade/version.go
  pkg/utils/common.go
  syncer/ddl.go
  syncer/online_ddl.go
  syncer/syncer.go
  tests/dmctl_basic/run.sh
  tests/online_ddl/conf/dm-task.yaml
  tests/online_ddl/data/db1.increment2.sql
  tests/online_ddl/data/db2.increment2.sql
  tests/online_ddl/run.sh
  tests/sequence_sharding_removemeta/run.sh
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/L, status/LGT2, status/can-merge

#1669 CHANGELOG: update release note for 2.0.3
  .github/workflows/upgrade-via-tiup.yml
  CHANGELOG.md
Labels: needs-cherry-pick-release-2.0, require-LGT1, size/S, status/LGT1, status/PTAL, status/can-merge

#1672 dm-master: check etcd wal dir when restart
  .github/workflows/check-and-build.yml
  dm/master/etcd.go
  dm/master/etcd_test.go
  dm/master/server_test.go
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/M, status/LGT2, status/can-merge

#1687 lint: remove nolintlint
  .golangci.yml
Labels: size/XS, status/LGT2, status/PTAL, status/can-merge

#1624 *: limit checker error at a finer granularity and auto increase max size
  checker/checker.go
  dm/ctl/common/util.go
  dm/master/server.go
  dm/master/server_test.go
  go.mod
  go.sum
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/L, status/LGT2, status/can-merge

#1661 tests: add mariaDB to version upgrading CI
  .github/workflows/upgrade-via-tiup.yml
  dm/master/bootstrap.go
  dm/master/scheduler/scheduler.go
  pkg/upgrade/upgrade.go
  tests/_utils/test_prepare
  tests/ha/run.sh
  tests/tiup/ansible_data/inventory.ini
  tests/tiup/conf/diff_config.toml
  tests/tiup/conf/diff_config_optimistic.toml
  tests/tiup/conf/source2.yaml
  tests/tiup/conf/task.yaml
  tests/tiup/conf/task_optimistic.yaml
  tests/tiup/docker/control/Dockerfile
  tests/tiup/docker/docker-compose.yml
  tests/tiup/lib.sh
  tests/tiup/upgrade-from-v1.sh
  tests/tiup/upgrade-from-v2.sh
Labels: needs-cherry-pick-release-2.0, require-LGT1, size/L, status/LGT1, status/can-merge

#1701 Revert "loader: revert #1544 to reduce risks"
  .gitignore
  loader/loader.go
  loader/loader_test.go
  tests/all_mode/run.sh
Labels: require-LGT1, size/XL, status/LGT1, status/can-merge

#1700 tracker: speed up create table by lower api
  pkg/schema/tracker.go
  pkg/schema/tracker_test.go
Labels: needs-cherry-pick-release-2.0, size/L, status/LGT2, status/PTAL, status/can-merge

#1681 tests: cover all possible scenarios in upgrading tests
  tests/tiup/conf/diff_config_pessimistic.toml
  tests/tiup/conf/task_pessimistic.yaml
  tests/tiup/lib.sh
  tests/tiup/upgrade-from-v2.sh
Labels: needs-cherry-pick-release-2.0, size/L, status/LGT2, status/PTAL, status/can-merge

#1679 test: refine action trigger
  .github/workflows/binlog-999999.yml
  .github/workflows/chaos-mesh.yml
  .github/workflows/check-and-build.yml
  .github/workflows/upgrade-via-tiup.yml
  .github/workflows/upstream-switch.yml
Labels: needs-cherry-pick-release-2.0, size/S, status/LGT2, status/PTAL, status/can-merge

#1683 scheduler: check invalid source before apply last bound
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
Labels: needs-cherry-pick-release-2.0, size/L, status/LGT2, status/PTAL, status/can-merge

#1706 tests: fix some unstable test
  tests/_utils/run_dm_ctl_with_retry
  tests/_utils/wait_process_exit
  tests/gtid/run.sh
  tests/ha/run.sh
  tests/sharding/run.sh
Labels: needs-cherry-pick-release-2.0, size/M, status/LGT2, status/PTAL, status/can-merge

#1725 README: remove TiDB Monthly and add case studies
  README.md
Labels: size/XS, status/LGT2, status/can-merge

#1722 dmctl: try read master addr from env
  .github/workflows/upgrade-via-tiup.yml
  dm/ctl/common/config.go
  tests/dmctl_command/run.sh
  tests/tiup/upgrade-from-v2.sh
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/M, status/LGT2, status/PTAL, status/can-merge

#1698 *: update go version to 1.16
  .github/workflows/binlog-999999.yml
  .github/workflows/chaos-mesh.yml
  .github/workflows/upgrade-via-tiup.yml
  .github/workflows/upstream-switch.yml
  CONTRIBUTING.md
  Dockerfile
  go.mod
  go.sum
  step_by_step_contribute.md
  tests/tiup/docker/control/Dockerfile
  tests/tiup/docker/node/Dockerfile
  tools/go.mod
Labels: needs-update-release-note, require-LGT1, size/M, status/LGT1, status/can-merge

#1707 syncer: update dependency to avoid exit when meet unsupported binlog
  _utils/terror_gen/errors_release.txt
  errors.toml
  go.mod
  go.sum
  pkg/terror/error_list.go
  syncer/streamer_controller.go
  syncer/syncer.go
  tests/incremental_mode/run.sh
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/M, status/LGT2, status/can-merge
