Repository pingcap/dm, pull requests merged in 2021-07, with the labels that each got.

#1799 schemaTracker: fix operate-schema --flush panic
  dm/ctl/master/operate_schema.go
  syncer/checkpoint.go
  tests/_utils/env_variables
  tests/_utils/test_prepare
  tests/downstream_more_column/conf/dm-master.toml
  tests/downstream_more_column/conf/dm-task-incremental.yaml
  tests/downstream_more_column/conf/dm-task.yaml
  tests/downstream_more_column/conf/dm-worker1.toml
  tests/downstream_more_column/conf/source1.yaml
  tests/downstream_more_column/data/db1.increment.sql
  tests/downstream_more_column/data/db1.increment2.sql
  tests/downstream_more_column/data/db1.prepare.sql
  tests/downstream_more_column/data/schema.sql
  tests/downstream_more_column/data/tidb.prepare.sql
  tests/downstream_more_column/run.sh
  tests/others_integration.txt
Labels: needs-cherry-pick-release-2.0, needs-update-docs, needs-update-release-note, require-LGT1, size/L, status/LGT1, status/PTAL, status/can-merge

#1782 syncer: support filter row by SQL expression
  Makefile
  _utils/terror_gen/errors_release.txt
  dm/config/expression_filter.go
  dm/config/subtask.go
  dm/config/task.go
  dm/config/task_test.go
  errors.toml
  go.mod
  go.sum
  pkg/terror/error_list.go
  pkg/utils/common.go
  syncer/dml.go
  syncer/expr_filter_group.go
  syncer/filter_test.go
  syncer/schema.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/all_mode/conf/dm-task-expression-filter.yaml
  tests/all_mode/run.sh
  tests/dmctl_basic/conf/get_task.yaml
  tests/expression_filter/conf/dm-master.toml
  tests/expression_filter/conf/dm-task.yaml
  tests/expression_filter/conf/dm-task2.yaml
  tests/expression_filter/conf/dm-worker1.toml
  tests/expression_filter/conf/source1.yaml
  tests/expression_filter/data/db1.increment.sql
  tests/expression_filter/data/db1.increment2.sql
  tests/expression_filter/data/db1.prepare.sql
  tests/expression_filter/data/db1.prepare2.sql
  tests/expression_filter/run.sh
  tests/import_v10x/conf/task.yaml
  tests/others_integration.txt
Labels: needs-cherry-pick-release-2.0, needs-update-docs, needs-update-release-note, size/XXL, status/LGT2, status/can-merge

#1828 test: test \n in SQL column comments
  .github/workflows/check-and-build.yml
  syncer/online_ddl.go
  syncer/syncer.go
  tests/_utils/run_sql_file_online_ddl
  tests/_utils/run_sql_online_ddl
  tests/online_ddl/run.sh
Labels: needs-cherry-pick-release-2.0, require-LGT1, size/M, status/LGT1, status/can-merge

#1837 dep: update go-mysql to introduce DECIMAL optimization
  go.mod
  go.sum
  pkg/streamer/reader.go
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/S, status/LGT2, status/can-merge

#1817 *: try check every returned `err` are handled
  _utils/terror_gen/errors_release.txt
  checker/checker.go
  dm/config/source_config.go
  dm/config/subtask.go
  dm/config/task_test.go
  dm/ctl/master/unlock_ddl_lock.go
  dm/master/server.go
  dm/master/shardddl/optimist.go
  dumpling/dumpling.go
  dumpling/util.go
  errors.toml
  loader/loader.go
  pkg/binlog/event/common.go
  pkg/dumpling/utils.go
  pkg/ha/relay.go
  pkg/streamer/reader.go
  pkg/terror/error_list.go
  relay/meta.go
  tests/dmctl_basic/conf/get_task.yaml
  tests/dmctl_command/run.sh
Labels: needs-cherry-pick-release-2.0, needs-update-docs, needs-update-release-note, size/L, status/LGT2, status/can-merge

#1821 tracker: change `tidb_enable_change_column_type` default value to ON
  Makefile
  pkg/schema/tracker.go
  tests/_utils/handle_error_lib.sh
  tests/handle_error/run.sh
  tests/handle_error_2/lib.sh
  tests/handle_error_2/run.sh
  tests/handle_error_3/lib.sh
  tests/handle_error_3/run.sh
  tests/shardddl4_1/run.sh
Labels: needs-cherry-pick-release-2.0, needs-update-docs, size/XL, status/LGT2, status/PTAL, status/can-merge

#1844 test: fix two unstable tests
  pkg/schema/tracker_test.go
  tests/adjust_gtid/run.sh
Labels: needs-cherry-pick-release-2.0, require-LGT1, size/XS, status/LGT1, status/can-merge

#1823 syncer: remove auto_random when track table from downstream
  pkg/schema/tracker.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, require-LGT1, size/L, status/LGT1, status/can-merge

#1849 doc: fix test readme link
  README.md
Labels: needs-cherry-pick-release-2.0, require-LGT1, size/XS, status/LGT1, status/PTAL, status/can-merge

#1853 syncer: print number of filtered row changes in log
  syncer/dml.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/expression_filter/run.sh
Labels: needs-cherry-pick-release-2.0, size/M, status/LGT2, status/can-merge

#1861 terror: add a walkaround to indicate not all dm-master are up
  _utils/terror_gen/errors_release.txt
  errors.toml
  pkg/terror/error_list.go
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, require-LGT1, size/XS, status/LGT1, status/can-merge

#1863 syncer, binlog: set all UseDecimal to false
  pkg/binlog/common/replication.go
  pkg/binlog/reader/file.go
  pkg/binlog/reader/tcp_test.go
  pkg/binlog/reader/util_test.go
  pkg/v1dbschema/schema.go
  syncer/db_test.go
  syncer/filter_test.go
Labels: needs-cherry-pick-release-2.0, size/M, status/LGT2, status/can-merge

#1865 pin mariadb version in chaos
  .github/workflows/binlog-999999.yml
  chaos/manifests/sources.yaml
Labels: needs-cherry-pick-release-2.0, require-LGT1, size/S, status/LGT1, status/PTAL, status/can-merge

#1775 syncer: check block-allow list before online DDL components
  syncer/ddl.go
  syncer/ddl_test.go
  syncer/error.go
  syncer/filter.go
  syncer/ghost.go
  syncer/online_ddl.go
  syncer/pt_osc.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/_utils/run_sql_online_ddl
  tests/online_ddl/data/db1.increment.sql
  tests/online_ddl/data/db2.increment.sql
  tests/online_ddl/run.sh
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/XL, status/LGT2, status/can-merge

#1852 .*: fix etcd txn limit for lots of sources
  dm/master/config.go
  pkg/election/election.go
  pkg/ha/bound.go
  pkg/ha/keepalive.go
  pkg/ha/load_task.go
  pkg/ha/relay.go
  pkg/ha/stage.go
  pkg/shardddl/optimism/info.go
  pkg/shardddl/optimism/operation.go
  pkg/shardddl/optimism/table.go
  pkg/shardddl/pessimism/info.go
  pkg/shardddl/pessimism/operation.go
  pkg/upgrade/upgrade_test.go
  tests/dmctl_basic/conf/get_master1.toml
Labels: needs-cherry-pick-release-2.0, needs-update-docs, needs-update-release-note, size/L, status/LGT2, status/PTAL, status/can-merge, type/bug-fix

#1860 syncer: move files to new packages to prepare online DDL change
  dm/worker/metrics.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/db.go
  syncer/db_test.go
  syncer/dbconn/db.go
  syncer/ddl.go
  syncer/ddl_test.go
  syncer/error.go
  syncer/error_test.go
  syncer/filter.go
  syncer/heartbeat.go
  syncer/metrics/metrics.go
  syncer/online-ddl-tools/base.go
  syncer/online-ddl-tools/ghost.go
  syncer/online-ddl-tools/online_ddl.go
  syncer/online-ddl-tools/pt_osc.go
  syncer/sharding_group.go
  syncer/sharding_group_test.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/online_ddl/run.sh
Labels: needs-cherry-pick-release-2.0, size/XXL, status/LGT2, status/can-merge

#1871 tests: add slack notification for all github action test
  .github/workflows/binlog-999999.yml
  .github/workflows/check-and-build.yml
Labels: needs-cherry-pick-release-2.0, require-LGT1, size/S, status/LGT1, status/PTAL, status/can-merge

#1848 syncer: update binlog filename when receive fake rotate event
  .github/workflows/upstream-switch.yml
  pkg/binlog/reader/util.go
  pkg/utils/util.go
  relay/relay.go
  relay/writer/file.go
  syncer/job.go
  syncer/syncer.go
  tests/fake_rotate_event/conf/diff_config.toml
  tests/fake_rotate_event/conf/dm-master.toml
  tests/fake_rotate_event/conf/dm-task.yaml
  tests/fake_rotate_event/conf/dm-worker1.toml
  tests/fake_rotate_event/conf/source1.yaml
  tests/fake_rotate_event/data/db1.prepare.sql
  tests/fake_rotate_event/run.sh
  tests/others_integration.txt
  tests/upstream_switch/Dockerfile
  tests/upstream_switch/case.sh
  tests/upstream_switch/docker-compose.yml
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/XL, status/LGT2, status/PTAL, status/can-merge

#1873 chore: add feishu notification
  .github/workflows/binlog-999999.yml
  .github/workflows/chaos-mesh.yml
  .github/workflows/check-and-build.yml
  .github/workflows/upgrade-via-tiup.yml
  .github/workflows/upstream-switch.yml
  tests/upstream_switch/Dockerfile
Labels: size/XXL, status/LGT2, status/can-merge

#1855 syncer: update lag metric calculation logic
  .gitignore
  syncer/job.go
  syncer/syncer.go
  tests/_utils/check_ticker_interval.py
  tests/all_mode/run.sh
  tests/metrics/conf/diff_config.toml
  tests/metrics/conf/dm-master.toml
  tests/metrics/conf/dm-task.yaml
  tests/metrics/conf/dm-worker1.toml
  tests/metrics/conf/dm-worker2.toml
  tests/metrics/conf/source1.yaml
  tests/metrics/conf/source2.yaml
  tests/metrics/data/db1.increment.sql
  tests/metrics/data/db1.prepare.sql
  tests/metrics/data/db2.increment.sql
  tests/metrics/data/db2.prepare.sql
  tests/metrics/run.sh
  tests/others_integration.txt
Labels: size/XXL, status/LGT2, status/PTAL, status/can-merge

#1882 ci: fix release ci
  .github/workflows/upstream-switch.yml
Labels: size/S, status/LGT2, status/can-merge

#1881 ci: bump action-tmate to v3
  .github/workflows/binlog-999999.yml
  .github/workflows/chaos-mesh.yml
  .github/workflows/upgrade-via-tiup.yml
  .github/workflows/upstream-switch.yml
Labels: needs-cherry-pick-release-2.0, size/S, status/LGT2, status/can-merge

#1738 syncer: fix the case-sensitive issue
  chaos/cases/task.go
  go.mod
  go.sum
  loader/loader.go
  pkg/parser/common.go
  pkg/parser/common_test.go
  pkg/shardddl/optimism/column.go
  pkg/shardddl/optimism/info.go
  pkg/shardddl/optimism/operation.go
  pkg/shardddl/optimism/table.go
  pkg/utils/common.go
  syncer/checkpoint.go
  syncer/ddl.go
  syncer/ddl_test.go
  syncer/filter.go
  syncer/handle_error.go
  syncer/online-ddl-tools/ghost.go
  syncer/online-ddl-tools/online_ddl.go
  syncer/online-ddl-tools/pt_osc.go
  syncer/shardddl/optimist.go
  syncer/sharding-meta/shardmeta.go
  syncer/sharding_group.go
  syncer/sharding_group_test.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/_utils/check_metric
  tests/case_sensitive/conf/diff_config.toml
  tests/case_sensitive/conf/dm-master.toml
  tests/case_sensitive/conf/dm-task.yaml
  tests/case_sensitive/conf/dm-worker1.toml
  tests/case_sensitive/conf/dm-worker2.toml
  tests/case_sensitive/conf/source1.yaml
  tests/case_sensitive/conf/source2.yaml
  tests/case_sensitive/data/db1.increment.sql
  tests/case_sensitive/data/db1.prepare.sql
  tests/case_sensitive/data/db2.increment.sql
  tests/case_sensitive/data/db2.prepare.sql
  tests/case_sensitive/run.sh
  tests/others_integration.txt
  tests/start_task/run.sh
  tests/tiup/conf/diff_config.toml
  tests/tiup/conf/diff_config_pessimistic.toml
  tests/tiup/conf/task.yaml
  tests/tiup/conf/task_optimistic.yaml
  tests/tiup/conf/task_pessimistic.yaml
  tests/tiup/docker/docker-compose.yml
  tests/tiup/lib.sh
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/XXL, status/LGT2, status/can-merge

#1889 fix unstable test case_sensitive
  tests/case_sensitive/run.sh
Labels: needs-cherry-pick-release-2.0, size/XS, status/LGT1, type/test

#1897 chore: remove no job in queue log
  .github/workflows/binlog-999999.yml
  .github/workflows/chaos-mesh.yml
  .github/workflows/check-and-build.yml
  .github/workflows/upgrade-via-tiup.yml
  .github/workflows/upstream-switch.yml
  syncer/syncer.go
  tests/_utils/send_lark_notify.go
  tests/metrics/run.sh
Labels: needs-cherry-pick-release-2.0, size/L, status/LGT2, status/can-merge

#1902 chore: get real committer name && optimise dockerfile
  .github/workflows/binlog-999999.yml
  .github/workflows/chaos-mesh.yml
  .github/workflows/check-and-build.yml
  .github/workflows/upgrade-via-tiup.yml
  .github/workflows/upstream-switch.yml
  Dockerfile
  tests/_utils/send_lark_notify.go
Labels: needs-cherry-pick-release-2.0, size/S, status/LGT2, status/can-merge

#1908 *: Create SECURITY.md
  SECURITY.md
Labels: first-time-contributor, require-LGT1, size/M, status/LGT1, status/can-merge

#1903 syncer/dbconn: add more retry error
  go.mod
  go.sum
  syncer/dbconn/db.go
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/S, status/LGT2, status/can-merge

#1900 *: manual pause a task which has been pause by error
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  tests/drop_column_with_index/run.sh
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/M, status/LGT2, status/can-merge

#1904 syncer: support two online-ddl pt and gh-ost on one task
  dm/config/subtask.go
  dm/config/subtask_test.go
  dm/config/task.go
  dm/config/task_test.go
  syncer/ddl_test.go
  syncer/online-ddl-tools/base.go
  syncer/online-ddl-tools/ghost.go
  syncer/online-ddl-tools/online_ddl.go
  syncer/online-ddl-tools/pt_osc.go
  syncer/syncer.go
  tests/dmctl_basic/conf/get_task.yaml
  tests/import_v10x/conf/task.yaml
  tests/online_ddl/conf/diff_config.toml
  tests/online_ddl/conf/dm-task.yaml
  tests/online_ddl/data/db1.increment.sql
  tests/online_ddl/data/db1.increment2.sql
  tests/online_ddl/data/db1.prepare.sql
  tests/online_ddl/data/db2.increment.sql
  tests/online_ddl/data/db2.increment2.sql
  tests/online_ddl/data/db2.prepare.sql
  tests/online_ddl/data/gho.db1.increment.sql
  tests/online_ddl/data/gho.db1.increment2.sql
  tests/online_ddl/data/gho.db1.prepare.sql
  tests/online_ddl/data/gho.db2.increment.sql
  tests/online_ddl/data/gho.db2.increment2.sql
  tests/online_ddl/data/gho.db2.prepare.sql
  tests/online_ddl/data/pt.db1.increment.sql
  tests/online_ddl/data/pt.db1.increment2.sql
  tests/online_ddl/data/pt.db1.prepare.sql
  tests/online_ddl/data/pt.db2.increment.sql
  tests/online_ddl/data/pt.db2.increment2.sql
  tests/online_ddl/data/pt.db2.prepare.sql
  tests/online_ddl/run.sh
Labels: needs-cherry-pick-release-2.0, needs-update-docs, needs-update-release-note, size/XXL, status/LGT2, status/can-merge

#1915 *: read downstream table before CREATE TABLE to fix IF NOT EXISTS
  loader/loader.go
  syncer/syncer.go
  tests/downstream_more_column/run.sh
  tests/shardddl1/run.sh
  tests/shardddl1_1/run.sh
Labels: needs-cherry-pick-release-2.0, needs-update-docs, needs-update-release-note, size/M, status/LGT2, status/can-merge

#1906 syncer: optimize safemode mechanism to improve performance
  syncer/checkpoint.go
  syncer/mode.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/_dmctl_tools/check_exit_safe_binlog.go
  tests/incremental_mode/run.sh
  tests/safe_mode/run.sh
Labels: needs-cherry-pick-release-2.0, needs-update-docs, needs-update-release-note, size/XL, status/LGT2, status/can-merge

#1877 downgrade: add import/export-configs command
  dm/config/source_config.go
  dm/config/source_config_test.go
  dm/config/task.go
  dm/config/task_test.go
  dm/ctl/common/util.go
  dm/ctl/ctl.go
  dm/ctl/master/config.go
  dm/master/scheduler/scheduler.go
  pkg/ha/source.go
  tests/dmctl_command/run.sh
  tests/new_relay/conf/source1.yaml
  tests/new_relay/configs/relay_workers.json
  tests/new_relay/configs/sources/mysql-replica-01.yaml
  tests/new_relay/configs/tasks/test.yaml
  tests/new_relay/data/db1.increment5.sql
  tests/new_relay/run.sh
  tests/tiup/conf/source1.yaml
  tests/tiup/conf/source2.yaml
  tests/tiup/lib.sh
  tests/tiup/upgrade-from-v2.sh
Labels: needs-cherry-pick-release-2.0, needs-update-docs, needs-update-release-note, size/XXL, status/LGT2, status/PTAL, status/can-merge

#1912 make: add check for merge conflicts
  Makefile
Labels: needs-cherry-pick-release-2.0, require-LGT1, size/XS, status/LGT1, status/can-merge

#1924 fix safe mode
  syncer/mode.go
  syncer/syncer.go
  tests/safe_mode/conf/source1.yaml
  tests/safe_mode/conf/source2.yaml
Labels: needs-cherry-pick-release-2.0, size/M, status/LGT2, status/can-merge

#1926 syncer: fix safemode exit too early
  syncer/syncer.go
  tests/all_mode/data/db2.increment3.sql
  tests/all_mode/run.sh
  tests/case_sensitive/run.sh
  tests/ha/run.sh
  tests/metrics/run.sh
Labels: needs-cherry-pick-release-2.0, size/L, status/LGT2, status/can-merge

#1934 .*: update change-log for v2.0.5
  CHANGELOG.md
Labels: needs-cherry-pick-release-2.0, require-LGT1, size/M, status/LGT1, status/PTAL

#1939 syncer: drain the old tick before Reset
  syncer/syncer.go
  tests/_utils/check_ticker_interval
  tests/metrics/run.sh
Labels: needs-cherry-pick-release-2.0, size/M, status/LGT2

#1937 changelog: update description
  CHANGELOG.md
Labels: size/XS, status/LGT2, status/PTAL, status/can-merge

#1941 test: add upgrade test for v2.0.5
  .github/workflows/upgrade-via-tiup.yml
Labels: needs-cherry-pick-release-2.0, size/XS, status/LGT2, status/PTAL, status/can-merge, type/test

#1935 github: enable concurrency mode
  .github/workflows/chaos-mesh.yml
  .github/workflows/check-and-build.yml
  .github/workflows/upgrade-via-tiup.yml
Labels: needs-cherry-pick-release-2.0, require-LGT1, size/M, status/LGT1, status/can-merge

#1933 streamer: support `ls` relay log file with seq larger than 999999
  pkg/streamer/file.go
  pkg/streamer/file_test.go
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/L, status/LGT2, status/can-merge
