Repository pingcap/dm, pull requests merged in 2021-09, with the labels that each got.

#2063 master: return correct "result" for commands even error exists
  dm/common/common.go
  dm/master/scheduler/worker.go
  dm/master/server.go
  dm/master/server_test.go
  dm/master/workerrpc/interface.go
  dm/worker/status.go
  tests/drop_column_with_index/run.sh
  tests/safe_mode/run.sh
Labels: status/LGT2, needs-update-release-note, needs-cherry-pick-release-2.0, status/can-merge, size/L

#2070 syncer: remove get real table from onlineDDL.Apply
  syncer/ddl.go
  syncer/ddl_test.go
  syncer/online-ddl-tools/online_ddl.go
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/M

#2055 openapi: add source releated API
  Makefile
  dm/config/source_config.go
  dm/config/source_config_test.go
  dm/master/bootstrap_test.go
  dm/master/openapi.go
  dm/master/openapi_test.go
  openapi/gen.server.go
  openapi/gen.types.go
  openapi/spec/dm.yaml
  pkg/conn/basedb.go
  pkg/utils/common.go
  tests/dmctl_basic/check_list/config.sh
  tests/new_relay/run.sh
  tests/openapi/client/openapi_source_check
  tests/openapi/conf/diff_config.toml
  tests/openapi/conf/dm-master1.toml
  tests/openapi/conf/dm-master2.toml
  tests/openapi/conf/dm-worker1.toml
  tests/openapi/conf/dm-worker2.toml
  tests/openapi/run.sh
  tests/others_integration_2.txt
  tests/requirements.txt
Labels: needs-update-docs, status/LGT2, needs-update-release-note, needs-cherry-pick-release-2.0, status/can-merge, size/XXL

#2060 syncer: refine lag metric
  dm/dm-ansible/conf/dm_worker.rules.yml
  syncer/job.go
  syncer/syncer.go
  tests/metrics/run.sh
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/L

#2071 test: remove mysql in some unit-test
  Makefile
  checker/check_test.go
  dm/master/bootstrap_test.go
  dm/master/server.go
  dm/master/server_test.go
  dm/worker/worker_test.go
  dumpling/dumpling.go
  dumpling/dumpling_test.go
  loader/checkpoint_test.go
  pkg/conn/mockdb.go
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XL

#2095 test: fix unstable wait rpc alive
  tests/_utils/check_rpc_alive
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XS

#2086 syncer: replace `{schema, table}` with `filter.Table` Part 1
  _utils/terror_gen/errors_release.txt
  pkg/terror/error_list.go
  pkg/utils/common.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/ddl.go
  syncer/ddl_test.go
  syncer/sharding-meta/shardmeta.go
  syncer/sharding_group.go
  syncer/sharding_group_test.go
  syncer/syncer.go
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XL

#2101 test: fix can't drop column with index problem
  syncer/error.go
Labels: status/LGT2, status/PTAL, needs-cherry-pick-release-2.0, status/can-merge, size/XS

#1994 *: refine subtask and unit level API
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/unit/unit.go
  dm/worker/server_test.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  dm/worker/worker_test.go
  loader/loader.go
  syncer/syncer.go
  tests/start_task/run.sh
Labels: status/LGT2, needs-update-release-note, needs-cherry-pick-release-2.0, status/can-merge, size/XXL

#2094 syncer: fix the gtid purged error when switching pos replication to gtid
  pkg/utils/db_test.go
  syncer/syncer.go
Labels: status/LGT2, status/PTAL, needs-cherry-pick-release-2.0, status/can-merge, size/M

#2047 syncer, relay: avoid read duplicate event when retry binlog streamer
  pkg/streamer/reader.go
  pkg/streamer/streamer.go
  relay/relay.go
  relay/relay_test.go
  relay/retry/reader.go
  syncer/mode.go
  syncer/syncer.go
  tests/_utils/check_metric
  tests/duplicate_event/conf/diff_config.toml
  tests/duplicate_event/conf/diff_relay_config.toml
  tests/duplicate_event/conf/dm-master.toml
  tests/duplicate_event/conf/dm-task-relay.yaml
  tests/duplicate_event/conf/dm-task.yaml
  tests/duplicate_event/conf/dm-worker1.toml
  tests/duplicate_event/conf/dm-worker2.toml
  tests/duplicate_event/conf/source1.yaml
  tests/duplicate_event/conf/source2.yaml
  tests/duplicate_event/data/db1.increment.sql
  tests/duplicate_event/data/db1.prepare.sql
  tests/duplicate_event/run.sh
  tests/others_integration_2.txt
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XL

#2076 worker: rename to source worker and provide source-level status
  checker/checker.go
  dm/unit/unit.go
  dm/worker/hub.go
  dm/worker/relay.go
  dm/worker/relay_test.go
  dm/worker/server.go
  dm/worker/source_worker.go
  dm/worker/source_worker_test.go
  dm/worker/status.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  dm/worker/task_checker.go
  dm/worker/task_checker_test.go
  dumpling/dumpling.go
  loader/loader.go
  loader/status.go
  pkg/binlog/status.go
  pkg/binlog/status_test.go
  relay/relay.go
  syncer/dbconn/upstream_db.go
  syncer/dbconn/upstream_db_test.go
  syncer/status.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/print_status/run.sh
Labels: status/LGT2, needs-update-release-note, needs-cherry-pick-release-2.0, status/can-merge, size/XXL

#2113 grafana: fix grafana dashboard
  dm/dm-ansible/scripts/DM-Monitor-Professional.json
  dm/dm-ansible/scripts/DM-Monitor-Standard.json
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/M

#2099 syncer: raise error when binlog_row_image not FULL
  _utils/terror_gen/errors_release.txt
  errors.toml
  pkg/terror/error_list.go
  syncer/dml.go
  syncer/syncer.go
  tests/all_mode/run.sh
Labels: status/LGT1, needs-update-release-note, needs-cherry-pick-release-2.0, status/can-merge, size/M, require-LGT1

#2115 syncer: fix panic when concurrent call Status
  syncer/status.go
  syncer/status_test.go
  syncer/syncer.go
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/L

#2106 syncer: replace `{schema, table}` with `filter.Table` Part 2
  _utils/terror_gen/errors_release.txt
  errors.toml
  pkg/parser/common.go
  pkg/parser/common_test.go
  pkg/schema/tracker.go
  pkg/schema/tracker_test.go
  pkg/terror/error_list.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/ddl.go
  syncer/filter.go
  syncer/filter_test.go
  syncer/handle_error.go
  syncer/job.go
  syncer/job_test.go
  syncer/optimist.go
  syncer/schema.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/downstream_more_column/run.sh
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XXL

#2116 test: add check_grafana_dashboard_datasource
  tests/_utils/check_grafana_dashboard_datasource
  tests/metrics/run.sh
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/M

#2112 syncer: add a struct `queryEventContext` to manage variables
  syncer/ddl.go
  syncer/job.go
  syncer/job_test.go
  syncer/optimist.go
  syncer/syncer.go
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XL

#2125 test: move some unit test to right place
  pkg/utils/util_test.go
  syncer/expr_filter_group_test.go
  syncer/filter_test.go
Labels: status/LGT2, status/can-merge, size/XXL

#2133 dep: update tidb to fix memory leak
  .golangci.yml
  dm/ctl/common/util.go
  go.mod
  go.sum
  tests/shardddl4_1/run.sh
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XXL

#2140 relay: fix `no such file or directory` for start-relay command
  relay/relay.go
  relay/writer/file.go
  tests/sharding2/conf/source2.yaml
  tests/sharding2/run.sh
Labels: status/LGT2, type/bug-fix, needs-update-release-note, status/can-merge, size/M

#2083 openapi: add relay log related API
  _utils/terror_gen/errors_release.txt
  dm/master/openapi.go
  dm/master/openapi_test.go
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
  dm/worker/server_test.go
  dm/worker/source_worker.go
  dm/worker/source_worker_test.go
  errors.toml
  openapi/gen.server.go
  openapi/gen.types.go
  openapi/spec/dm.yaml
  pkg/terror/error_list.go
  tests/openapi/client/openapi_source_check
  tests/openapi/run.sh
Labels: needs-update-docs, status/LGT2, status/PTAL, needs-update-release-note, needs-cherry-pick-release-2.0, status/can-merge, size/XXL

#2130 syncer: replace `{schema, table}` with `filter.Table` Part 3
  _utils/terror_gen/errors_release.txt
  errors.toml
  pkg/parser/common.go
  pkg/schema/tracker.go
  pkg/schema/tracker_test.go
  pkg/terror/error_list.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/ddl.go
  syncer/ddl_test.go
  syncer/dml.go
  syncer/expr_filter_group.go
  syncer/expr_filter_group_test.go
  syncer/job.go
  syncer/job_test.go
  syncer/online-ddl-tools/online_ddl.go
  syncer/optimist.go
  syncer/safe-mode/mode.go
  syncer/safe-mode/mode_test.go
  syncer/schema.go
  syncer/syncer.go
  syncer/syncer_test.go
  syncer/util.go
  syncer/util_test.go
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XXL

#2100 test: remove mysql in pkg relay
  pkg/binlog/reader/util.go
  relay/relay.go
  relay/relay_test.go
  relay/util_test.go
  tests/new_relay/run.sh
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XL

#2121 *: remove deprecated heartbeat code
  dm/config/subtask.go
  dm/config/task.go
  relay/relay.go
  syncer/heartbeat.go
  syncer/heartbeat_test.go
  syncer/metrics/metrics.go
  syncer/syncer.go
Labels: status/LGT2, status/PTAL, needs-cherry-pick-release-2.0, status/can-merge, size/XXL

#2153 test: fix integration test which may cause case fail sometimes
  tests/_utils/test_prepare
  tests/all_mode/run.sh
Labels: status/LGT2, contribution, needs-cherry-pick-release-2.0, first-time-contributor, status/can-merge, size/XS

#2143 cherrypick #2065 #2094 and #2133 to release-2.0.7
  .golangci.yml
  dm/ctl/common/util.go
  dumpling/dumpling_test.go
  go.mod
  go.sum
  pkg/log/log.go
  pkg/log/log_test.go
  pkg/schema/tracker.go
  pkg/utils/common.go
  pkg/utils/db_test.go
  syncer/error.go
  syncer/syncer.go
  tests/README.md
  tests/handle_error/run.sh
  tests/handle_error_2/run.sh
  tests/handle_error_3/run.sh
  tests/import_goroutine_leak/run.sh
  tests/others_integration_1.txt
  tests/others_integration_2.txt
  tests/run.sh
  tests/shardddl4_1/run.sh
Labels: status/LGT2, status/can-merge, size/XXL

#2139 onlineddl: support regular expressions rules for PT/GH-OST
  _utils/terror_gen/errors_release.txt
  dm/config/subtask.go
  dm/config/task.go
  dm/config/task_test.go
  errors.toml
  pkg/terror/error_list.go
  syncer/job.go
  syncer/online-ddl-tools/online_ddl.go
  syncer/safe-mode/mode.go
  syncer/syncer_test.go
  tests/dmctl_basic/conf/get_task.yaml
  tests/import_v10x/conf/task.yaml
Labels: status/LGT2, needs-cherry-pick-release-2.0, first-time-contributor, status/can-merge, size/L

#2147 syncer: refactor `filter.go`
  syncer/ddl.go
  syncer/ddl_test.go
  syncer/filter.go
  syncer/filter_test.go
  syncer/syncer.go
  syncer/syncer_test.go
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XXL

#2158 *: update tools and fix lint
  .golangci.yml
  Makefile
  dm/ctl/ctl.go
  relay/meta.go
  syncer/syncer_test.go
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XXL

#2160 .*: update changelog for v2.0.7
  CHANGELOG.md
Labels: status/LGT2, status/PTAL, status/can-merge, size/S

#2167 dmctl: typo fix
  CHANGELOG.md
  dm/ctl/common/config.go
Labels: status/LGT2, status/PTAL, needs-cherry-pick-release-2.0, status/can-merge, size/XS

#2120 test: remove mysql in pkg syncer
  dm/config/subtask.go
  dm/master/openapi_test.go
  dm/portal/api_test.go
  dm/worker/source_worker_test.go
  dumpling/dumpling_test.go
  go.sum
  step_by_step_contribute.md
  syncer/dbconn/upstream_db_test.go
  syncer/ddl_test.go
  syncer/handle_error_test.go
  syncer/syncer_test.go
  tests/README.md
  tests/sql_mode/conf/diff_config.toml
  tests/sql_mode/data/db1.prepare.sql
  tests/sql_mode/data/timezone.America-Phoenix.sql
  tests/sql_mode/data/timezone.Asia-Shanghai.sql
  tests/sql_mode/run.sh
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XXL

#2161 .*: cherry-pick #2139 and update change log for v2.0.7
  CHANGELOG.md
  _utils/terror_gen/errors_release.txt
  dm/config/subtask.go
  dm/config/task.go
  dm/config/task_test.go
  errors.toml
  pkg/terror/error_list.go
  syncer/online-ddl-tools/online_ddl.go
  syncer/syncer_test.go
  tests/dmctl_basic/conf/get_task.yaml
  tests/import_goroutine_leak/run.sh
  tests/import_v10x/conf/task.yaml
Labels: status/LGT2, status/PTAL, status/can-merge, size/L

#2152 syncer: split `tables [][]*filter.Table` to `sourceTables []*filter.Table` and `targetTables []*filter.Table`
  syncer/ddl.go
  syncer/ddl_test.go
  syncer/dml.go
  syncer/job.go
  syncer/job_test.go
  syncer/optimist.go
  syncer/schema.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/downstream_more_column/run.sh
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XL

#2150 ha: fix old cancel not call and adjust lint
  pkg/ha/keepalive.go
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/S

#2171 test: support verify CI
  Makefile
  tools/Makefile
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/M

#2141 openapi: add start/stop task API
  dm/config/subtask.go
  dm/config/task.go
  dm/config/task_test.go
  dm/master/openapi.go
  dm/master/openapi_test.go
  dm/master/scheduler/scheduler.go
  dm/master/server.go
  go.mod
  openapi/gen.server.go
  openapi/gen.types.go
  openapi/spec/dm.yaml
  openapi/task.go
  openapi/task_test.go
  tests/openapi/client/openapi_source_check
  tests/openapi/client/openapi_task_check
  tests/openapi/run.sh
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XXL

#2166 [#2165] dmctl: change pause-task/resume-task/stop-task to support operate tasks bound to a source.
  dm/ctl/master/operate_task.go
  dm/ctl/master/operate_task_test.go
  dm/ctl/master/pause_task.go
  dm/ctl/master/resume_task.go
  dm/ctl/master/stop_task.go
  tests/dmctl_basic/check_list/pause_task.sh
  tests/dmctl_basic/check_list/resume_task.sh
  tests/dmctl_basic/check_list/stop_task.sh
  tests/dmctl_basic/conf/bar-task.yaml
  tests/dmctl_basic/conf/baz-task.yaml
  tests/dmctl_basic/conf/foo-task.yaml
  tests/dmctl_basic/run.sh
Labels: status/LGT2, needs-update-release-note, contribution, needs-cherry-pick-release-2.0, status/can-merge, size/XL

#2182 onlineddl: report an error when online ddl only matches only one regex
  _utils/terror_gen/errors_release.txt
  dm/config/subtask.go
  errors.toml
  pkg/terror/error_list.go
  syncer/ddl.go
  syncer/ddl_test.go
  syncer/online-ddl-tools/online_ddl.go
Labels: status/LGT2, status/PTAL, needs-cherry-pick-release-2.0, status/can-merge, size/L

#2176 github: use yml template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/question.yml
Labels: status/LGT2, contribution, first-time-contributor, status/can-merge, size/L

#2186 *: move from deprecated ioutil to os and io packages
  _utils/terror_gen/gen.go
  chaos/cases/source.go
  dm/config/security.go
  dm/config/security_test.go
  dm/config/source_config.go
  dm/config/source_config_test.go
  dm/config/task.go
  dm/config/task_test.go
  dm/ctl/common/util.go
  dm/ctl/master/config.go
  dm/ctl/master/get_config.go
  dm/master/bootstrap.go
  dm/master/bootstrap_test.go
  dm/master/config_test.go
  dm/master/etcd.go
  dm/master/etcd_test.go
  dm/master/server_test.go
  dm/portal/api.go
  dm/worker/server_test.go
  loader/loader.go
  loader/util_test.go
  monitoring/dashboards/dashboard.go
  pkg/binlog/writer/file_test.go
  pkg/dumpling/utils_test.go
  pkg/ha/source_test.go
  pkg/streamer/file_test.go
  pkg/streamer/reader_test.go
  pkg/utils/file.go
  pkg/utils/file_test.go
  pkg/utils/relay_test.go
  pkg/v1workermeta/api_test.go
  relay/meta_test.go
  relay/purger/file_test.go
  relay/purger/purger_test.go
  relay/relay_test.go
  relay/writer/file_test.go
  relay/writer/file_util_test.go
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/syncer_test.go
  tests/_dmctl_tools/check_master_http_apis.go
  tests/_dmctl_tools/check_master_online_http.go
  tests/_utils/send_lark_notify.go
  tests/utils/dmctl.go
Labels: status/LGT2, contribution, needs-cherry-pick-release-2.0, first-time-contributor, status/can-merge, size/XL

#2189 test: fix ctx timeout in advance before test success in ut
  dm/master/agent_pool_test.go
  dm/master/election_test.go
  dm/master/server_test.go
  pkg/election/election_test.go
  pkg/streamer/reader_test.go
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/S
