Repository pingcap/dm, pull requests merged in 2021-02, with the labels that each got.

#1413 ci: build on both Ubuntu and macOS
  .github/workflows/check-and-build.yml
Labels: needs-cherry-pick-2.0, status/LGT1, type/test

#1410 config: add warning, when users set configuration to mydumper/loader/syncer b…
  _utils/terror_gen/errors_release.txt
  dm/config/task.go
  dm/config/task_test.go
  errors.toml
  pkg/terror/error_list.go
Labels: first-time-contributor, needs-cherry-pick-2.0, needs-update-release-note, status/LGT1

#1364 auto master-slave switch
  .github/workflows/upgrade-via-tiup.yml
  .github/workflows/upstream-switch.yml
  _utils/terror_gen/errors_release.txt
  errors.toml
  pkg/streamer/file.go
  pkg/streamer/file_test.go
  pkg/streamer/reader.go
  pkg/streamer/reader_test.go
  pkg/terror/error_list.go
  relay/relay.go
  tests/upstream_switch/Dockerfile
  tests/upstream_switch/case.sh
  tests/upstream_switch/chk_mysql.sh
  tests/upstream_switch/conf/diff_config.toml
  tests/upstream_switch/conf/dm-master.toml
  tests/upstream_switch/conf/dm-worker1.toml
  tests/upstream_switch/conf/dm-worker2.toml
  tests/upstream_switch/conf/source1.yaml
  tests/upstream_switch/conf/source2.yaml
  tests/upstream_switch/conf/task-pessimistic.yaml
  tests/upstream_switch/docker-compose.yml
  tests/upstream_switch/init.sh
  tests/upstream_switch/lib.sh
  tests/upstream_switch/mysql57_master/keepalive.conf
  tests/upstream_switch/mysql57_slave/keepalive.conf
  tests/upstream_switch/mysql8_master/keepalive.conf
  tests/upstream_switch/mysql8_slave/keepalive.conf
Labels: needs-cherry-pick-2.0, priority/normal, status/LGT1, status/PTAL

#1396 worker, ha: For errors that can only be attempted a limited number of times, the number of attempts is limited
  dm/worker/join.go
  dm/worker/server.go
  dm/worker/server_test.go
  pkg/etcdutil/etcdutil.go
  pkg/ha/bound.go
  pkg/ha/source.go
Labels: first-time-contributor, needs-cherry-pick-2.0, needs-update-release-note, status/LGT2, type/bug-fix

#1405 worker, ha: increase keepalive TTL to 1 minute, and to 30 minutes if relay enabled
  dm/worker/config.go
  dm/worker/join.go
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/worker_test.go
  pkg/ha/keepalive.go
  tests/dmctl_basic/conf/get_worker1.toml
  tests/dmctl_basic/conf/get_worker2.toml
  tests/incremental_mode/run.sh
Labels: needs-cherry-pick-2.0, needs-update-docs, needs-update-release-note, status/LGT2, status/PTAL

#1424 dep: sort GTID set for printing
  go.mod
  go.sum
  pkg/gtid/gtid_test.go
Labels: needs-cherry-pick-2.0

#1400 relay: don't purge relay logs when connected to last source
  dm/worker/relay.go
  pkg/gtid/gtid.go
  pkg/gtid/gtid_test.go
  pkg/v1dbschema/schema.go
  relay/meta.go
  relay/meta_test.go
  relay/relay.go
  relay/relay_test.go
  relay/writer/file.go
  relay/writer/file_test.go
  relay/writer/writer.go
  tests/ha_cases/run.sh
  tests/relay_interrupt/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT1, status/PTAL

#1436 tests: remove `use-rowid` and `sql-mode` properties configuration of integration tests
  tests/all_mode/conf/diff_config.toml
  tests/compatibility/conf/diff_config.toml
  tests/dm_syncer/conf/diff_config.toml
  tests/dm_syncer/conf/diff_config_blalist.toml
  tests/dm_syncer/conf/diff_config_route_rules.toml
  tests/dmctl_basic/conf/diff_config.toml
  tests/dmctl_command/conf/diff_config.toml
  tests/drop_column_with_index/conf/diff_config.toml
  tests/full_mode/conf/diff_config.toml
  tests/ha/conf/diff_config.toml
  tests/ha_cases/conf/diff-standalone-config.toml
  tests/ha_cases/conf/diff_config.toml
  tests/ha_cases/conf/diff_config_multi_task.toml
  tests/ha_master/conf/diff_config.toml
  tests/handle_error/conf/diff_config.toml
  tests/http_apis/conf/diff_config.toml
  tests/import_v10x/conf/diff_config.toml
  tests/incremental_mode/conf/diff_config.toml
  tests/initial_unit/conf/diff_config.toml
  tests/load_interrupt/conf/diff_config.toml
  tests/many_tables/conf/diff_config.toml
  tests/online_ddl/conf/diff_config.toml
  tests/print_status/conf/diff_config.toml
  tests/relay_interrupt/conf/diff_config.toml
  tests/retry_cancel/conf/diff_config.toml
  tests/safe_mode/conf/diff_config.toml
  tests/sequence_safe_mode/conf/diff_config.toml
  tests/sequence_sharding/conf/diff_config.toml
  tests/sequence_sharding_optimistic/conf/diff_config.toml
  tests/sequence_sharding_removemeta/conf/diff_config.toml
  tests/shardddl1/conf/diff_config.toml
  tests/shardddl2/conf/diff_config.toml
  tests/shardddl3/conf/diff_config.toml
  tests/sharding/conf/diff_config.toml
  tests/sharding2/conf/diff_config.toml
  tests/start_task/conf/diff_config.toml
Labels: first-time-contributor, needs-cherry-pick-2.0

#1437 dmctl: refine help message and enable test
  dm/ctl/master/pause_relay.go
  dm/ctl/master/purge_relay.go
  dm/ctl/master/resume_relay.go
  pkg/streamer/hub.go
  tests/dmctl_basic/conf/dm-task.yaml
  tests/dmctl_basic/conf/get_task.yaml
  tests/dmctl_basic/run.sh
Labels: needs-cherry-pick-2.0, needs-update-docs, status/LGT1, status/PTAL

#1430 gtid, relay: use `gtid_purged` to handle gap in Previous_gtids event
  .github/workflows/check-and-build.yml
  pkg/gtid/gtid.go
  pkg/gtid/gtid_test.go
  pkg/utils/db.go
  pkg/v1dbschema/schema.go
  pkg/v1dbschema/schema_test.go
  relay/relay.go
  relay/relay_test.go
  tests/gtid/conf/diff_config.toml
  tests/gtid/conf/dm-master.toml
  tests/gtid/conf/dm-task.yaml
  tests/gtid/conf/dm-worker1.toml
  tests/gtid/conf/dm-worker2.toml
  tests/gtid/conf/source1.yaml
  tests/gtid/conf/source2.yaml
  tests/gtid/data/db1.increment.sql
  tests/gtid/data/db1.prepare.sql
  tests/gtid/data/db2.increment.sql
  tests/gtid/data/db2.prepare.sql
  tests/gtid/run.sh
  tests/others_integration.txt
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT1, status/PTAL

#1438 *: refine metrics
  .gitignore
  dm/dm-ansible/conf/dm_worker.rules.yml
  dm/master/metrics/metrics.go
  dm/master/server.go
  monitoring/dashboards/dm.json
  monitoring/rules/dm_worker.rules.yml
  tests/_utils/check_metric
  tests/dmctl_basic/run.sh
Labels: needs-cherry-pick-2.0, needs-update-docs, needs-update-release-note, status/LGT1

#1446 dmctl: add ending peroid
  dm/ctl/master/pause_relay.go
  dm/ctl/master/purge_relay.go
  dm/ctl/master/resume_relay.go
Labels: needs-cherry-pick-2.0, status/PTAL

#1445 grafana: fix duplicate panel id and position
  dm/dm-ansible/scripts/dm.json
Labels: needs-cherry-pick-2.0, needs-update-dm-ansible, status/LGT1

#1461 master: disable grpc gateway of embedded etcd
  dm/master/config.go
  tests/ha_master/run.sh
  tests/tls/run.sh
Labels: needs-cherry-pick-2.0
