Repository pingcap/dm, pull requests merged in 2021-06, with the labels that each got.

#1723 syncer: fix syncer gtid auto switch from off to on
  dm/worker/server.go
  pkg/binlog/position.go
  pkg/binlog/position_test.go
  pkg/binlog/reader/reader.go
  pkg/binlog/reader/util.go
  pkg/streamer/streamer.go
  syncer/checkpoint.go
  syncer/syncer.go
  tests/adjust_gtid/conf/diff_config.toml
  tests/adjust_gtid/conf/dm-master.toml
  tests/adjust_gtid/conf/dm-task.yaml
  tests/adjust_gtid/conf/dm-worker1.toml
  tests/adjust_gtid/conf/dm-worker2.toml
  tests/adjust_gtid/conf/source1.yaml
  tests/adjust_gtid/conf/source2.yaml
  tests/adjust_gtid/data/db1.increment.sql
  tests/adjust_gtid/data/db1.prepare.sql
  tests/adjust_gtid/data/db2.increment.sql
  tests/adjust_gtid/data/db2.prepare.sql
  tests/adjust_gtid/run.sh
  tests/all_mode/run.sh
  tests/others_integration.txt
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, require-LGT1, size/XXL, status/LGT1, status/PTAL, status/can-merge

#1743 ci: try fix chaos mesh
  .github/workflows/chaos-mesh.yml
Labels: size/S, status/LGT2, status/PTAL, status/can-merge

#1748 relay: fix bug of relay metrics being recorded only once
  relay/metrics.go
Labels: contribution, first-time-contributor, needs-cherry-pick-release-2.0, needs-update-release-note, size/S, status/LGT2, status/can-merge

#1699 syncer: load table structure from dump files
  _utils/terror_gen/errors_release.txt
  errors.toml
  loader/loader.go
  loader/util.go
  pkg/terror/error_list.go
  pkg/utils/file.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/all_mode/run.sh
  tests/run.sh
  tests/safe_mode/run.sh
  tests/shardddl1/run.sh
  tests/sharding/run.sh
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, require-LGT1, size/XL, status/LGT1, status/can-merge

#1709 syncer: add metric replicationLagGauge back
  Makefile
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/worker/status.go
  pkg/utils/db.go
  pkg/utils/db_test.go
  syncer/db.go
  syncer/db_test.go
  syncer/job.go
  syncer/job_test.go
  syncer/metrics.go
  syncer/optimist.go
  syncer/syncer.go
  syncer/syncer_test.go
  tests/_utils/run_dm_ctl_with_retry
  tests/_utils/run_dm_ctl_with_tls_and_retry
  tests/all_mode/conf/dm-task.yaml
  tests/all_mode/data/db1.increment2.sql
  tests/all_mode/data/db2.increment2.sql
  tests/all_mode/run.sh
  tests/tls/run.sh
Labels: needs-cherry-pick-release-2.0, size/XXL, status/LGT2, status/PTAL, status/can-merge

#1764 syncer: fix replication lag when hanle-error
  syncer/err-operator/operator.go
  syncer/err-operator/operator_test.go
  syncer/syncer.go
Labels: needs-cherry-pick-release-2.0, size/S, status/LGT2, status/PTAL, status/can-merge

#1616 Quality reinforcement (11): fix unstable test cases
  dm/master/bootstrap_test.go
  dm/master/election_test.go
  dm/master/etcd_test.go
  dm/master/server_test.go
  pkg/election/election_test.go
  tests/README.md
  tests/_utils/shardddl_lib.sh
  tests/ha_master/run.sh
  tests/incremental_mode/run.sh
  tests/shardddl1/run.sh
  tests/shardddl2/run.sh
  tests/shardddl2_1/run.sh
  tests/shardddl4_1/run.sh
Labels: size/XXL, status/LGT2, status/PTAL, status/can-merge

#1750 dmctl: fix dmctl command to improve its usability
  cmd/dm-ctl/main.go
  dm/ctl/common/config.go
  dm/ctl/ctl.go
  dm/ctl/master/get_config.go
  tests/_utils/env_variables
  tests/_utils/get_leader
  tests/_utils/run_dm_ctl_cmd_mode
  tests/_utils/run_dm_ctl_with_rematch
  tests/_utils/run_dm_ctl_with_retry
  tests/_utils/wait_until_sync
  tests/dmctl_basic/check_list/dmctl.sh
  tests/dmctl_basic/check_list/get_config.sh
  tests/dmctl_basic/run.sh
  tests/dmctl_command/run.sh
  tests/handle_error/lib.sh
  tests/handle_error_2/lib.sh
  tests/handle_error_3/lib.sh
Labels: needs-cherry-pick-release-2.0, needs-update-docs, needs-update-release-note, size/XXL, status/LGT2, status/PTAL, status/can-merge

#1733 utils: don't panic when no row returned for SHOW MASTER STATUS
  _utils/terror_gen/errors_release.txt
  errors.toml
  pkg/terror/error_list.go
  pkg/utils/db.go
  pkg/utils/db_test.go
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, require-LGT1, size/M, status/LGT1, status/can-merge

#1777 syncer: adjust safemode duration to 2 * checkpointFlushInterval
  syncer/mode.go
  syncer/syncer_test.go
  tests/print_status/run.sh
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/S, status/LGT2, status/can-merge

#1752 syncer: don't skip jobs from same event when comparing table checkpoint
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/syncer.go
  tests/all_mode/data/db1.increment3.sql
  tests/all_mode/data/db2.increment3.sql
  tests/all_mode/run.sh
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/L, status/LGT2, status/can-merge

#1749 scheduler: full import scheduling
  _utils/terror_gen/errors_release.txt
  dm/common/common.go
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
  dm/master/server.go
  dm/worker/server_test.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  errors.toml
  loader/loader.go
  pkg/ha/load_task.go
  pkg/ha/load_task_test.go
  pkg/ha/source.go
  pkg/terror/error_list.go
  syncer/syncer.go
  tests/load_task/conf/diff_config1.toml
  tests/load_task/conf/diff_config2.toml
  tests/load_task/conf/diff_config3.toml
  tests/load_task/conf/diff_config4.toml
  tests/load_task/conf/dm-master.toml
  tests/load_task/conf/dm-task.yaml
  tests/load_task/conf/dm-task2.yaml
  tests/load_task/conf/dm-task3.yaml
  tests/load_task/conf/dm-task4.yaml
  tests/load_task/conf/dm-worker1.toml
  tests/load_task/conf/dm-worker2.toml
  tests/load_task/conf/dm-worker3.toml
  tests/load_task/conf/source1.yaml
  tests/load_task/conf/source2.yaml
  tests/load_task/data/db1.increment.sql
  tests/load_task/data/db1.prepare.sql
  tests/load_task/data/db2.increment.sql
  tests/load_task/data/db2.prepare.sql
  tests/load_task/run.sh
  tests/others_integration.txt
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/XXL, status/LGT2, status/PTAL, status/can-merge

#1786 changelog: add change log for v2.0.4
  CHANGELOG.md
Labels: needs-cherry-pick-release-2.0, size/M, status/LGT2, status/can-merge, type/CHANGELOG

#1783 syncer: don't skip jobs from same event when comparing table checkpoint (#1752)
  syncer/checkpoint.go
  syncer/checkpoint_test.go
  syncer/syncer.go
  tests/all_mode/data/db1.increment3.sql
  tests/all_mode/data/db2.increment3.sql
  tests/all_mode/run.sh
Labels: size/L, status/LGT2

#1794 changelog: add change log for v1.0.7
  .github/workflows/upgrade-via-tiup.yml
  CHANGELOG.md
  tests/tiup/upgrade-from-v1.sh
Labels: require-LGT1, size/S, status/LGT1, status/can-merge, type/CHANGELOG

#1789 test: add v2.0.4 in tiup upgrade test
  .github/workflows/upgrade-via-tiup.yml
Labels: needs-cherry-pick-release-2.0, require-LGT1, size/XS, status/LGT1, status/can-merge, type/test

#1767 syncer: remove useless code
  syncer/syncer.go
Labels: needs-cherry-pick-release-2.0, require-LGT1, size/S, status/LGT1, status/PTAL, status/can-merge

#1773 test: try fix etcd error in CI
  tests/_utils/shardddl_lib.sh
  tests/_utils/wait_process_exit
  tests/tiup/lib.sh
Labels: needs-cherry-pick-release-2.0, size/M, status/LGT2, status/can-merge

#1796 grafana: change some dashboard type to graph
  dm/dm-ansible/scripts/dm.json
  monitoring/readme.md
  tests/run.sh
Labels: size/XXL, status/LGT2, status/can-merge

#1809 syncer: fix syncer not being triggered by ticker
  syncer/syncer.go
  tests/only_dml/conf/dm-task.yaml
  tests/only_dml/run.sh
Labels: needs-cherry-pick-release-2.0, size/S, status/LGT2, status/PTAL, status/can-merge

#1812 pessimist: Fix Inconsistent DDL sequence error if same DDL replicate twice in sequence-sharding
  syncer/sharding-meta/shardmeta.go
  tests/shardddl1_1/run.sh
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/L, status/LGT2, status/PTAL, status/can-merge, type/bug-fix

#1820 loader: fix loader painc when not remove meta
  _utils/terror_gen/errors_release.txt
  errors.toml
  loader/checkpoint.go
  loader/loader.go
  pkg/terror/error_list.go
  tests/load_interrupt/run.sh
Labels: needs-cherry-pick-release-2.0, needs-update-docs, needs-update-release-note, size/M, status/LGT2, status/can-merge
