Repository pingcap/dm, pull requests merged in 2021-04, with the labels that each got.

#1551 shardddl/optimistic: use init-schema for table without info when recover lock
  dm/master/shardddl/optimist.go
  dm/master/shardddl/optimist_test.go
  pkg/shardddl/optimism/schema.go
  pkg/shardddl/optimism/schema_test.go
  tests/_utils/test_prepare
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, size/L, status/LGT2, status/can-merge

#1515 *: add start-relay/stop-relay command
  _utils/terror_gen/errors_release.txt
  dm/config/source_config.go
  dm/config/source_config_test.go
  dm/ctl/ctl.go
  dm/ctl/master/start_relay.go
  dm/ctl/master/stop_relay.go
  dm/master/bootstrap_test.go
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
  dm/master/server.go
  dm/pb/dmmaster.pb.go
  dm/proto/dmmaster.proto
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  errors.toml
  pkg/ha/bound.go
  pkg/ha/relay.go
  pkg/ha/stage.go
  pkg/ha/worker.go
  pkg/ha/worker_test.go
  pkg/terror/error_list.go
  syncer/syncer.go
  tests/all_mode/run.sh
  tests/dmctl_basic/check_list/pause_relay.sh
  tests/dmctl_basic/check_list/purge_relay.sh
  tests/dmctl_basic/check_list/query_status.sh
  tests/dmctl_basic/check_list/start_relay.sh
  tests/dmctl_basic/check_list/stop_relay.sh
  tests/dmctl_basic/run.sh
  tests/dmctl_command/run.sh
  tests/drop_column_with_index/run.sh
  tests/full_mode/run.sh
  tests/gtid/run.sh
  tests/ha/run.sh
  tests/ha_cases/lib.sh
  tests/ha_cases/run.sh
  tests/ha_master/run.sh
  tests/handle_error/run.sh
  tests/http_apis/run.sh
  tests/import_v10x/run.sh
  tests/incremental_mode/run.sh
  tests/initial_unit/run.sh
  tests/online_ddl/run.sh
  tests/only_dml/run.sh
  tests/relay_interrupt/run.sh
  tests/sequence_sharding_optimistic/run.sh
  tests/shardddl3/run.sh
  tests/sharding2/run.sh
  tests/upstream_switch/case.sh
Labels: needs-cherry-pick-2.0, size/XXL, status/LGT2, status/can-merge

#1493 test: add test cases for shardddl
  go.mod
  go.sum
  tests/_utils/run_dm_ctl_with_rematch
  tests/shardddl3/conf/double-source-optimistic.yaml
  tests/shardddl3/conf/double-source-pessimistic.yaml
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-2.0, size/XXL, status/LGT2, status/PTAL, status/can-merge

#1528 test: when VIP upstream switching, continue from relay.meta
  relay/relay.go
  tests/all_mode/conf/source1.yaml
  tests/all_mode/data/db1.increment0.sql
  tests/all_mode/data/db2.increment0.sql
  tests/all_mode/run.sh
Labels: needs-cherry-pick-2.0, size/M, status/LGT2, status/PTAL, status/can-merge

#1552 binlog/event: improve parsing MariaDB status vars in binlog
  pkg/binlog/event/util.go
  pkg/binlog/event/util_test.go
Labels: needs-cherry-pick-2.0, needs-update-release-note, require-LGT1, size/S, status/LGT1, status/can-merge

#1550 dep, schema: update tidb and add clustered index test
  go.mod
  go.sum
  pkg/schema/tracker.go
  pkg/schema/tracker_test.go
  syncer/syncer_test.go
Labels: needs-cherry-pick-2.0, size/L, status/LGT2, status/can-merge

#1566 dep: update dumpling dependency
  dumpling/dumpling.go
  dumpling/dumpling_test.go
  go.mod
  go.sum
Labels: needs-cherry-pick-2.0, size/S, status/LGT2, status/can-merge

#1533 *: `query-status -s` and purge-relay send to all relay worker
  cmd/dm-worker/main.go
  dm/config/source_config.go
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
  dm/master/server.go
  dm/master/server_test.go
  dm/worker/config.go
  dm/worker/server.go
  dm/worker/worker.go
  pkg/ha/keepalive.go
  pkg/ha/source.go
  pkg/streamer/hub.go
  pkg/utils/db.go
  relay/relay.go
  syncer/streamer_controller.go
  tests/_utils/test_prepare
  tests/all_mode/run.sh
  tests/dmctl_basic/check_list/query_status.sh
  tests/ha_cases/run.sh
  tests/new_relay/conf/diff_config.toml
  tests/new_relay/conf/dm-master.toml
  tests/new_relay/conf/dm-task.yaml
  tests/new_relay/conf/dm-worker1.toml
  tests/new_relay/conf/dm-worker2.toml
  tests/new_relay/conf/dm-worker3.toml
  tests/new_relay/conf/source1.yaml
  tests/new_relay/data/db1.increment.sql
  tests/new_relay/data/db1.increment2.sql
  tests/new_relay/data/db1.increment3.sql
  tests/new_relay/data/db1.increment4.sql
  tests/new_relay/data/db1.prepare.sql
  tests/new_relay/run.sh
  tests/others_integration.txt
  tests/start_task/run.sh
Labels: needs-cherry-pick-2.0, size/XXL, status/LGT2, status/can-merge

#1540 common, upgrade: return `/` ternimated string when partitially encode keys
  dm/common/common.go
  dm/common/common_test.go
  pkg/shardddl/optimism/operation.go
  pkg/shardddl/pessimism/operation.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  pkg/upgrade/version.go
Labels: needs-cherry-pick-2.0, require-LGT1, size/L, status/LGT1, status/can-merge

#1557 *: add start-relay/stop-relay command (#1515)
  _utils/terror_gen/errors_release.txt
  dm/config/source_config.go
  dm/config/source_config_test.go
  dm/ctl/ctl.go
  dm/ctl/master/start_relay.go
  dm/ctl/master/stop_relay.go
  dm/master/bootstrap_test.go
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
  dm/master/server.go
  dm/pb/dmmaster.pb.go
  dm/proto/dmmaster.proto
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  errors.toml
  pkg/ha/bound.go
  pkg/ha/relay.go
  pkg/ha/stage.go
  pkg/ha/worker.go
  pkg/ha/worker_test.go
  pkg/terror/error_list.go
  syncer/syncer.go
  tests/all_mode/run.sh
  tests/dmctl_basic/check_list/pause_relay.sh
  tests/dmctl_basic/check_list/purge_relay.sh
  tests/dmctl_basic/check_list/query_status.sh
  tests/dmctl_basic/check_list/start_relay.sh
  tests/dmctl_basic/check_list/stop_relay.sh
  tests/dmctl_basic/run.sh
  tests/dmctl_command/run.sh
  tests/drop_column_with_index/run.sh
  tests/full_mode/run.sh
  tests/gtid/run.sh
  tests/ha/run.sh
  tests/ha_cases/lib.sh
  tests/ha_cases/run.sh
  tests/ha_master/run.sh
  tests/handle_error/run.sh
  tests/http_apis/run.sh
  tests/import_v10x/run.sh
  tests/incremental_mode/run.sh
  tests/initial_unit/run.sh
  tests/online_ddl/run.sh
  tests/only_dml/run.sh
  tests/relay_interrupt/run.sh
  tests/sequence_sharding_optimistic/run.sh
  tests/shardddl3/run.sh
  tests/sharding2/run.sh
  tests/upstream_switch/case.sh
Labels: size/XXL, status/LGT1

#1573 *: `query-status -s` and purge-relay send to all relay worker (#1533)
  cmd/dm-worker/main.go
  dm/config/source_config.go
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
  dm/master/server.go
  dm/master/server_test.go
  dm/worker/config.go
  dm/worker/server.go
  dm/worker/worker.go
  pkg/ha/keepalive.go
  pkg/ha/source.go
  pkg/streamer/hub.go
  pkg/utils/db.go
  relay/relay.go
  syncer/streamer_controller.go
  tests/_utils/test_prepare
  tests/all_mode/run.sh
  tests/dmctl_basic/check_list/query_status.sh
  tests/ha_cases/run.sh
  tests/new_relay/conf/diff_config.toml
  tests/new_relay/conf/dm-master.toml
  tests/new_relay/conf/dm-task.yaml
  tests/new_relay/conf/dm-worker1.toml
  tests/new_relay/conf/dm-worker2.toml
  tests/new_relay/conf/dm-worker3.toml
  tests/new_relay/conf/source1.yaml
  tests/new_relay/data/db1.increment.sql
  tests/new_relay/data/db1.increment2.sql
  tests/new_relay/data/db1.increment3.sql
  tests/new_relay/data/db1.increment4.sql
  tests/new_relay/data/db1.prepare.sql
  tests/new_relay/run.sh
  tests/others_integration.txt
  tests/start_task/run.sh
Labels: size/XXL

#1574 test: run apt update to avoid outdated link
  tests/tiup/upgrade-from-v1.sh
Labels: size/XS, status/LGT2, status/can-merge

#1571 CHANGELOG: update release note for 2.0.2
  CHANGELOG.md
Labels: needs-cherry-pick-2.0, require-LGT1, size/M, status/LGT1, status/can-merge

#1575 conn: refine TLS configuration
  dm/master/server.go
  dumpling/dumpling.go
  pkg/binlog/reader/tcp.go
  pkg/conn/basedb.go
  relay/relay.go
  relay/relay_test.go
  relay/util_test.go
  syncer/heartbeat.go
Labels: needs-cherry-pick-2.0, size/L, status/LGT2, status/can-merge

#1577 ansible: Update inventory.ini
  dm/dm-ansible/inventory.ini
Labels: size/XS

#1559 shardddl: fix optimistic bug
  dm/common/common.go
  dm/master/server_test.go
  dm/master/shardddl/optimist.go
  dm/master/shardddl/optimist_test.go
  dm/worker/task_checker_test.go
  go.sum
  pkg/retry/errors.go
  pkg/shardddl/optimism/column.go
  pkg/shardddl/optimism/column_test.go
  pkg/shardddl/optimism/info.go
  pkg/shardddl/optimism/info_test.go
  pkg/shardddl/optimism/keeper.go
  pkg/shardddl/optimism/keeper_test.go
  pkg/shardddl/optimism/lock.go
  pkg/shardddl/optimism/lock_test.go
  pkg/shardddl/optimism/operation.go
  pkg/shardddl/optimism/operation_test.go
  pkg/shardddl/optimism/ops.go
  pkg/shardddl/optimism/ops_test.go
  syncer/optimist.go
  syncer/schema.go
  syncer/shardddl/optimist_test.go
  syncer/syncer.go
  tests/shardddl2/run.sh
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-2.0, size/XXL, status/LGT2, status/PTAL, status/can-merge, type/bug-fix

#1581 CHANGELOG: fix wrong date
  CHANGELOG.md
Labels: require-LGT1, size/XS, status/LGT1, status/can-merge

#1582 CHANGELOG: fix wrong date
  CHANGELOG.md
Labels: size/XS, status/LGT1

#1583 CHANGELOG, actions: fix some typo when release
  .github/workflows/upgrade-via-tiup.yml
  CHANGELOG.md
Labels: require-LGT1, size/XS, status/LGT1, status/can-merge

#1567 test: check worker is alive before adding source
  tests/upstream_switch/case.sh
Labels: needs-cherry-pick-2.0, require-LGT1, size/XS, status/LGT1, status/can-merge

#1589 actions: skip outdated actions and update version of an action
  .github/workflows/chaos-mesh.yml
  .github/workflows/check-and-build.yml
Labels: needs-cherry-pick-2.0, require-LGT1, size/S, status/LGT1, status/can-merge

#1516 chaos: support optimistic mode for chaos test
  .github/workflows/chaos-mesh.yml
  .github/workflows/upgrade-via-tiup.yml
  chaos/cases/cases.go
  chaos/cases/db.go
  chaos/cases/generator.go
  chaos/cases/source.go
  chaos/cases/stmt.go
  chaos/cases/task.go
  chaos/manifests/dm-master.yaml
  chaos/manifests/dm-worker.yaml
  chaos/manifests/io-chaos-dm.yaml
  chaos/manifests/network-emulation-dm.yaml
  chaos/manifests/pod-failure-dm.yaml
  chaos/manifests/pod-kill-dm.yaml
  loader/loader.go
  pkg/shardddl/optimism/lock.go
Labels: needs-cherry-pick-2.0, require-LGT1, size/XXL, status/LGT1, status/PTAL, type/test

#1412 Quality reinforcement (9): fix unstable test cases
  dm/master/server_test.go
  dm/worker/server_test.go
  pkg/election/election_test.go
  pkg/shardddl/optimism/info_test.go
  relay/purger/purger.go
  relay/relay_test.go
  tests/all_mode/run.sh
  tests/only_dml/run.sh
  tests/shardddl3/conf/source1.yaml
  tests/shardddl3/conf/source2.yaml
  tests/sharding/run.sh
Labels: needs-cherry-pick-2.0, require-LGT1, size/L, status/LGT1, status/can-merge

#1585 syncer: remove improper ignored error
  syncer/error.go
  tests/all_mode/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, require-LGT1, size/S, status/LGT1, status/can-merge

#1591 test: try split large integration test cases
  syncer/syncer.go
  tests/ha_cases/run.sh
  tests/ha_cases2/conf/diff-standalone-config.toml
  tests/ha_cases2/conf/diff_config.toml
  tests/ha_cases2/conf/diff_config_multi_task.toml
  tests/ha_cases2/conf/dm-master-join1.toml
  tests/ha_cases2/conf/dm-master-join2.toml
  tests/ha_cases2/conf/dm-master-join3.toml
  tests/ha_cases2/conf/dm-master-join4.toml
  tests/ha_cases2/conf/dm-master-join5.toml
  tests/ha_cases2/conf/dm-master1.toml
  tests/ha_cases2/conf/dm-master2.toml
  tests/ha_cases2/conf/dm-master3.toml
  tests/ha_cases2/conf/dm-task.yaml
  tests/ha_cases2/conf/dm-task2.yaml
  tests/ha_cases2/conf/dm-worker-join1.toml
  tests/ha_cases2/conf/dm-worker-join2.toml
  tests/ha_cases2/conf/dm-worker1.toml
  tests/ha_cases2/conf/dm-worker2.toml
  tests/ha_cases2/conf/dm-worker3.toml
  tests/ha_cases2/conf/dm-worker4.toml
  tests/ha_cases2/conf/dm-worker5.toml
  tests/ha_cases2/conf/source1.yaml
  tests/ha_cases2/conf/source2.yaml
  tests/ha_cases2/conf/standalone-task.yaml
  tests/ha_cases2/conf/standalone-task2.yaml
  tests/ha_cases2/data/db1.increment.sql
  tests/ha_cases2/data/db1.increment2.sql
  tests/ha_cases2/data/db1.prepare.sql
  tests/ha_cases2/data/db2.increment.sql
  tests/ha_cases2/data/db2.increment2.sql
  tests/ha_cases2/data/db2.prepare.sql
  tests/ha_cases2/lib.sh
  tests/ha_cases2/run.sh
  tests/shardddl1/run.sh
  tests/shardddl3/run.sh
  tests/shardddl4/conf/diff_config.toml
  tests/shardddl4/conf/dm-master.toml
  tests/shardddl4/conf/dm-worker1.toml
  tests/shardddl4/conf/dm-worker2.toml
  tests/shardddl4/conf/double-source-optimistic.yaml
  tests/shardddl4/conf/double-source-pessimistic.yaml
  tests/shardddl4/conf/single-source-optimistic-2.yaml
  tests/shardddl4/conf/single-source-optimistic.yaml
  tests/shardddl4/conf/single-source-pessimistic-2.yaml
  tests/shardddl4/conf/single-source-pessimistic.yaml
  tests/shardddl4/conf/source1.yaml
  tests/shardddl4/conf/source2.yaml
  tests/shardddl4/conf/tidb-alter-pk-config.toml
  tests/shardddl4/run.sh
Labels: needs-cherry-pick-2.0, require-LGT1, size/XXL, status/LGT1, status/can-merge

#1601 Quality reinforcement (10): fix unstable test cases
  _utils/terror_gen/errors_release.txt
  chaos/manifests/sources.yaml
  dm/worker/join.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  errors.toml
  pkg/election/election_test.go
  pkg/terror/error_list.go
  tests/ha_cases/run.sh
  tests/shardddl2/run.sh
Labels: require-LGT1, size/M, status/LGT1, status/can-merge

#1587 dmctl, master: refine source behaviour in `operate-source`
  dm/ctl/master/operate_source.go
  dm/master/server.go
  tests/dmctl_basic/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, size/M, status/LGT2, status/can-merge

#1605 master: support unlock-ddl-lock after stop-task
  dm/master/server.go
  tests/sequence_sharding_optimistic/run.sh
  tests/sequence_sharding_removemeta/data/db1.increment2.sql
  tests/sequence_sharding_removemeta/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, size/M, status/LGT2, status/can-merge

#1606 worker: delete taskState when task is stopped/finished
  dm/dm-ansible/scripts/dm.json
  dm/dm-ansible/scripts/dm_instances.json
  dm/worker/metrics.go
  dm/worker/subtask.go
  tests/_utils/check_metric_not_contains
  tests/all_mode/run.sh
  tests/full_mode/run.sh
Labels: needs-cherry-pick-2.0, needs-update-docs, needs-update-release-note, size/M, status/LGT2, status/can-merge

#1613 dep: update go-mysql
  Makefile
  go.mod
  go.sum
Labels: first-time-contributor, needs-cherry-pick-2.0, size/M, status/LGT2, status/can-merge

#1610 check: add error/warn count for check-task
  checker/check_test.go
  checker/checker.go
  checker/cmd.go
  dm/ctl/common/config.go
  dm/ctl/master/check_task.go
  dm/master/server.go
  dm/master/server_test.go
  dm/pb/dmmaster.pb.go
  dm/pbmock/dmmaster.go
  dm/pbmock/dmworker.go
  dm/proto/dmmaster.proto
  tests/dmctl_basic/check_list/check_task.sh
  tests/dmctl_basic/conf/dm-task3.yaml
  tests/dmctl_basic/data/db1.prepare.sql
  tests/dmctl_basic/run.sh
  tools/go.mod
  tools/go.sum
Labels: needs-cherry-pick-2.0, size/XXL, status/LGT2, status/PTAL, status/can-merge, type/bug-fix

#1615 *: only use go.uber.org/atomic as atomic dependency
  checker/checker.go
  debug-tools/binlog-event-blackhole/fetcher.go
  dm/master/config.go
  dm/master/election.go
  dm/master/server.go
  dm/master/server_test.go
  dm/master/workerrpc/rawgrpc.go
  dm/worker/relay.go
  dm/worker/relay_test.go
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/subtask.go
  dm/worker/task_checker.go
  dm/worker/task_checker_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  dumpling/dumpling.go
  go.mod
  go.sum
  loader/loader.go
  loader/status.go
  pkg/atomic2/atomic.go
  pkg/atomic2/atomic_test.go
  pkg/binlog/reader/file.go
  pkg/binlog/writer/file.go
  pkg/election/election.go
  pkg/utils/file.go
  relay/meta.go
  relay/purger/purger.go
  relay/purger/purger_test.go
  relay/purger/strategy_filename.go
  relay/purger/strategy_inactive.go
  relay/purger/strategy_space.go
  relay/purger/strategy_time.go
  relay/relay.go
  relay/writer/file.go
  relay/writer/file_test.go
  syncer/optimist.go
  syncer/status.go
  syncer/syncer.go
Labels: needs-cherry-pick-2.0, size/XXL, status/LGT2, status/can-merge

#1625 *: update docs
  CONTRIBUTING.md
  README.md
  step_by_step_contribute.md
  tests/README.md
  tools/Makefile
Labels: size/M, status/LGT2, status/PTAL, status/can-merge

#1629 *: update run integration_test doc
  tests/README.md
  tests/all_mode/run.sh
Labels: size/S, status/LGT2, status/can-merge

#1619 *: only get master status once when query-status
  dm/unit/unit.go
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/status.go
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  dumpling/dumpling.go
  loader/status.go
  pkg/utils/db.go
  pkg/utils/util.go
  pkg/utils/util_test.go
  syncer/status.go
  syncer/syncer_test.go
Labels: needs-cherry-pick-2.0, size/XL, status/LGT2, status/can-merge

#1618 master, pessimism: remove ddl-lock metrics when remove the lock
  dm/master/metrics/metrics.go
  dm/master/server.go
  dm/master/shardddl/pessimist.go
  pkg/shardddl/pessimism/keeper.go
  tests/sequence_sharding_removemeta/run.sh
Labels: already-cherry-pick-2.0, needs-update-release-note, size/S, status/LGT2, status/can-merge

#1628 build: add more arch and os for build
  .github/workflows/check-and-build.yml
  go.sum
Labels: needs-cherry-pick-2.0, size/M, status/LGT2, status/can-merge

#1634 dmctl: show help msg before validate cfg #1564
  cmd/dm-ctl/main.go
  dm/ctl/common/config.go
  dm/master/metrics/metrics.go
  dm/worker/worker.go
  tests/dmctl_command/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, size/S, status/LGT2, status/PTAL, status/can-merge

#1641 Hotfix again
  .gitignore
  dm/config/subtask.go
  dm/config/task.go
  syncer/ddl.go
  syncer/sharding_group.go
  syncer/syncer.go
  tests/all_mode/conf/diff_config.toml
  tests/compatibility/conf/diff_config.toml
  tests/dmctl_basic/conf/diff_config.toml
  tests/dmctl_command/conf/diff_config.toml
  tests/full_mode/conf/diff_config.toml
  tests/http_apis/conf/diff_config.toml
  tests/incremental_mode/conf/diff_config.toml
  tests/initial_unit/conf/diff_config.toml
  tests/load_interrupt/conf/diff_config.toml
  tests/online_ddl/conf/diff_config.toml
  tests/print_status/conf/diff_config.toml
  tests/relay_interrupt/conf/diff_config.toml
  tests/retry_cancel/conf/diff_config.toml
  tests/safe_mode/conf/diff_config.toml
  tests/sequence_safe_mode/conf/diff_config.toml
  tests/sequence_sharding/conf/diff_config.toml
  tests/sequence_sharding/conf/dm-task.yaml
  tests/sequence_sharding/data/db1.increment.sql
  tests/sharding/conf/diff_config.toml
  tests/start_task/conf/diff_config.toml
Labels: size/L, status/LGT2

#1639 scheduler: close workers grpc connections timely
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
  dm/master/server.go
  dm/master/workerrpc/rawgrpc.go
Labels: needs-cherry-pick-2.0, needs-update-release-note, severity/critical, size/M, status/LGT2, status/PTAL, status/can-merge, type/bug-fix
