Repository pingcap/dm, pull requests merged in 2021-08, with the labels that each got.

#1946 test: fix unstable evict test
  pkg/election/election.go
  tests/ha_master/run.sh
Labels: needs-cherry-pick-release-2.0, size/S, status/LGT2, status/can-merge

#1951 README: update go version
  README.md
Labels: require-LGT1, size/XS, status/LGT1, status/can-merge

#1905 test: resume task to fix unstable test case
  tests/shardddl1/run.sh
Labels: needs-cherry-pick-release-2.0, require-LGT1, size/XS, status/LGT1, status/can-merge

#1952 syncer: split functions of different shard mode
  syncer/optimist.go
  syncer/syncer.go
Labels: needs-cherry-pick-release-2.0, size/L, status/LGT2, status/can-merge

#1954 syncer: remove unreasonable context.Background()
  syncer/db.go
  syncer/db_test.go
  syncer/syncer.go
Labels: needs-cherry-pick-release-2.0, needs-update-release-note, size/S, status/LGT2, status/can-merge

#1856 relay: not watch whole dir to reduce cpu usage
  pkg/streamer/file.go
  pkg/streamer/file_test.go
  pkg/streamer/reader.go
  pkg/streamer/reader_test.go
  relay/relay.go
  relay/relay_test.go
  relay/transformer/transformer.go
Labels: status/LGT2, status/PTAL, needs-update-release-note, needs-cherry-pick-release-2.0, status/can-merge, size/XL

#1967 election: try manually resign
  pkg/election/election.go
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/S

#1949 syncer: move UpstreamConn into dbconn package
  dm/config/subtask.go
  dm/worker/worker_test.go
  dumpling/dumpling_test.go
  syncer/db_test.go
  syncer/dbconn/upstream_db.go
  syncer/dbconn/upstream_db_test.go
  syncer/handle_error.go
  syncer/handle_error_test.go
  syncer/heartbeat_test.go
  syncer/optimist.go
  syncer/relay.go
  syncer/schema.go
  syncer/streamer_controller.go
  syncer/syncer.go
  syncer/syncer_test.go
  syncer/util.go
  tests/initial_unit/run.sh
Labels: status/LGT2, status/PTAL, needs-cherry-pick-release-2.0, status/can-merge, size/XXL

#1972 test: disable relay and enable relay according to version
  relay/relay.go
  relay/writer/file_util.go
  tests/tiup/conf/source1.yaml
  tests/tiup/conf/source2.yaml
  tests/tiup/conf/topo.yaml
  tests/tiup/lib.sh
  tests/tiup/upgrade-from-v2.sh
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/M

#1960 cmd: add warning message when grpc proxy address env exists
  cmd/dm-ctl/main.go
  cmd/dm-master/main.go
  cmd/dm-worker/main.go
  go.mod
  pkg/utils/util.go
  pkg/utils/util_test.go
  tests/http_proxies/conf/dm-master.toml
  tests/http_proxies/conf/dm-worker1.toml
  tests/http_proxies/run.sh
  tests/others_integration.txt
Labels: status/LGT2, needs-update-release-note, needs-cherry-pick-release-2.0, first-time-contributor, status/can-merge, size/L

#1971 optimistic: fix optimist panic after table/source removed
  pkg/shardddl/optimism/keeper.go
  pkg/shardddl/optimism/lock.go
  tests/shardddl1/run.sh
Labels: status/LGT2, status/PTAL, type/bug-fix, needs-update-release-note, needs-cherry-pick-release-2.0, status/can-merge, size/L

#1986 election: always try to clean last election key
  pkg/election/election.go
Labels: status/LGT2, needs-update-release-note, needs-cherry-pick-release-2.0, status/can-merge, size/S

#1969 syncer: display correct error information when handle-error revert
  syncer/syncer.go
  tests/handle_error_3/run.sh
Labels: status/LGT2, needs-update-release-note, needs-cherry-pick-release-2.0, status/can-merge, size/M

#1990 .*: update changelog for v2.0.6
  CHANGELOG.md
Labels: status/LGT2, status/PTAL, type/CHANGELOG, status/can-merge, size/S

#1991 cherrypick #1971 and #1990 to release-2.0.6
  CHANGELOG.md
  pkg/shardddl/optimism/keeper.go
  pkg/shardddl/optimism/lock.go
  tests/shardddl1/run.sh
Labels: status/LGT2, status/PTAL, type/cherry-pick, size/L

#1992 test: add upgrade test for v2.0.6
  .github/workflows/upgrade-via-tiup.yml
Labels: status/LGT2, status/PTAL, type/test, status/can-merge, size/XS

#1938 chore: spilt others integration test
  tests/README.md
  tests/others_integration_1.txt
  tests/others_integration_2.txt
  tests/run.sh
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/S

#1981 tests: fix unstable tests
  tests/_utils/env_variables
  tests/_utils/shardddl_lib.sh
  tests/_utils/test_prepare
  tests/dmctl_basic/check_list/get_config.sh
  tests/full_mode/run.sh
  tests/ha/run.sh
  tests/ha_cases/lib.sh
  tests/ha_cases/run.sh
  tests/ha_cases2/lib.sh
  tests/ha_cases3/lib.sh
  tests/ha_cases3_1/lib.sh
  tests/ha_cases_1/lib.sh
  tests/ha_cases_1/run.sh
  tests/ha_cases_2/lib.sh
  tests/ha_cases_2/run.sh
  tests/ha_master/run.sh
  tests/shardddl1/run.sh
  tests/shardddl3/run.sh
  tests/sharding/run.sh
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/M

#1910 *: put source/task tls config into etcd
  _utils/terror_gen/errors_release.txt
  dm/config/security.go
  dm/config/security_test.go
  dm/config/task.go
  dm/config/task_test.go
  dm/ctl/master/operate_source.go
  dm/ctl/master/start_task.go
  dm/master/server.go
  dumpling/dumpling.go
  dumpling/dumpling_test.go
  errors.toml
  go.mod
  go.sum
  pkg/conn/basedb.go
  pkg/ha/bound_test.go
  pkg/ha/ops_test.go
  pkg/ha/relay_test.go
  pkg/ha/source_test.go
  pkg/log/log.go
  pkg/log/log_test.go
  pkg/schema/tracker.go
  pkg/schema/tracker_test.go
  pkg/terror/error_list.go
  pkg/utils/common.go
  relay/relay.go
  syncer/syncer.go
  tests/full_mode/run.sh
  tests/handle_error/run.sh
  tests/handle_error_2/run.sh
  tests/handle_error_3/run.sh
  tests/tls/conf/diff_config.toml
  tests/tls/conf/dm-task.yaml
  tests/tls/conf/dm-worker2.toml
  tests/tls/conf/source1.yaml
  tests/tls/run.sh
Labels: status/LGT2, status/can-merge, size/XXL

#1928 syncer: stop/pause until reached the end of a transaction
  syncer/syncer.go
  tests/checkpoint_transaction/conf/diff_config.toml
  tests/checkpoint_transaction/conf/dm-master.toml
  tests/checkpoint_transaction/conf/dm-task.yaml
  tests/checkpoint_transaction/conf/dm-worker1.toml
  tests/checkpoint_transaction/conf/source1.yaml
  tests/checkpoint_transaction/data/db1.increment1.sql
  tests/checkpoint_transaction/data/db1.increment2.sql
  tests/checkpoint_transaction/data/db1.prepare.sql
  tests/checkpoint_transaction/run.sh
  tests/others_integration_1.txt
Labels: status/LGT2, needs-update-release-note, needs-cherry-pick-release-2.0, status/can-merge, size/XL

#2003 test: fix unstable metrics test
  tests/all_mode/run.sh
  tests/case_sensitive/run.sh
  tests/gtid/run.sh
  tests/metrics/run.sh
  tests/only_dml/run.sh
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/M

#2001 test: fix upgrade via tiup ci
  tests/tiup/docker/readme.md
  tests/tiup/upgrade-from-v1.sh
Labels: status/LGT2, status/PTAL, needs-cherry-pick-release-2.0, status/can-merge, size/XS

#2008 scheduler: try bind free worker to source in start scheduler
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
Labels: status/LGT2, type/bug-fix, needs-cherry-pick-release-2.0, status/can-merge, size/M

#1746 dmctl: fix handle err commands
  dm/ctl/ctl.go
  dm/ctl/master/binlog.go
  dm/ctl/master/check_task.go
  dm/ctl/master/config.go
  dm/ctl/master/get_config.go
  dm/ctl/master/handle_error.go
  dm/ctl/master/list_member.go
  dm/ctl/master/offline_member.go
  dm/ctl/master/operate_leader.go
  dm/ctl/master/operate_schema.go
  dm/ctl/master/operate_source.go
  dm/ctl/master/pause_relay.go
  dm/ctl/master/pause_task.go
  dm/ctl/master/purge_relay.go
  dm/ctl/master/query_status.go
  dm/ctl/master/resume_relay.go
  dm/ctl/master/resume_task.go
  dm/ctl/master/shard_ddl_lock.go
  dm/ctl/master/show_ddl_locks.go
  dm/ctl/master/source_table_schema.go
  dm/ctl/master/start_stop_relay.go
  dm/ctl/master/start_task.go
  dm/ctl/master/stop_task.go
  dm/ctl/master/transfer_source.go
  dm/ctl/master/unlock_ddl_lock.go
  dm/ctl/master/update_task.go
  tests/dmctl_advance/check_list/binlog.sh
  tests/dmctl_advance/check_list/source_table_schema.sh
  tests/dmctl_advance/check_list/unlock_ddl_lock.sh
  tests/dmctl_advance/run.sh
  tests/dmctl_basic/check_list/config.sh
  tests/dmctl_basic/check_list/show_ddl_locks.sh
  tests/dmctl_basic/run.sh
  tests/dmctl_command/run.sh
  tests/ha_master/run.sh
  tests/handle_error/run.sh
  tests/handle_error_2/run.sh
  tests/handle_error_3/run.sh
  tests/import_v10x/run.sh
  tests/new_relay/run.sh
  tests/sequence_sharding_optimistic/run.sh
  tests/sequence_sharding_removemeta/run.sh
  tests/shardddl1/run.sh
  tests/shardddl3_1/run.sh
  tests/shardddl4/run.sh
  tests/shardddl4_1/run.sh
  tests/tiup/upgrade-from-v2.sh
Labels: needs-update-docs, status/LGT2, needs-update-release-note, needs-cherry-pick-release-2.0, status/can-merge, size/XXL

#2006 syncer: refine syncer log for handleRowsEvent
  syncer/syncer.go
  tests/downstream_more_column/conf/dm-task-incremental.yaml
  tests/downstream_more_column/conf/dm-task.yaml
  tests/downstream_more_column/data/db1.increment.sql
  tests/downstream_more_column/data/db1.increment2.sql
  tests/downstream_more_column/data/db1.prepare.sql
  tests/downstream_more_column/data/tidb.prepare.sql
  tests/downstream_more_column/run.sh
Labels: status/LGT2, needs-update-release-note, needs-cherry-pick-release-2.0, status/can-merge, size/M

#2007 test: fix unstable TestPurgeWorkerRelay
  dm/master/server_test.go
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/S

#2015 dmctl: add config err log
  dm/ctl/common/config.go
Labels: status/LGT2, needs-update-release-note, contribution, needs-cherry-pick-release-2.0, first-time-contributor, status/can-merge, size/XS

#2014 syncer: add retry for binlog event streamer
  syncer/streamer_controller.go
  syncer/streamer_controller_test.go
  syncer/syncer.go
  tests/drop_column_with_index/run.sh
  tests/incremental_mode/run.sh
Labels: status/LGT2, needs-update-release-note, needs-cherry-pick-release-2.0, status/can-merge, size/L

#2022 test: fix unstable test metrics
  syncer/syncer.go
  tests/metrics/run.sh
Labels: status/LGT1, needs-cherry-pick-release-2.0, status/can-merge, size/S, require-LGT1

#2024 syncer, loader: make warn log message more accurate
  loader/db.go
  syncer/dbconn/db.go
Labels: status/LGT2, needs-update-release-note, contribution, needs-cherry-pick-release-2.0, first-time-contributor, status/can-merge, size/M

#2018 test: fix ci lark push
  .github/workflows/upgrade-via-tiup.yml
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/S

#2020 test: swap some test cases to make use of enabled task checker
  tests/_utils/test_prepare
  tests/shardddl1/run.sh
  tests/shardddl2/run.sh
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XXL

#2037 test: fix unstable retry resume-task
  tests/incremental_mode/run.sh
  tests/sequence_sharding_optimistic/run.sh
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/S

#2041 test: increase unit test timeout
  Makefile
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XS

#2033 test: fix metrics again
  syncer/syncer.go
  tests/_utils/check_ticker_interval
  tests/metrics/run.sh
Labels: status/LGT2, status/can-merge, size/S

#2039 config: adjust OnlineDDL in subtask config
  dm/config/subtask.go
  dm/config/subtask_test.go
Labels: status/LGT2, needs-update-release-note, needs-cherry-pick-release-2.0, status/can-merge, size/S

#2044 test: fix unstable kill worker
  tests/_utils/ha_cases_lib.sh
  tests/all_mode/run.sh
  tests/ha_cases/run.sh
  tests/ha_cases2/lib.sh
  tests/ha_cases2/run.sh
  tests/ha_cases3/lib.sh
  tests/ha_cases3/run.sh
  tests/ha_cases3_1/lib.sh
  tests/ha_cases3_1/run.sh
  tests/ha_cases_1/lib.sh
  tests/ha_cases_1/run.sh
  tests/ha_cases_2/lib.sh
  tests/ha_cases_2/run.sh
Labels: status/LGT2, needs-cherry-pick-release-2.0, status/can-merge, size/XXL

#2036 test: try to write something when init()
  cmd/dm-master/main_test.go
  pkg/printinit/noimport.go
Labels: status/LGT2, status/can-merge, size/S

#2065 tracker: disable background statistic job
  pkg/schema/tracker.go
Labels: status/LGT1, needs-update-release-note, needs-cherry-pick-release-2.0, status/can-merge, size/S, require-LGT1

#2040 test: fix TestParseFilerelayLogUpdatedOrNewCreated
  pkg/streamer/reader_test.go
Labels: status/LGT1, needs-cherry-pick-release-2.0, status/can-merge, size/XS, require-LGT1
