Repository pingcap/dm, pull requests merged in 2021-03, with the labels that each got.

#1448 syncer: update active relay log at fake rotate event
  pkg/binlog/common/replication.go
  pkg/streamer/streamer.go
  syncer/relay.go
  syncer/syncer.go
  tests/incremental_mode/run.sh
  tests/only_dml/conf/diff_config.toml
  tests/only_dml/conf/dm-master.toml
  tests/only_dml/conf/dm-task.yaml
  tests/only_dml/conf/dm-worker1.toml
  tests/only_dml/conf/dm-worker2.toml
  tests/only_dml/conf/source1.yaml
  tests/only_dml/conf/source2.yaml
  tests/only_dml/data/db1.prepare.sql
  tests/only_dml/data/db2.prepare.sql
  tests/only_dml/run.sh
  tests/others_integration.txt
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT1

#1456 dep: update parser, dumpling, tidb
  dumpling/dumpling.go
  dumpling/metrics.go
  go.mod
  go.sum
  pkg/schema/tracker.go
  pkg/schema/tracker_test.go
  tests/full_mode/run.sh
  tests/sequence_sharding_optimistic/run.sh
  tests/shardddl1/run.sh
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-2.0, status/LGT2

#1477 conn: add timeout for ping
  pkg/conn/basedb.go
Labels: needs-cherry-pick-2.0, needs-update-release-note

#1479 shardddl: support combine ddls in one sql for optimistic sharding mode
  _utils/terror_gen/errors_release.txt
  dm/master/server_test.go
  dm/master/shardddl/optimist_test.go
  errors.toml
  pkg/ha/keepalive.go
  pkg/shardddl/optimism/info.go
  pkg/shardddl/optimism/info_test.go
  pkg/shardddl/optimism/keeper.go
  pkg/shardddl/optimism/keeper_test.go
  pkg/shardddl/optimism/lock.go
  pkg/shardddl/optimism/lock_test.go
  pkg/terror/error_list.go
  relay/meta_test.go
  syncer/optimist.go
  syncer/shardddl/optimist.go
  syncer/shardddl/optimist_test.go
  tests/shardddl2/run.sh
Labels: needs-update-release-note, status/LGT2, status/PTAL, type/feature-request

#1467 config: disable heartbeat feature
  dm/config/task.go
  dm/config/task_test.go
  pkg/v1workermeta/api.go
  tests/import_v10x/conf/task.yaml
  tests/tiup/conf/task.yaml
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT2

#1483 dmctl: change help message
  dm/ctl/ctl.go
Labels: needs-cherry-pick-2.0, needs-update-docs, status/LGT2

#1464 relay, binlog: don't truncate relay log that only contains headers
  pkg/binlog/reader/file.go
  relay/writer/file_util.go
  relay/writer/file_util_test.go
Labels: needs-cherry-pick-2.0, status/LGT2

#1473 test: add a test about pause/resume relay when sync data
  tests/all_mode/run.sh
Labels: needs-cherry-pick-2.0, status/LGT1

#1489 error: show origin ddl when error
  syncer/job.go
  syncer/job_test.go
  syncer/optimist.go
  syncer/syncer.go
  tests/handle_error/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT2, status/PTAL, status/can-merge, type/feature-request

#1480 tests/: add DM CASE 104~112
  errors.toml
  go.mod
  go.sum
  pkg/shardddl/optimism/lock.go
  pkg/shardddl/optimism/lock_test.go
  tests/run.sh
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-2.0, status/LGT2, status/can-merge, type/test

#1497 loader: don't use ANSI_QUOTES for dumped data files
  loader/convert_data.go
  loader/loader.go
  tests/safe_mode/conf/dm-task.yaml
  tests/safe_mode/data/db1.prepare.sql
  tests/safe_mode/data/db2.prepare.sql
  tests/safe_mode/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT1

#1496 optimist: only update table info if no conflict
  dm/ctl/ctl.go
  pkg/shardddl/optimism/lock.go
  pkg/shardddl/optimism/lock_test.go
  tests/handle_error/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT2, status/PTAL, status/can-merge, type/bug-fix

#1476 binlog, relay: support binlog sequence number larger than 999999
  .github/workflows/binlog-999999.yml
  go.mod
  go.sum
  pkg/binlog/filename.go
  pkg/binlog/filename_test.go
  relay/writer/file.go
  tests/binlog_999999/docker-compose.yml
  tests/incremental_mode/data/db1.increment.sql
  tests/incremental_mode/data/db2.increment.sql
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT2

#1499 ha: add RelayConfig related function
  _utils/terror_gen/errors_release.txt
  dm/common/common.go
  errors.toml
  pkg/ha/bound.go
  pkg/ha/relay.go
  pkg/ha/relay_test.go
  pkg/terror/error_list.go
  relay/retry/reader.go
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT1, status/PTAL

#1492 dmctl, scheduler: support manually transfer-source
  _utils/terror_gen/errors_release.txt
  dm/ctl/ctl.go
  dm/ctl/master/transfer_source.go
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
  dm/master/server.go
  dm/pb/dmmaster.pb.go
  dm/proto/dmmaster.proto
  errors.toml
  go.mod
  go.sum
  pkg/ha/bound.go
  pkg/terror/error_list.go
  tests/dmctl_basic/check_list/operate_source.sh
  tests/dmctl_basic/check_list/transfer_source.sh
  tests/dmctl_basic/run.sh
  tests/dmctl_command/run.sh
  tests/ha/run.sh
Labels: needs-cherry-pick-2.0, needs-update-docs, needs-update-release-note, status/LGT1

#1507 worker: move relay/subtask related function together
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  tests/sequence_sharding_optimistic/run.sh
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, status/can-merge

#1506 operate-schema: flush schema info and sync to master in optimistic mode
  dm/ctl/master/operate_schema.go
  dm/master/server.go
  dm/master/shardddl/optimist.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmworker.pb.go
  dm/pbmock/dmmaster.go
  dm/proto/dmmaster.proto
  dm/proto/dmworker.proto
  go.sum
  pkg/shardddl/optimism/info.go
  pkg/shardddl/optimism/info_test.go
  pkg/shardddl/optimism/keeper.go
  pkg/shardddl/optimism/lock.go
  pkg/shardddl/optimism/lock_test.go
  syncer/checkpoint.go
  syncer/schema.go
  tests/handle_error/run.sh
  tests/shardddl1/conf/source1.yaml
  tests/shardddl1/conf/source2.yaml
  tests/shardddl1/run.sh
Labels: needs-cherry-pick-2.0, needs-update-docs, needs-update-release-note, status/LGT1, status/PTAL

#1522 dependency: remove alter-primary config
  go.mod
  go.sum
  pkg/schema/tracker.go
  tests/sequence_sharding_optimistic/run.sh
  tests/shardddl1/run.sh
  tests/shardddl3/conf/tidb-alter-pk-config.toml
  tests/shardddl3/run.sh
Labels: dependencies, needs-cherry-pick-2.0, status/PTAL

#1508 worker: enable relay and handling subtask on demand
  _utils/terror_gen/errors_release.txt
  dm/config/subtask.go
  dm/master/bootstrap.go
  dm/worker/join.go
  dm/worker/relay.go
  dm/worker/relay_test.go
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/subtask.go
  dm/worker/subtask_holder.go
  dm/worker/task_checker.go
  dm/worker/task_checker_test.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  errors.toml
  go.mod
  go.sum
  pkg/ha/subtask.go
  pkg/ha/subtask_test.go
  pkg/terror/error_list.go
  pkg/upgrade/upgrade.go
  relay/metrics.go
  relay/relay.go
  tests/ha_cases/lib.sh
  tests/ha_cases/run.sh
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL

#1526 *： remove redundant type conversions
  debug-tools/binlog-event-blackhole/fetcher.go
  dm/master/server.go
  pkg/binlog/event/event.go
  pkg/binlog/event/event_test.go
  pkg/utils/relay.go
  relay/writer/file_util_test.go
  syncer/db_test.go
  syncer/dml.go
  syncer/syncer_test.go
Labels: size/S, status/LGT2, status/can-merge

#1525 streamer: fix duplicate event when reparse relay using GTID
  pkg/streamer/reader.go
  pkg/streamer/reader_test.go
Labels: needs-cherry-pick-2.0, size/L, status/LGT2, status/PTAL, status/can-merge

#1521 master: add etcd compaction and quota config
  dm/master/config.go
  dm/master/config_test.go
  dm/master/server_test.go
  tests/all_mode/conf/dm-master.toml
  tests/dm_syncer/conf/dm-master.toml
  tests/dmctl_advance/conf/dm-master.toml
  tests/dmctl_basic/conf/get_master1.toml
  tests/dmctl_command/conf/dm-master.toml
  tests/drop_column_with_index/conf/dm-master.toml
  tests/full_mode/conf/dm-master.toml
  tests/gtid/conf/dm-master.toml
  tests/ha/conf/dm-master1.toml
  tests/ha/conf/dm-master2.toml
  tests/ha/conf/dm-master3.toml
  tests/ha/conf/dm-master4.toml
  tests/ha/conf/dm-master5.toml
  tests/ha/conf/dm-master6.toml
  tests/ha_cases/conf/dm-master-join1.toml
  tests/ha_cases/conf/dm-master-join2.toml
  tests/ha_cases/conf/dm-master-join3.toml
  tests/ha_cases/conf/dm-master-join4.toml
  tests/ha_cases/conf/dm-master-join5.toml
  tests/ha_cases/conf/dm-master1.toml
  tests/ha_cases/conf/dm-master2.toml
  tests/ha_cases/conf/dm-master3.toml
  tests/ha_master/conf/dm-master-join1.toml
  tests/ha_master/conf/dm-master1.toml
  tests/ha_master/conf/dm-master2.toml
  tests/ha_master/conf/dm-master3.toml
  tests/ha_master/conf/dm-master4.toml
  tests/ha_master/conf/dm-master5.toml
  tests/handle_error/conf/dm-master.toml
  tests/http_apis/conf/dm-master.toml
  tests/import_goroutine_leak/conf/dm-master.toml
  tests/import_v10x/conf/dm-master.toml
  tests/incremental_mode/conf/dm-master.toml
  tests/initial_unit/conf/dm-master.toml
  tests/load_interrupt/conf/dm-master.toml
  tests/many_tables/conf/dm-master.toml
  tests/online_ddl/conf/dm-master.toml
  tests/only_dml/conf/dm-master.toml
  tests/print_status/conf/dm-master.toml
  tests/relay_interrupt/conf/dm-master.toml
  tests/retry_cancel/conf/dm-master.toml
  tests/safe_mode/conf/dm-master.toml
  tests/sequence_safe_mode/conf/dm-master.toml
  tests/sequence_sharding/conf/dm-master.toml
  tests/sequence_sharding_optimistic/conf/dm-master.toml
  tests/sequence_sharding_removemeta/conf/dm-master.toml
  tests/shardddl1/conf/dm-master.toml
  tests/shardddl2/conf/dm-master.toml
  tests/shardddl3/conf/dm-master.toml
  tests/sharding/conf/dm-master.toml
  tests/sharding2/conf/dm-master.toml
  tests/start_task/conf/dm-master.toml
  tests/tls/conf/dm-master1.toml
  tests/tls/conf/dm-master2.toml
  tests/tls/conf/dm-master3.toml
  tests/upstream_switch/conf/dm-master.toml
Labels: needs-cherry-pick-2.0, needs-update-release-note, size/L, status/LGT2, status/PTAL, status/can-merge

#1512 sync: return an error for rename table statement in optimistic mode
  _utils/terror_gen/errors_release.txt
  errors.toml
  go.sum
  pkg/terror/error_list.go
  syncer/syncer.go
  tests/shardddl1/run.sh
Labels: needs-cherry-pick-2.0, needs-update-docs, needs-update-release-note, size/M, status/LGT1, status/PTAL

#1518 bug-fix: use table-info-before always and fix bug for recover lock in optimistic
  _utils/terror_gen/errors_release.txt
  dm/master/server_test.go
  dm/master/shardddl/optimist.go
  dm/master/shardddl/optimist_test.go
  errors.toml
  pkg/shardddl/optimism/info.go
  pkg/shardddl/optimism/info_test.go
  pkg/shardddl/optimism/keeper.go
  pkg/shardddl/optimism/keeper_test.go
  pkg/shardddl/optimism/lock.go
  pkg/shardddl/optimism/lock_test.go
  pkg/shardddl/optimism/ops_test.go
  pkg/terror/error_list.go
  syncer/schema.go
  syncer/shardddl/optimist_test.go
  tests/shardddl1/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, size/XXL, status/LGT2, status/PTAL, type/bug-fix

#1510 shardddl/optimistic: warn add not fully dropped columns
  _utils/terror_gen/errors_release.txt
  dm/common/common.go
  dm/master/server_test.go
  dm/master/shardddl/optimist.go
  dm/master/shardddl/optimist_test.go
  dm/master/shardddl/pessimist_test.go
  dm/worker/task_checker_test.go
  errors.toml
  go.sum
  loader/util.go
  loader/util_test.go
  monitoring/dashboards/dashboard.go
  pkg/etcdutil/etcdutil.go
  pkg/ha/bound.go
  pkg/ha/stage.go
  pkg/shardddl/optimism/column.go
  pkg/shardddl/optimism/column_test.go
  pkg/shardddl/optimism/info.go
  pkg/shardddl/optimism/info_test.go
  pkg/shardddl/optimism/keeper.go
  pkg/shardddl/optimism/keeper_test.go
  pkg/shardddl/optimism/lock.go
  pkg/shardddl/optimism/lock_test.go
  pkg/shardddl/optimism/operation.go
  pkg/shardddl/optimism/operation_test.go
  pkg/shardddl/optimism/ops.go
  pkg/shardddl/optimism/ops_test.go
  pkg/terror/error_list.go
  pkg/utils/db_test.go
  syncer/err-operator/operator.go
  syncer/optimist.go
  syncer/shardddl/optimist.go
  syncer/shardddl/optimist_test.go
  tests/_utils/test_prepare
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-2.0, needs-update-docs, needs-update-release-note, size/XXL, status/LGT2, status/can-merge

#1538 test: align with TiDB clustered index behaviour
  tests/sequence_sharding_optimistic/run.sh
  tests/shardddl3/conf/tidb-alter-pk-config.toml
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-2.0, size/S, status/LGT2, status/PTAL, status/can-merge

#1511 worker, ha: separate etcd message for subtask and relay
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
  dm/worker/join.go
  dm/worker/metrics.go
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/subtask.go
  dm/worker/subtask_holder.go
  dm/worker/worker_test.go
  pkg/ha/bound.go
  pkg/ha/keepalive.go
  pkg/ha/ops.go
  pkg/ha/ops_test.go
  pkg/ha/relay.go
  syncer/syncer.go
  tests/ha_cases/run.sh
  tests/import_goroutine_leak/conf/source1.yaml
  tests/import_goroutine_leak/run.sh
Labels: needs-cherry-pick-2.0, size/XXL, status/LGT2, status/PTAL, status/can-merge

#1466 load: restore schemas in parallel
  .gitignore
  Dockerfile
  loader/loader.go
  loader/loader_test.go
  tests/README.md
  tests/_utils/env_variables
  tests/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, rewarded, size/XL, status/LGT2, status/can-merge

#1541 test: fix unstable CI caused by concurrent unit test
  dm/master/shardddl/optimist_test.go
Labels: needs-cherry-pick-2.0, size/XS, status/LGT2, status/can-merge

#1548 test: fix unstabled drop then add column
  tests/sequence_sharding_optimistic/data/db1.increment.sql
  tests/sequence_sharding_optimistic/data/db1.increment2.sql
  tests/shardddl1/run.sh
  tests/shardddl3/run.sh
Labels: needs-cherry-pick-2.0, size/M, status/LGT2, status/can-merge
