Repository pingcap/dm, pull requests merged in 2021-01, with the labels that each got.

#1367 chaos: integrate mysql-8 and mariadb
  .github/workflows/chaos-mesh.yml
  chaos/cases/conf/source1.yaml
  chaos/cases/conf/source2.yaml
  chaos/cases/conf/source3.yaml
  chaos/cases/conf/task-optimistic.yaml
  chaos/cases/conf/task-pessimistic.yaml
  chaos/cases/conf/task-single.yaml
  chaos/cases/config.go
  chaos/cases/main.go
  chaos/cases/source.go
  chaos/cases/task.go
  chaos/manifests/dm-worker.yaml
  chaos/manifests/mysql.yaml
  chaos/manifests/sources.yaml
Labels: priority/normal, status/PTAL, type/test

#1366 dep: check some privilege should be globally granted
  checker/check_test.go
  go.mod
  go.sum
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT1

#1372 test: fix test isn't suitable for an unordered output
  checker/check_test.go
Labels: needs-cherry-pick-2.0, priority/unimportant, status/PTAL

#1375 dep: check some privilege should be globally granted (#1366)
  checker/check_test.go
  go.mod
  go.sum
Labels: status/LGT1

#1376 chaos: half time per round
  chaos/cases/task.go
Labels: severity/minor, status/PTAL, type/test

#1369 test: refine some tests
  pkg/parser/common_test.go
  syncer/syncer_test.go
Labels: needs-cherry-pick-2.0, status/LGT1

#1382 util: fix status_vars can't parse more than one 0-terminated string
  pkg/binlog/event/util.go
  pkg/binlog/event/util_test.go
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT1

#1378 loader: fix loader lost data when quickly starts/stops task
  loader/loader.go
  tests/all_mode/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT1, type/bug-fix

#1385 config: fix empty flavor for source
  dm/config/source_config.go
  dm/master/server.go
  dm/worker/source.yaml
  pkg/gtid/gtid.go
  pkg/gtid/gtid_test.go
  relay/meta.go
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT1, status/PTAL, type/bug-fix

#1373 *: last bound source is prior to other source when pick for bound
  dm/common/common.go
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
  pkg/ha/bound.go
  pkg/ha/ops.go
  pkg/ha/source.go
  tests/ha_cases/lib.sh
  tests/ha_cases/run.sh
Labels: needs-cherry-pick-2.0, needs-update-docs, needs-update-release-note, status/LGT1

#1370 feat: source level filter support
  _utils/terror_gen/errors_release.txt
  dm/config/source_config.go
  dm/config/source_config_test.go
  dm/config/task.go
  dm/master/bootstrap_test.go
  dm/worker/server.go
  dm/worker/worker.go
  dm/worker/worker_test.go
  errors.toml
  pkg/terror/error_list.go
  tests/dmctl_basic/conf/dm-task.yaml
  tests/dmctl_basic/conf/get_source1.yaml
  tests/dmctl_basic/conf/get_source2.yaml
  tests/dmctl_basic/conf/get_task.yaml
  tests/dmctl_basic/conf/source1.yaml
  tests/dmctl_basic/run.sh
Labels: needs-cherry-pick-2.0, needs-update-docs, needs-update-release-note, status/LGT1, status/PTAL, type/feature

#1393 syncer, relay: support incremental task with gtid specified only
  pkg/binlog/event/util.go
  pkg/streamer/reader.go
  relay/relay.go
  syncer/checkpoint.go
  syncer/relay.go
  syncer/status.go
  syncer/syncer.go
  tests/incremental_mode/conf/source1.yaml
  tests/incremental_mode/run.sh
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT1

#1351 Quality reinforcement (8): fix unstable test cases
  relay/relay.go
  tests/_utils/wait_until_sync
  tests/sequence_sharding/run.sh
Labels: needs-cherry-pick-2.0, status/LGT1, type/test

#1390 relay: align with MySQL when using GTID
  _utils/terror_gen/errors_release.txt
  chaos/cases/conf/source3.yaml
  errors.toml
  pkg/binlog/event/event.go
  pkg/binlog/reader/util.go
  pkg/binlog/reader/util_test.go
  pkg/streamer/reader.go
  pkg/streamer/reader_test.go
  pkg/terror/error_list.go
  relay/relay.go
  relay/relay_test.go
  relay/transformer/transformer.go
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT2, status/PTAL, type/bug-fix

#1404 streamer: add heartbeat for local streamer
  pkg/streamer/reader_test.go
  pkg/streamer/streamer.go
  pkg/streamer/streamer_test.go
Labels: needs-cherry-pick-2.0, needs-update-release-note, status/LGT2

#1407 README: add more info
  README.md
Labels: status/LGT2
